### ISSUE TITLE
`glide pin` and other commands which print to stdout are hard to use

### ISSUE THREAD

**Issue by albrow** [Masterminds/glide#100]
`glide pin` seems like a very useful command. However, it is really hard to use because of the way it prints to stdout. My first instinct was to run `glide pin > glide.yaml` but that overwrites my glide.yaml file with `Oops! Top YAML node must be a map.` How am I supposed to actually use `glide pin`? The best I can come up with is to copy the output from my terminal and paste it into glide.yaml. Or to write the results to a temporary file `glide pin > glide.yaml.new` and then copy it with `rm glide.yaml; mv glide.yaml.new glide.yaml`. This is really inconvenient. 

I'm only guessing here, but I think the idea is that printing to stdout because is safer than editing glide.yaml directly. However, what has happened to me is that is causes more problems, not less. I think `glide pin` and similar commands that currently print to stdout should just modify glide.yaml directly. It's less likely that users of glide will screw something up and it's more intuitive.

**Comment by albrow** [comment]
I see after looking at the `glide help pin` that you can provide a filename as the second argument. That's much better than just always printing to stdout, but it still strikes me as inconsistent for two reasons. 1) Many other commands like `glide install`, `glide update`, etc. use glide.yaml as the default filename and have a flag for changing it. 2) At least one other command, `glide get`, writes to glide.yaml directly. Why is it okay for `glide get` to write to glide.yaml but not for `glide pin`, `glide guess`, or others?

**Comment by mattfarina** [comment]
Thanks for the feedback. There's a discussion going on #85 around modifying the way `glide pin` works to make it more useful. Can you take a look at the suggestions there?

**Comment by dnephin** [comment]
I think there are some issues here that aren't covered by #85.

1) `Info()` writes to stdout instead of stderr. So trying to do `glide import godeps > tmp` creates an invalid yaml file, beucase the `[Info]`line is in the stdout.  I think all log messages (info, debug) should go to stderr so they don't conflict with commands that write the "normal program output" to stdout.
2) `glide import` doesn't accept a filename , so there's no option to write it directly to `glide.yaml` or any other file

Let me know if you feel there should be a separate issue for either of these

**Comment by technosophos** [comment]
Yeah, can you file two separate issues for those? We need to fix both of them.

**Comment by dnephin** [comment]
cool, created #104  and #105

**Comment by ches** [comment]
Just scanning through issues, seems like this can be closed at this point.

**Comment by mattfarina** [comment]
Command output not prints to stdErr, which is common. Any output that should be passed to another command goes to stdout.
