### ISSUE TITLE
Info and Debug messages are sent to stdout (pollutes normal program output)

### ISSUE THREAD

**Issue by dnephin** [Masterminds/glide#104]
From #100 

`Info()` writes to stdout instead of stderr. So trying to do `glide import godeps > tmp` creates an invalid yaml file, beucase the `[Info]` line is in the stdout. I think all log messages (info, debug) should go to stderr so they don't conflict with commands that write the "normal program output" to stdout.

**Comment by technosophos** [comment]
Is there a precedent for writing non-error information to stderr? If this is the way it should be done, it should be a nice easy change for us to make. Just msg.go and msg_windows.go need to be changed.

**Comment by dnephin** [comment]
I'm having trouble finding a reference, but the rule I follow is:

stdout is for "normal program output". Ex: `glide import` should output the configuration to stdout

[stderr is for everthing else](http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout).

In this case logging of actions it not "normal program output". 

I believe the golang log module uses stderr for all messages (https://golang.org/pkg/log/)

**Comment by technosophos** [comment]
That's good enough for me. Fixed. This actually makes several things much easier.

It's on the `feature/flatten` branch right now, but will merge into Master hopefully this week.
