### ISSUE TITLE
Unable to export dependencies to vendor directory: Unable to export source: exit status 128

### ISSUE THREAD

**Issue by ychdesign** [Masterminds/glide#1045]
glide version : 0.13.2
os:windows
issues:
[ERROR] Export failed for github.com/hashicorp/consul: Unable to export source: exit status 128
[ERROR] Unable to export dependencies to vendor directory: Unable to export source: exit status 128

My project depends on  github.com/hashicorp/consul. I use glide install,but occuers err. I found the package has already in the cache file  ./glide/cache/src. Only this cont be exported to vender.I tried many times,it failed on windows. however it works ok on macos.I need some information  about the err

**Comment by xexiyong** [comment]
same error occurs in mine

**Comment by whendream** [comment]
Have you solved this problem now?
