### ISSUE TITLE
 `glide import` doesn't accept a filename for output path

### ISSUE THREAD

**Issue by dnephin** [Masterminds/glide#105]
From #100 

 `glide import` doesn't accept a filename , so there's no option to write it directly to `glide.yaml` or any other file. Other commands (like `pin`) all accept a filename for output

**Comment by technosophos** [comment]
On the new `feature/flatten` branch, all import commands accept `-f outfile.yaml`. This matches the design for `glide up -f modified.yaml`.

As soon as this is merged, we can mark this resolved.

**Comment by technosophos** [comment]
This has been merged. Please let me know if it's not working as expected.
