### ISSUE TITLE
Error when repository URL have sub levels

### ISSUE THREAD

**Issue by jaswdr** [Masterminds/glide#1052]
Glide did not work when a repository have more levels, like `https://gitlab.com/vendor/project/repository`, the error like the message bellow is printed:

```
[ERROR] Error scanning gitlab.com/jaswdr/project/repo/package: cannot find package "." in:
        /home/jaswdr/.glide/cache/src/git-gitlab.com-jaswdr-project-repo.git/package
```

**Comment by mojtabacazi** [comment]
@jaswdr Did you find a solution?

**Comment by jaswdr** [comment]
@mojtabacazi I give up and started to use another package manager, when I opened this I didn't have time to fix it by myself, today I don't have any interest anymore in the glide project.
