### ISSUE TITLE
How to ONLY get a package and NOT UPDATE the entire vendor?

### ISSUE THREAD

**Issue by jaswdr** [Masterminds/glide#1058]
I want ONLY to install a single package and it dependencies, how can I do this with glide? I didn't want to update my entirely vendor.

**Comment by edupaim** [comment]
Why do you intend to upgrade only 1 package?

**Comment by jaswdr** [comment]
@edupaim is not upgrade, when I use `glide get <module>` it always update all dependencies, even if I only want to get that single package, but never mind I migrate to `go mod`, thanks.
