### ISSUE TITLE
glide get FAILURE

### ISSUE THREAD

**Issue by sandeeplinux** [Masterminds/glide#107]
We are using Atlassain Stash with no https.
```glide get``` fails with stash package but works with github package.
Error is  => ```Oops! Cannot detect VCS```

go get stash with golang 1.5 fails. we are using --insecure tag to get the the pacakge.
```go get --insecure stash/package```.  i need to pass --insecure tag on go get. please update

**Comment by mattfarina** [comment]
Adding the `--insecure` flag makes sense. there are a few places we assume `https://`.

**Comment by sandeeplinux** [comment]
we dont use https.
will it create a problem even though --insecure tag is added?

**Comment by mattfarina** [comment]
@sandeeplinux I added the `--insecure` flag. Can you try the latest code on master `go get -u github.com/Masterminds/glide`. If this doesn't work please re-open the issue.

**Comment by sandeeplinux** [comment]
Thank you. It worked
