### ISSUE TITLE
glide package change: github.com/codegangsta/cli to github.com/urfave/cli

### ISSUE THREAD

**Issue by BogdanRS** [Masterminds/glide#1079]
An update is needed for this, as it can't be downloaded.
<img width="509" alt="Screenshot 2021-02-25 at 01 56 02" src="https://user-images.githubusercontent.com/51833259/109082411-a1098280-770c-11eb-956b-c1dbc5ec0464.png">

**Comment by BraveShadow** [comment]
Hi, I'm getting the same problem, how did you solve it?

**Comment by sandrozbinden** [comment]
I am getting the same error when trying to get the go module on osx with the following command:

`go get github.com/Masterminds/glide`

I will repost the error message as text so that it can be indexed for searching. 

```shell
go get: github.com/codegangsta/cli@none updating to
  github.com/codegangsta/cli@v1.22.5: parsing go.mod:
  module declares its path as: github.com/urfave/cli
    but was required as: github.com/codegangsta/cli
```
