### ISSUE TITLE
Mutiple vendor : Recursive vendor

### ISSUE THREAD

**Issue by sandeeplinux** [Masterminds/glide#111]
I would like to request a feature which can make us to avoid duplicates.
For example X depends on Y and Z depends on Y. Then Z->vendor(Y->Vendor(X)) which is current scenario.  I would like to propose Z -> vendor (X,Y). Reason: for our Z depends on X also. In that case it will save another copy in vendor, Z->vendor(X, Y->Vendor(X)) according to present glide. Few times it stores local service in vendor and searches in vendor instead of searching locally. That would save space for us and compiling would be easy.

**Comment by technosophos** [comment]
The branch `feature/flatten` is our revised way of doing this. It moves all dependencies to the top `vendor` directory (there are no more nested vendor directories). I think that accomplishes what you are asking for.

**Comment by technosophos** [comment]
`feature/flatten` has been merged. Please re-open this if you feel like there's still something we should do here.

**Comment by sandeeplinux** [comment]
Is --insecure registry https://github.com/Masterminds/glide/issues/107 working with new merge? 
It seems it is not working for me.please update

**Comment by mattfarina** [comment]
@sandeeplinux what command were you trying to use the `--insecure` flag on?

**Comment by sandeeplinux** [comment]
I was trying to use glide to get stash packages on HTTP 
`glide get --insecure stash/package`
