### ISSUE TITLE
I think the flattening feature broke my project's Travis-CI builds

### ISSUE THREAD

**Issue by akutz** [Masterminds/glide#113]
See the cancelled build at https://travis-ci.org/emccode/rexray/builds/86485654. Or any of the recent PR builds. I was going crazy trying to figure out what was up, but that's when I realized I pull Glide ahead of each install and once I realized Glide was timing out I checked your commit history. It looks like you guys merged a major new feature recently. I'm going to go out on a limb and say that's why. Check out my version of `glide up` locally:

```
[0]akutz@pax:rexray$ glide up
[INFO] Fetching updates for github.com/spf13/pflag.
[INFO] Fetching updates for github.com/spf13/cobra.
[INFO] Fetching updates for github.com/goamz/goamz.
[INFO] Fetching updates for github.com/emccode/goscaleio.
[INFO] Fetching updates for github.com/emccode/goxtremio.
[INFO] Fetching updates for github.com/akutz/golf.
[INFO] Fetching updates for github.com/spf13/viper.
[INFO] Setting version for github.com/spf13/pflag.
[INFO] Setting version for github.com/spf13/cobra.
[INFO] Setting version for github.com/goamz/goamz.
[INFO] Setting version for github.com/emccode/goscaleio.
[INFO] Setting version for github.com/emccode/goxtremio.
[INFO] Setting version for github.com/akutz/golf.
[INFO] Setting version for github.com/spf13/viper.
[INFO] Checking dependencies for updates. Godeps: false, GPM: false, gb: false
[INFO] Inspecting /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor.
[INFO] Looking in /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor/github.com/spf13/pflag for a glide.yaml file.
[INFO] Package github.com/spf13/pflag manages its own dependencies.
[INFO] Looking in /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra for a glide.yaml file.
[INFO] Package github.com/spf13/cobra manages its own dependencies.
[INFO] Looking in /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor/github.com/goamz/goamz for a glide.yaml file.
[INFO] Package github.com/goamz/goamz manages its own dependencies.
[INFO] Looking in /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor/github.com/emccode/goscaleio for a glide.yaml file.
[INFO] Package github.com/emccode/goscaleio manages its own dependencies.
[INFO] Looking in /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor/github.com/emccode/goxtremio for a glide.yaml file.
[INFO] Package github.com/emccode/goxtremio manages its own dependencies.
[INFO] Looking in /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor/github.com/akutz/golf for a glide.yaml file.
[INFO] Package github.com/akutz/golf manages its own dependencies.
[INFO] Looking in /Users/akutz/Projects/go/src/github.com/emccode/rexray/vendor/github.com/spf13/viper for a glide.yaml file.
[INFO] Package github.com/spf13/viper manages its own dependencies.
[0]akutz@pax:rexray$
```

On Travis it looks like this:

```
  ...downloading go dependencies...[INFO] Fetching updates for github.com/spf13/cobra.
[INFO] Fetching updates for github.com/goamz/goamz.
[INFO] Fetching updates for github.com/emccode/goscaleio.
[INFO] Fetching updates for github.com/emccode/goxtremio.
[INFO] Fetching updates for github.com/akutz/golf.
[INFO] Fetching updates for github.com/spf13/viper.
[INFO] Fetching updates for github.com/spf13/pflag.
[INFO] Setting version for github.com/spf13/cobra.
[INFO] Setting version for github.com/goamz/goamz.
[INFO] Setting version for github.com/emccode/goscaleio.
[INFO] Setting version for github.com/emccode/goxtremio.
[INFO] Setting version for github.com/akutz/golf.
[INFO] Setting version for github.com/spf13/viper.
[INFO] Setting version for github.com/spf13/pflag.
[INFO] Scanning github.com/spf13/cobra for dependencies.
[INFO] Scanning github.com/cpuguy83/go-md2man for dependencies.
[INFO] Fetching updates for github.com/cpuguy83/go-md2man.
[INFO] Fetching updates for github.com/inconshreveable/mousetrap.
[INFO] Scanning github.com/russross/blackfriday for dependencies.
[INFO] Fetching updates for github.com/russross/blackfriday.
[INFO] Scanning github.com/shurcooL/sanitized_anchor_name for dependencies.
[INFO] Scanning github.com/inconshreveable/mousetrap for dependencies.
[INFO] Scanning github.com/goamz/goamz for dependencies.
[INFO] Scanning github.com/emccode/goscaleio for dependencies.
[INFO] Fetching updates for github.com/shurcooL/sanitized_anchor_name.
[INFO] Scanning github.com/Sirupsen/logrus for dependencies.
[INFO] Scanning github.com/emccode/goxtremio for dependencies.
[INFO] Scanning github.com/akutz/golf for dependencies.
[INFO] Scanning github.com/spf13/viper for dependencies.
[INFO] Fetching updates for github.com/Sirupsen/logrus.
[INFO] Scanning github.com/BurntSushi/toml for dependencies.
Done: Job Cancelled
```

That bit took over 5 minutes. I finally cancelled it. Whatever y'all are doing is too slow.

Thoughts? Am I nuts?

**Comment by akutz** [comment]
I'm enabling the `--no-recursive` switch to see if that helps.

**Comment by akutz** [comment]
That seemed to do the trick! https://travis-ci.org/emccode/rexray/builds/86488607

**Comment by mattfarina** [comment]
I've seen this. there is something going on here.

**Comment by akutz** [comment]
Hi @mattfarina,

Well, it wasn't good, that's for sure. It broke prod builds since I use `go get` to get glide. I will switch that to a static version in the future for sure. Thanks for looking into it!

**Comment by mattfarina** [comment]
@akutz Normally a change this big wouldn't land until a bug like this is worked out. I didn't notice it until after the merge and what's happening is it's taking a long time. This needs to be fixed soon. If @technosophos doesn't poke at it first I'm going to look at it tomorrow.

**Comment by akutz** [comment]
Hi @mattfarina,

Well, yeah, I mean obviously :) Same here with my software. We all get bit sometimes. That's why they're called bugs :) No biggie in the long run -- it was just a pain to figure out since I was running silent on Travis (no output) and locally I hadn't updated Glide. So it was an hour or so before I realized what was happening (after I showed the output on Travis).

**Comment by technosophos** [comment]
Here are the new changes that are making an impact:

- Glide is now recursive by default (probably good)
- Glide flattens dependencies to the top level directory (definitely good)
- Glide now inspects all source code and tries to pull in anything it doesn't have (probably the source of slowness).

Let me disable just that last part and see if that makes a difference.

**Comment by technosophos** [comment]
Here are my results:

Glide with source code inspection:

```
time glide -y random.yaml up
[INFO] Fetching updates for golang.org/x/net.
[INFO] Fetching updates for github.com/codegangsta/negroni.
[INFO] Fetching updates for github.com/gorilla/mux.
[INFO] Fetching updates for github.com/boltdb/bolt.
...
glide -y random.yaml up  2.57s user 1.64s system 6% cpu 1:04.00 total
```

Resetting the environment and disabling scanning, we get:

```
time glide -y random.yaml up
[INFO] Fetching updates for golang.org/x/net.
[INFO] Fetching updates for github.com/gorilla/context.
[INFO] Fetching updates for github.com/PuerkitoBio/goquery.
[INFO] Fetching updates for github.com/GeertJohan/go.rice.
...
[INFO] Project relies on 11 dependencies.
glide -y random.yaml up  1.90s user 1.07s system 10% cpu 28.117 total
```

That's a pretty substantial difference, especially for a small project like this. Note, however, that the first one located three packages that were not explicitly declared by Godeps, GPM, gb, or Glide.

I started to test on Kubernetes, but it takes a _really_ long time.

If you don't mind testing, @akutz, I'd like to hear whether disabling the source code scanning helped yours, too. I'm checking this into master right now.

**Comment by akutz** [comment]
Hi @technosophos,

That appears to have addressed the issue. It was night and day. 

FWIW, I disable recursive by default because I only "lock" my dependencies prior to a release. I guess it comes from working with Maven for so long.

**Comment by mattfarina** [comment]
@technosophos I ran `time go run glide.go --debug up` on the glide codebase before and with 40a9a6b. Before the commit it took 3 minutes 9.06 seconds. With that commit it took 9.41 seconds. With the scanning it's 20x as long on glide which isn't a large codebase.

This may be better behind a flag.

**Comment by technosophos** [comment]
@akutz I added a feature you might find useful. If you do a `glide up -f myfile.yaml` it will do an update and then generate a glide.yaml with all of the discovered dependencies listed. It's like doing a guess followed by a get, except the logic is better because it is aware of Godep, GPM, and gb files and will pin accordingly.

'Course it's probably too late for your present use case... but hopefully it will come in handy in the future.

**Comment by akutz** [comment]
Hi @technosophos,

That sounds cool! Yeah, when we locked dependencies prior to the last release I did a `glide guess` followed by a `glide pin` to generate a file that was relevant for that release. One thing was was confusing is why `glide pin` wasn't working at first. It took me far too long to realize that I actually had to already have glide manage a dependency before it could pin it (hence the `glide guess`).

**Comment by technosophos** [comment]
@akutz last night I started working on #85 , which will change the way pinning works -- hopefully for the better. If you feel like weighing in on the design, you can check that thread and scroll down to the really big post about 3/4 of the way through. (I know there must be some way to link directly to a comment, but I can't figure it out).

I think I totally miscalculated how popular `pin` would be, and @mattfarina and I are trying to make it a better experience for people who rely on it.

Finally, as far as this issue goes, I'm going to add a flag (`--scan-source` or something) to enable source code scanning, and then re-commit. I'll consider that to be the last step of this ticket.

Thanks, BTW, for running on master. ;-) Would have been bad to go to production with this before discovering how poorly it performs.

**Comment by mattfarina** [comment]
We've fixed the system that scans unmanaged code so it is quite fast now. Used kubernetes as a test case due to its size. So, I'm closing this.

**Comment by shtripat** [comment]
@mattfarina Even I started facing this issue today.
if I do "go get github.com/Masterminds/glide" next time, would it solve the issue?

**Comment by mattfarina** [comment]
@shtripat you can get from the tip of master or wait for the 0.8 release tomorrow.

**Comment by akutz** [comment]
I've been using the master branch for all my builds since I set them up on Travis and aside from this issue (to which the authors responded promptly) and one other, it's all been smooth sailing. Thanks all!

**Comment by shtripat** [comment]
Thanks Matt!!

On 10 Dec 2015 00:10, "Matt Farina" <notifications@github.com> wrote:
>
> @shtripat you can get from the tip of master or wait for the 0.8 release
tomorrow.
