### ISSUE TITLE
Failed to get speter.net/go/exp/math/dec/inf

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#117]
For some reason, this particular package doesn't seem to work:

```
$ glide get speter.net/go/exp/math/dec/inf
[INFO] Preparing to install 1 package.
[ERROR] Could not construct repo for "speter.net/go/exp/math/dec/inf": Cannot detect VCS
Oops! Cannot detect VCS
```

I haven't really looked into it at all.

**Comment by mattfarina** [comment]
@technosophos This was an issue in `github.com/Masterminds/vcs`. Version 1.1.3 (released on Wednesday) fixed that issue. Can you update, rebuild, and try again?

**Comment by technosophos** [comment]
Ah, that makes sense. We'll switch our Travis to build from master.
