### ISSUE TITLE
imports paths. Go build complains when importing from vendor dir

### ISSUE THREAD

**Issue by gedw99** [Masterminds/glide#131]
i use atom and glide 0.7, and it is adding the imports like this:
"bitbucket.org/gedw99/berlininfusions/server/vendor/github.com/jinzhu/configor"

rather than:
"github.com/jinzhu/configor"

So when i do a go build it complains with:
```
imports bitbucket.org/gedw99/berlininfusions/server/vendor/github.com/jinzhu/configor: must be imported as github.com/jinzhu/configor

```

Can anyone advice me ?

**Comment by gedw99** [comment]
also this might help.
When i do glide list, it says that github.com/jinzhu/configor  is in the gopath and NOT in the vendor.
??


```
gedw99-MacBook-Pro:server apple$ glide list
bitbucket.org/gedw99/berlininfusions/server/config (Location: gopath)
bitbucket.org/gedw99/berlininfusions/server/vendor/github.com/jinzhu/configor (Location: gopath)
github.com/gorilla/context (Location: vendored)
github.com/gorilla/mux (Location: vendored)
github.com/jtolds/gls (Location: gopath)
github.com/smartystreets/assertions (Location: gopath)
github.com/smartystreets/assertions/internal/oglematchers (Location: gopath)
github.com/smartystreets/goconvey/convey (Location: vendored)
github.com/smartystreets/goconvey/convey/gotest (Location: vendored)
github.com/smartystreets/goconvey/convey/reporting (Location: vendored)
gopkg.in/yaml.v2 (Location: gopath)
```

**Comment by gedw99** [comment]
i changed over to godeps. 
i tried glide for about 2 weeks and was often getting hit with problems.

With godeps, i did what it said and in 10 minutes had everything working how it should. I turned off the Vendoring flag in the paths also as godeps wants. It found all my dependencies, rewrote the paths, made the json file, and now in bitbucket i have everything to be able to reliably do a build form nothing on the exact same dependencies.

i am not writing this to be critical, but to explain, in the hope that it helps.
i feel like glide is really nice but, at least for me, its still too green and unstable for now for day to day needs.

**Comment by mattfarina** [comment]
@gedw99 did you have the GO15VENDOREXPERIMENT turned on? That needs to be enabled for Glide (and will be on by default in Go 1.6).

**Comment by gedw99** [comment]
yes i did, but did not help.  Seriously might as well just have a seperate go path for each project i work.  Brute force encapsulation..
