### ISSUE TITLE
Steps to build from source seems to be incomplete

### ISSUE THREAD

**Issue by hyPiRion** [Masterminds/glide#132]
From the README.md:

> To build from source you can:
> * Clone this repository and change directory into it
> * Run `make bootstrap`
>
> This will leave you with `./glide`, which you can put in your `$PATH` if you'd like. (You can also take a look > at `make install` to install for you.)

When I ran the following steps:

```shell
git clone https://github.com/Masterminds/glide.git
cd glide
make bootstrap
```

I ended up with no `./glide` file.

Looking at the makefile, I assumed that `make` or `make build` would work. However, both fails with this output:

```
go build -o glide -ldflags "-X main.version=0.7.0" glide.go
glide.go:42:2: cannot find package "github.com/Masterminds/cookoo" in any of:
	/home/jeannikl/code/.go1.5/src/github.com/Masterminds/cookoo (from $GOROOT)
	/home/jeannikl/code/golang/src/github.com/Masterminds/cookoo (from $GOPATH)
glide.go:40:2: cannot find package "github.com/Masterminds/glide/cmd" in any of:
	/home/jeannikl/code/.go1.5/src/github.com/Masterminds/glide/cmd (from $GOROOT)
	/home/jeannikl/code/golang/src/github.com/Masterminds/glide/cmd (from $GOPATH)
glide.go:43:2: cannot find package "github.com/codegangsta/cli" in any of:
	/home/jeannikl/code/.go1.5/src/github.com/codegangsta/cli (from $GOROOT)
	/home/jeannikl/code/golang/src/github.com/codegangsta/cli (from $GOPATH)
Makefile:5: recipe for target 'build' failed
make: *** [build] Error 1
```

This happens both with and without GO15VENDOREXPERIMENT set.

I am running `go version go1.5 linux/amd64`.

Not sure if this is an error with my setup or an error with the Readme/Makefile, but help would be appreciated either way.

**Comment by mattfarina** [comment]
You're right that this is a documentation bug. `make bootstrap` retrieves dependencies to the `vendor/` folder (for the vendor experiment) and `make build` will create the Go binary. `make install` will build and put the glide app in `/usr/local/bin`.

I'm happy to update the README but it might be a day or two. Pull requests are always welcome.

**Comment by hyPiRion** [comment]
Right, that's what I thought – thanks for verifying that.

I'm still somewhat puzzled that `make build` did not work as intended on my machine though. Even if I do `export GO15VENDOREXPERIMENT=1`, I end up with the error message I posted in the description, as if the vendor directory is ignored.

**Comment by mattfarina** [comment]
Did you perform a `make bootstrap` before a `make build`?

**Comment by hyPiRion** [comment]
I did, but I did not place the glide directory on the $GOPATH, which was the issue I had. I'll send a pull request with improved build steps.
