### ISSUE TITLE
No home directory set to create

### ISSUE THREAD

**Issue by kyteague** [Masterminds/glide#135]
I get the error "No home directory set to create" when running "glide install" on my droplet on Digital Ocean.

glide version 0.7.0
OS is Ubuntu 14.04.

**Comment by kyteague** [comment]
Downgrading to 0.6.1 fixes the issue.

**Comment by technosophos** [comment]
This appears to be related to caching. @mattfarina is there a way to disable that?

**Comment by mattfarina** [comment]
The issue is it assumes there's always a home path. This happens when the `os` package can't detect the home directory or "" was passed in as the home directory.

In the short term you could set the environment variable `GLIDE_HOME` to the users home directory.

I'll release a fix in the next few days to gracefully handle no home directory.

**Comment by technosophos** [comment]
So doing an `export HOME=. glide up` would be a quick work-around?

On Sun, Nov 8, 2015 at 8:24 AM, Matt Farina <notifications@github.com>
wrote:

> The issue is it assumes there's always a home path. This happens when the
> os package can't detect the home directory or "" was passed in as the
> home directory.
>
> In the short term you could set the environment variable GLIDE_HOME to
> the users home directory.
>
> I'll release a fix in the next few days to gracefully handle no home
> directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Masterminds/glide/issues/135#issuecomment-154833468>.
>



-- 
http://technosophos.com
https://github.com/Masterminds

**Comment by mattfarina** [comment]
@technosophos If you do that it will put a `.glide` directory in the current directory but otherwise it should work.
