### ISSUE TITLE
github.com/spf13/viper dependency fails

### ISSUE THREAD

**Issue by dopgm** [Masterminds/glide#142]
Hi,

When adding - package: github.com/spf13/viper, Glide throws "cannot find package "gopkg.in/fsnotify.v1"m
where fsnotify is a dependency of viper ("import").
When trying to get viper explicitly via glide get github.com/spf13/viper, Glide reports
[INFO] Package github.com/spf13/viper manages its own dependencies
[INFO] Project relies on 12 dependencies.

but nothing else.

Please advise on the correct steps how to take care of its dependencies (believe this is incorrect if i'll be adding all failing deps manually into glide.yaml)

Thanks!

**Comment by technosophos** [comment]
We have temporarily disabled the automatic recursive dependency resolution on `glide get` and `glide up` in Glide 0.7 while we try to figure out how to speed it up. It was taking way too long.

In the meantime, you can use `glide guess` or `glide list` to do the dependency resolution for you. `glide guess` generates a glide.yaml file that you can use. `glide list` will generate a list of dependencies.

We're hoping to have the automatic dependency resolution enabled again on 0.8.

**Comment by dopgm** [comment]
Hi @technosophos , 
thank you!
