### ISSUE TITLE
Your last commit (ae478dcfd64a5cfe1) makes glide significantly slower

### ISSUE THREAD

**Issue by allan-simon** [Masterminds/glide#145]
for small sized project it takes a dozen of minutes to run :(

**Comment by technosophos** [comment]
How many dependencies? I am actively working on that code to try to speed it up. Anything you can provide to help me understand where it's slow would be great.

If we can't get it significantly faster, we will probably pull it back out before the 0.8 release.

**Comment by mattfarina** [comment]
@allan-simon thanks for pointing this out.

@technosophos A couple things...

* I created a `feat/code-scanning` branch for this work. We can have hundreds of clones per day (I'm guessing CI/CD) off the tip of master. So, I wanted to get the slowness out of the way so we can work it out.
* It looks like code scanning is running on Go core packages (those in the GOROOT). For example, when I tried it on Glide it hung on the `io` package. Given the [graph of packages used by `io`](https://godoc.org/io?import-graph) I was a bit surprised.

![io_graph_-_godoc](https://cloud.githubusercontent.com/assets/62991/11309566/96339786-8f92-11e5-82ef-85fb8659dfb3.png)

* I created #146 to handle code scanning as a feature and linked in other issues I knew about.

Going to close this unless there is continued slowness.

**Comment by allan-simon** [comment]
@technosophos , i'm going to ask my colleagues to take part of this ticket to give you the number and type of dependencies we have. but with an initial glide.yaml of maybe 5 directory dependencies, we finished with a huge output of scanning

**Comment by technosophos** [comment]
Thank you. I did leave the debug logging on when I shouldn't have. @mattfarina found some of the leaks, so I'm going to rework the logic on a branch and then re-test.

Thank you very much.
