### ISSUE TITLE
"Guess" dependencies on an existing codebase

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#15]
Incorporate package scanning as @gsalgado did in #6.

The idea is to have glide scan existing code and derive a list of dependencies from it.

At base, it should work like this:

```
$ glide guess
# Scans "." and all subdirectories that don't begin with `_`, and then generates a list of dependencies
$ glide guess some/dir
# Scans `some/dir` and gathers a list of dependencies. Useful for running on packages in _vendor.
```

My guess is that this functionality could get very complex very quickly, but at least building a solid starting point would be useful to many adopting glide to their existing projects.

**Comment by azylman** [comment]
Just to clarify: what's the current status of this? Does `glide pin` make a `glide.yaml` file with all of the currently-used dependencies?

**Comment by mattfarina** [comment]
Yes. `glide pin` will will create a `glide.yaml` file with the currently used dependencies. Just tested with 0.5.

**Comment by azylman** [comment]
Awesome! Could we get this documented in the README, as well?

**Comment by mattfarina** [comment]
I updated the readme in ffc4d25e7e58149dc33653de854cf5c64989ec8b

Going back to the other things documented here:
> glide init - create initial file {aks user for package name, ask about detecting packages, runtime}
> glide shrinkwrap - create/update godeps file basede on current enviroment (https://www.npmjs.org/doc/cli/npm-shrinkwrap.html)
> glide run {named script} - yaml file would contain runnable scripts (https://www.npmjs.org/doc/cli/npm-run-script.html)
> glide install - install dependencies based on godeps, if file is not present use go get, install runtime..(https://github.com/pwoolcoc/goenv)

There is already a command to create the initial file. At install time there's an `--import` flag to work with Godeps and GPM. `glide pin` locks down a version similar to shrinkwrapping.

That leaves the suggestion of a `glide run` command. I've added #59 to address that discussion.

I think everything else here is handed so I'm closing the issue. If there's still something outstanding please open a new issue or re-open this one.
