### ISSUE TITLE
subpackages and glide up/get don't get along well

### ISSUE THREAD

**Issue by colemickens** [Masterminds/glide#151]
I have used glide to vendor github.com/Azure/azure-sdk-for-go. The top level of the repo is not a package, but it contains such things as "arm/network" and "arm/resource" as packages.

Unfortunately, once the repo has been added to my glide file, I can't use `glide up` to update the packages to the latest. It just doesn't do anything. It says that azure-sdk-for-go is already in glide.yaml and then says it's "setting version" to the same version that was already in the file. (even though a newer version exists both in github and in my local $GOPATH).

I manually updated glide.yaml so that I could move forward. I then realized I wanted another package in azure-sdk-for-go, so I did `glide get github.com/Azure/azure-sdk-for-go/arm/network` expecting it to be added as a subpackage in glide.yaml.

It wasn't added as a subpackage either, so I've also manually done that.

Am I using `glide` incorrectly or are there just some gaps around packages/subpackages?

**Comment by mattfarina** [comment]
@colemickens what version of glide are you using (`glide --version`) and can you share what you're `glide.yaml` file looks like? Sub-packages should work just fine.

**Comment by colemickens** [comment]
This should help illuminate things hopefully:

```
$ glide --version

glide version dev

$ cat glide.yaml

package: azkube-deploy
import:
- package: github.com/Azure/azure-sdk-for-go
  version: 84843207ea0c77c8c8aecbe2e16ac77caa8ce9cc
  subpackages:
  - /arm/resources
- package: github.com/cloudflare/cfssl
  version: 755f4128c7c69bad69117e44ffa028c1847a0608
  subpackages:
  - /crypto
- package: github.com/spf13/cobra
  version: 1c44ec8d3f1552cac48999f9306da23c4d8a288b

$ glide get github.com/Azure/azure-sdk-for-go/arm/network

[INFO] Preparing to install 1 package.
[WARN] Package "github.com/Azure/azure-sdk-for-go" is already in glide.yaml. Skipping
[INFO] Package github.com/Azure/azure-sdk-for-go/arm/network manages its own dependencies
[INFO] Setting version for github.com/Azure/azure-sdk-for-go to 84843207ea0c77c8c8aecbe2e16ac77caa8ce9cc.
[INFO] Setting version for github.com/cloudflare/cfssl to 755f4128c7c69bad69117e44ffa028c1847a0608.
[INFO] Setting version for github.com/spf13/cobra to 1c44ec8d3f1552cac48999f9306da23c4d8a288b.
[INFO] Project relies on 3 dependencies.


$ cat glide.yaml

package: azkube-deploy
import:
- package: github.com/Azure/azure-sdk-for-go
  version: 84843207ea0c77c8c8aecbe2e16ac77caa8ce9cc
  subpackages:
  - /arm/resources
- package: github.com/cloudflare/cfssl
  version: 755f4128c7c69bad69117e44ffa028c1847a0608
  subpackages:
  - /crypto
- package: github.com/spf13/cobra
  version: 1c44ec8d3f1552cac48999f9306da23c4d8a288b
```

Similarly, as originally mentioned, I can't get `glide up [anything]` to update the version ref for `azure-sdk-for-go`. I've tried the top level repo, specific packages, nothing seems to do what I'd expect.

**Comment by technosophos** [comment]
Remove the `version` field and run a `glide up`. Does that fix it?

As you have things configured above, you are "pinned" to a particular commit. `glide up` respects your version pinning and will not advance you to a newer version.

We're making a big change to this, though.

In the past, we've recommended people use the `glide pin` command to manage this stuff, but in Glide 0.8 (coming hopefully later this week) we will change things. We're moving to the model where Glide generates a lock file. That file will lock your dependencies until you run `glide update`, then it will update them. Basically, I think that's the workflow you're already after.

So in the future (Glide 0.8 and on), you will use `version` to specify fuzzy version constraints (e.g. `>2.3` or `~1.4`), and the exact version pinning will be tracked in the `glide.lock` file.

Sorry for the confusion on that. We're working on making that part of the experience better! And if you have any feedback on how you'd expect things to work, we're all ears.

**Comment by colemickens** [comment]
I think that sounds like what I'm looking for. I'll be sure to give it a shot whenever the new version is out. If you want, you can close this, otherwise I'll close it I'll try out 0.8 on Friday or next week and update this accordingly. Thanks!

**Comment by colemickens** [comment]
This has been behaving as I expected since Glide 0.8 was out. Closing.
