### ISSUE TITLE
 Does devimport do anything?

### ISSUE THREAD

**Issue by pib** [Masterminds/glide#152]
I notice that glide-generated glide.yaml files include a devimport section, but putting packages into this section seems to result in nothing happening.

A quick look through the source seems to reveal that while the setting exists in the config, it isn't actually used anywhere in the code.

What's the intended use-case for this? I had assumed it was a place to put test and development dependencies that aren't required when building or including a package as a dependency. Are there plans to add a command-line flag to request installing devimports packages?

**Comment by technosophos** [comment]
You are right in assuming that. We just haven't gotten to implementing it yet.

My initial plan was to allow a `--dev` or `--with-dev` flag that would install dev imports, too. But we decided to hold off implementing it until other parts of the system were more stable. (Primarily the lock file logic that we're finally getting into version 0.8)

**Comment by pib** [comment]
Ok, just wanted to make sure I wasn't somehow missing something :D

I guess I'll just set my testing libs as regular dependencies until then.

Thanks!

**Comment by mattfarina** [comment]
#320 has been added to track resolving test imports to devImports

**Comment by mattfarina** [comment]
Test imports are being worked on in PR #461. Reviews appreciated.

**Comment by mattfarina** [comment]
Fixed. Tip of master now handles test imports.
