### ISSUE TITLE
Copy from GOPATH interacts poorly with flatten!

### ISSUE THREAD

**Issue by ax-nathan** [Masterminds/glide#155]
Took me quite some time to figure out why "flatten by default" wasn't (apparently) working!

**Scenario**
- Packages A & B both exist in GOPATH.
- Packages A & B both use glide.
- Packages A & B both vendor package C in `glide.yaml`.
- Package A vendors package B.
- Package B DOES NOT have `vendor/` in VCS.
- Package B DOES have `vendor/` on disk in GOPATH.

**Result**
- `glide up` in Package A (with flatten enabled) *copies* Package B from GOPATH.
- The copy of Package B includes the `vendor/` directory from disk.
- The resulting build includes `A/vendor/C` *and* `A/vendor/B/vendor/C`.
- Bad Things(tm)

**Proposal**
- `--skip-gopath` should default to `true`, or
- "flatten by default" becomes aware of `vendor/` directories copied from GOPATH, and prevents the copying of packages which should be flattened.

**Comment by mattfarina** [comment]
I've been having issues with the gopath copying myself. we need to do something about that.

I'm considering:
* opt-in to gopath copying.
* making sure the gopath version isn't dirty. But, this won't find anything being ignored.
* trying to introspect what's ignored or not along with dirtyness to figure out what to copy or skip. This would be complex.

Caching and reuse are hard.

**Comment by ax-nathan** [comment]
I'd vote for "opt-in to go path copying" as a quick, safe fix. Seems like the current method is an overly aggressive performance optimization, but results in "surprising" behavior for the development use case. At a minimum, perhaps the README needs a "Gotchas" section where things like this are called out?

**Comment by mattfarina** [comment]
8615f59981536a4f8a143e151f34f62208fb2294 made the copying from the GOPATH opt-in. This will be in the next release.
