### ISSUE TITLE
Glide says glide.yaml is missing although it was just created with glide create [Windows]

### ISSUE THREAD

**Issue by rubenhazelaar** [Masterminds/glide#161]
I have the following problem (on Windows 8):

I'm in my project folder:  `$GOPATH/src/ruben/project` 

In this folder I just ran: `glide create` which succesfully created glide.yaml

Then I run `glide get github.com/some/project`, however glide says my glide.yaml file is missing.

Am I just overlooking something or is there something wrong?

BTW I'm running 1.5.2 Go with GO15VENDOREXPERIMENT=1. I have located the glide executable in C:\Go\bin

**Comment by mattfarina** [comment]
@rubenhazelaar any chance you can provide the exact error message text? That would help me find where the issue is happening.

**Comment by rubenhazelaar** [comment]
Ofcourse:

    Oops! glide.yaml is missing from C:\Path\to\project

Above path corresponds to: `$GOPATH/src/github.com/ruben/project`. 

I have also tried running glide get with as Administrator, however unfortunatly it's the same.

**Comment by mattfarina** [comment]
@rubenhazelaar I just downloaded the 0.8.0 release from the [releases page](https://github.com/Masterminds/glide/releases) and tested on Windows. I had no issues. I'm not yet able to reproduce the problem.

1. What version of Glide are you using. `glide --version` will provide that.
2. Where did you get Glide from? Did you install a binary? Did you use `go get` to retrieve it?
3. Can you open and edit the `glide.yaml` by hand?

I'd like to be able to reproduce this problem. So far I've not been able to.

**Comment by rubenhazelaar** [comment]
I'm also using 0.8.0. I downloaded the binary from the releases page, so no
go get performed (should I have?). Glide.yaml is in the folder and I can
open it by hand and edit it. Edited or unedited, it makes no difference.
Strange..., could it be the location of the executable? Stuck the binary I
downloaded in C:/Go/bin.

**Comment by rubenhazelaar** [comment]
I discovered that when I run glide create & glide get directly in my $GOPATH folder, the dependencies are downloaded correctly. Of course this is not as intended with glide. It should be in $GOPATH/src/some/project.

**Comment by mattfarina** [comment]
Ah, I have an idea what it might be.

Glide supports the `go` tool. The `go` tool requires that all code be within the `GOPATH`. So, your project needs to be in the `GOPATH` (e.g., `GOPATH/src/foo/bar`). Glide will put code in the `vendor/` folder in the project (e.g., `GOPATH/src/foo/bar/vendor/`) and the `glide.yaml` file should be at  `GOPATH/src/foo/bar/glide.yaml`.

The `go` tool does not support project based structures. It's heavily tied to the `GOPATH` which is a product of how Google internally manages code.

In your initial go was your code inside the `GOPATH/src`? If not that would have been the problem.

If you want a project based build tool you'd need to replace the `go` tool with something like [gb](http://getgb.io).

Does this help?

**Comment by rubenhazelaar** [comment]
Thanks for the tip on gb, looks good!

It could be that my main code was originally in GOPATH/src (don't
remember), however does the go tool really remember this? If so, it could
be the problem. However I don't understand why go would remember this
although the structure has been changed for a long time.

2015-12-12 16:01 GMT-03:00 Matt Farina <notifications@github.com>:

**Comment by rubenhazelaar** [comment]
Ok, I have tested the following:

Reset my `GOPATH

**Comment by mattfarina** [comment]
@rubenhazelaar thanks for all the details. I'm glad you were able to get a working version.

You've given enough details I can try to setup a fresh windows 8 system and try to reproduce this next week. Thanks.

**Comment by mattfarina** [comment]
@rubenhazelaar one more question, which of the windows binary builds were you using?

**Comment by rubenhazelaar** [comment]
Great, hope it works out and your able to reproduce the case :). If you
need anything else please let me know.

I used the amd64 binary for Windows.

**Comment by mattfarina** [comment]
I've been attempting to re-create this situation and have failed to reproduce the same problem. I've setup Windows 8 and the type of setup described here. Does anyone have more detail?

**Comment by rubenhazelaar** [comment]
To give some closure to this: I downloaded the new 0.8.3 version from the releases page and it works as expected :)
