### ISSUE TITLE
`glide [create | install]` in root is looking at many stdlib packages

### ISSUE THREAD

**Issue by justinfx** [Masterminds/glide#163]
(glide v0.8.0)

I decided to give glide a try for the first time, and I am testing it out in one of my own projects ([gofileseq](https://github.com/justinfx/gofileseq)). This project is structured as:

* a library in the root of the project
* 1 or more library sub-packages
* 1 or more main applications within cmd/

The first thing I tried to do was to run `glide create` in the root of the project. This resulted in glide scanning a bunch of stdlib packages...

```bash
(gofileseq ) $ glide create
[INFO] Generating a YAML configuration file and guessing the dependencies
[INFO] Attempting to import from other package managers (use --skip-import to skip)
[INFO] Found reference to bufio
[INFO] Found reference to bytes
[INFO] Found reference to errors
[INFO] Found reference to fmt
[INFO] Found reference to io
[INFO] Adding sub-package ioutil to io
[INFO] Found reference to math
[INFO] Found reference to os
[INFO] Adding sub-package user to os
[INFO] Found reference to path/filepath
[INFO] Found reference to regexp
[INFO] Found reference to runtime
[INFO] Found reference to sort
[INFO] Found reference to strconv
[INFO] Found reference to strings
[INFO] Found reference to sync
[INFO] Found reference to syscall
[INFO] Found reference to text/tabwriter
[INFO] Found reference to text/template
[INFO] Found reference to time 
```

... and putting them into the `glide.yaml`:

```yaml
package: github.com/justinfx/gofileseq
import:
- package: bufio
- package: bytes
- package: errors
- package: fmt
- package: io
  subpackages:
  - ioutil
- package: math
- package: os
  subpackages:
  - user
- package: path/filepath
- package: regexp
- package: runtime
- package: sort
- package: strconv
- package: strings
- package: sync
- package: syscall
- package: text/tabwriter
- package: text/template
- package: time
```

At this point, if I did nothing else to clean up that yaml file, and if I run something like `glide list`, I get an error because the vendor directory has not yet been created by glide, and it thinks it would have installed a stdlib there:

```bash
[ERROR] Dependency /Users/justin/src/go/src/github.com/justinfx/gofileseq/vendor/bytes failed to resolve: lstat /Users/justin/src/go/src/github.com/justinfx/gofileseq/vendor/bytes: no such file or directory.
Oops! lstat /Users/justin/src/go/src/github.com/justinfx/gofileseq/vendor/bytes: no such file or directory
```

And then if I did `glide install` or `glide update`, it wants to scan through a bunch of stdlib:

```bash
[INFO] Lock file (glide.lock) does not exist. Performing update.
[INFO] Fetching updates for bufio.
[WARN] Unable to checkout bufio
[WARN] Update failed for bufio: Cannot detect VCS
[INFO] Fetching updates for bytes.
[WARN] Unable to checkout bytes
[WARN] Update failed for bytes: Cannot detect VCS
[INFO] Fetching updates for errors.
[WARN] Unable to checkout errors
[WARN] Update failed for errors: Cannot detect VCS
[INFO] Fetching updates for fmt.
...
```

Questions:

1. Am I meant to clean up the yaml, after glide, to remove all the stdlib package it discovered? 
1. Is this a project structure that does not make glide happy?
1. Really the only thing it should be managing is the external dependencies of the `cmd/seqls` application. Being that we want a flat dependency management in the root vendor, I assumed I should have a single glide configuration at the root. Am I supposed to configure the root glide yaml to manage this sub-package application, or am I meant to put a glide yaml lower down in the `cmds/`?

So far, it isn't very clear to me how to start managing this project structure via glide. Currently I have the specific `cmds/seqls` application using its own Godeps.

Thanks for the support!

**Comment by mattfarina** [comment]
Glide should not be detecting the stdlib packages. It should skip detection of those. Looking at your project I don't see something that would make it unhappy. I tried to see if I could replicate the problem and I can't.

So, let's see if we can get to the bottom of this. I have a few questions.

1. What os/version are you on?
2. Can you run `glide --version` and share that version.
3. How did you install glide? Did you use one of the binaries, fetch and compile yourself, or use something like homebrew for mac?

Thanks.

**Comment by technosophos** [comment]
Also, the values of $GOROOT and $GOPATH would help. I could see how this would happen if $GOPATH happened to point to core packages. The scanning for whether or not a package is core relies pretty heavily on what Go thinks its environment is.

**Comment by justinfx** [comment]
Thanks for the quick feedback!

I'm using the OSX homebrew-provided 0.8.0 glide install, and the following go-1.5.1 env:

```
$ go env
GOARCH="amd64"
GOBIN="/Users/justin/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/justin/src/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

`$GOROOT` is not set by me. 

If you think trying glide from tip will make a difference, I can do that. I have a really simple env, and basically just tried doing your standard `glide create` in the root of the project.

**Comment by justinfx** [comment]
Interesting. I just removed the brew 0.8.0 version, and installed glide from tip. It does not have this same problem. What could be the difference here between the brew package and tip?

**Comment by mattfarina** [comment]
@justinfx I just installed 0.8.0 from homebrew and cannot reproduce the problems on your project. I have a similar setup to yours on el capitan.

What version of OS X are you on?

**Comment by technosophos** [comment]
This is an error where the runtime is not correctly locating the GOROOT. Something about the Homebrew binary or build must be causing this. We had a similar problem a while back with a Homebrew build that favored the built-in GOROOT location instead of the one specified on $GOROOT. Do you remember that one @mattfarina ?

**Comment by mattfarina** [comment]
@technosophos I remember this one. I have an idea what's causing it now.

**Comment by justinfx** [comment]
Awesome. Thanks for the quick support!
