### ISSUE TITLE
Allow glide.yaml to declare dependencies as "development-time only"

### ISSUE THREAD

**Issue by xeger** [Masterminds/glide#168]
It's common for a package to depend on third-party code in order to run tests or perform other development work on the package itself, but not to depend on that code at runtime. The canonical example would be a library like ginkgo or omega: I may choose to write my tests using ginkgo, but if someone imports my package to use my exports in their own executable, they do _not_ need ginkgo.

Because glide honors any `glide.yaml` it finds in transitive dependencies, there is no way for me to use glide both to manage my project's development-time dependencies _and_ provide a dependency specification to others who are importing my package. Since I want others to be able to use my code, I am forced to omit development dependencies from `glide.yaml` and manage them by hand; ouch!

I'd like to add the capability to glide to mark certain dependencies as "local," i.e. not to be considered when one's package is imported into another person's project. There are many ways to achieve this, so I thought I would gather some feedback before coding anything.

Some sample ideas for supporting conditional dependencies:

- Introduce a flag such as `development: true|false` to each dependency listed in glide.yaml
- Introduce a more flexible concept such as "tagging" of dependencies, and allow callers of the`glide` CLI to provide a whitelist or blacklist of dependencies that should be considered in building the graph
- Introduce a separate file i.e. `glide-local.yaml` that glide ignores unless it lives in initial working dir.

**Comment by mattfarina** [comment]
There is a `devImports` option in the `glide.yaml` for this that doesn't actually work at the moment. It's not wired up. It's currently the next most highly requested feature so we will be implementing it in the near future.

**Comment by technosophos** [comment]
I am thinking that probably what we will do is add a `--dev` flag to the relevant commands, and that will read the `devImports` section of a Glide file as well as the regular `imports` section.

I'm wondering if we should have a separate lock file for dev dependencies.

**Comment by xeger** [comment]
Thank you; a `devImports` plus an opt-in `--dev` flag would fit the bill quite nicely. I stand ready to test -- I'd offer to help implement but it sounds like you're moving quickly and I'm not up to speed on your project yet, so I'll be a guinea pig instead.

**Comment by pspeter3** [comment]
Is there an open issue that is tracking this development?

**Comment by mattfarina** [comment]
@pspeter3 yes. See #152 and #103. We're currently cleaning up the internals of Glide which will remove some old code and make it easier for people to contribute. Once that is done this is one of the higher priority items. It will be coming soon since much of that cleanup work is done.
