### ISSUE TITLE
Bad glide.yaml

### ISSUE THREAD

**Issue by leprechau** [Masterminds/glide#169]
In the project glide.yaml the declared repository is in SSH format which breaks hosts including portions of this project that are also using glide and do not have SSH access to the cookoo project.  The repo and vcs lines should just be removed.

```
- package: github.com/Masterminds/cookoo
  version: ^1.2.0
  repo: git@github.com:Masterminds/cookoo.git
  vcs: git
```

**Comment by mattfarina** [comment]
I've been waiting for someone to comment on this. I got bit by this today when I was doing Windows testing.

**Comment by technosophos** [comment]
Is there a reason why we have the `repo` in there? I think we can safely just remove it, right?
