### ISSUE TITLE
Make Glide configurable to be of more general use

### ISSUE THREAD

**Issue by jurgen-kluft** [Masterminds/glide#177]
What about:

1. Removing the dependency on a system wide environment variable 'GOPATH' ? 
    Instead go up the hierachy until a 'glide.root' file is encountered and treat that as 'GOPATH'.
    If GOPATH is set, writing a 'glide.root' file should make Glide work with the above change.

It already seems that Glide doesn't depend on a formal Golang installation, just adding GOPATH seems to be sufficient. This will actually allow Glide to be useable for any language. I am using Glide now for C++ to pull in dependency packages and i have my own scripts to generate the project and solution files.

All in all, great work in developing this, it works great!

**Comment by mattfarina** [comment]
Thanks for the input and idea.

Most languages have their own package manager. For example Cargo for Rust, Composer for PHP, npm for JavaScript, Maven for Java, and so on. In this case we'd targeted Glide at Go and we leverage Go specific features such as scanning the codebase to find imports. That way we can get the whole tree and lock it to a version.

I'm amazed that you've been able to use Glide with C++. I don't think we can easily make it work well for Go users while decoupling it from Go (e.g., the `GOPATH`, `GOROOT`, and so on).

Someone could possibly use the projects under Masterminds and some parts of Glide to build a package manager targeted at C++.

**Comment by jurgen-kluft** [comment]
Hello Matt and thanks for the explanation.

I am aware that other languages have very good package managers, C++ however not so much. Therefor i was quite jealous of Go and Rust to so easily be able to import packages directly from BitBucket, Github or other places. 
I have integrated and tested both Glide (Go) and Cargo (Rust) to provide the service to pull in the dependency packages which saves me time to develop this myself and this works very well.

The additional scripts that i have depend on a pom like project descriptor that lists the dependencies, i then save out the glide.yaml for Glide which then installs or updates them. So i only use this part of Glide (or Cargo). Perhaps in the future i might look into integrating the C++ scanning into a fork of Glide.

Thanks
