### ISSUE TITLE
glide handling of packages with the same prefix

### ISSUE THREAD

**Issue by dmitris** [Masterminds/glide#182]
I wonder if glide has any special logic to consider imports like "package-with-dashes-one" and "package-with-dashes-two" to be really subpackages of "package-with-dashes" for any reason?

I have a test project sometld.com/dmitris/go-simple-canary-cmd
that depends on sometld.com/dmitris/go-simple-canary-lib and through that library transitively on
sometld.com/dmitris/go-simple-canary-lib-two and sometld.com/dmitris/go-simple-canary-lib-three (for testing the CI system).

When I run "glide init" and "glide up", it creates a glide.lock file with:
```
imports:
- name: sometld.com/dmitris/go-simple-canary-lib
  version: 50cfa0f24c75a099648c023a5548ea37f20e9fdc
  subpackages:
  - -two
  - -three
```

glide.yaml has only "sometld.com/dmitris/go-simple-canary-lib" even when I explicitly try to run "glide get sometld.com/dmitris/go-simple-canary-lib-two".

Initially, I had packages named like go-simple-canary-lib, go-simple-canary-lib2, and go-simple-canary-lib3 and glide did a similar thing: it put "2" and "3" as subpackages even though each one a stand-alone package with its own import path...

**Comment by mattfarina** [comment]
Glide has special logic to find the top of VCS repos. Are all of these in the same VCS repo?

One place this happens inside [GetRootFromPackage](https://github.com/Masterminds/glide/blob/8b683f9ec07fb4463a252ead1ee91b693f1c4cb9/util/util.go#L30). In here it tries a variety of methods to figure out the root repo.

The sub-packages are the suffix to the root package. You can see some of this logic at work in [NormalizeName](https://github.com/Masterminds/glide/blob/8b683f9ec07fb4463a252ead1ee91b693f1c4cb9/cmd/yaml.go#L163).

Can you share more detail about your layout? What VCS? How is it laid out? Is this private or public? Do you have a go-get redirect in place?

**Comment by dmitris** [comment]
Yes, they are all the same VCS (git).

The layout is:
go-simple-canary-cmd
go-simple-canary-lib
go-simple-canary-lib-two
go-simple-canary-lib-three

each one is part of the package name like "go.corp.company.com/dmitris/go-simple-canary-cmd" (the domain is not the real one).  The dependency chain is: cmd -> lib -> lib-two -> lib-three (toy projects to test dependency resolution by the CI system).

'go list -e -f' finds them all fine:
```
$ go list -e -f '{{join .Deps "\n"}}' ./... | xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}'
go.corp.company.com/dmitris/go-simple-canary-cmd
go.corp.company.com/dmitris/go-simple-canary-lib
go.corp.company.com/dmitris/go-simple-canary-lib-three
go.corp.company.com/dmitris/go-simple-canary-lib-two
```
and "go get" installs them correctly.


There is indeed a go-get "redirect" with the meta tags  (like for golang.org/x):
```
Fetching https://go.corp.company.com/dmitris/go-simple-canary-cmd?go-get=1
Parsing meta tags from https://go.corp.company.com/dmitris/go-simple-canary-cmd?go-get=1 (status code 200)
get "go.corp.company.com/dmitris/go-simple-canary-cmd": found meta tag main.metaImport{Prefix:"go.corp.company.com/dmitris/go-simple-canary-cmd", VCS:"git", RepoRoot:"ssh://git@git.corp.company.com/dmitris/go-simple-canary-cmd"} at https://go.corp.company.com/dmitris/go-simple-canary-cmd?go-get=1
```

Maybe it would be possible (and even simpler) to "seed" glide.yaml in 'glide init' from the output of 'go list' - at least, as an option?  Thanks a lot for looking into this.

**Comment by dmitris** [comment]
maybe I did not make it clear - go-simple-canary-cmd, go-simple-canary-lib etc. are all in their separate Git repos with distinct remote.origin.url:
```
$ git config --get remote.origin.url
git@git.corp.company.com:dmitris/go-simple-canary-cmd.git
$ cd ../go-simple-canary-lib
$ git config --get remote.origin.url
git@git.corp.company.com:dmitris/go-simple-canary-lib.git
```
etc.

**Comment by mattfarina** [comment]
@dmitris thanks for all the detail. I think we are getting somewhere. This is really helping to make progress. I think the issue is in the logic around the go-get redirects.

If a package like `go.corp.company.com/dmitris/go-simple-canary-cmd` is queried does it return one or more go-import meta tags? You can test this with curl via:

> curl "https://go.corp.company.com/dmitris/go-simple-canary-cmd?go-get=1"

Am I right to think there are more than one go-import statements?

I'm guessing the issue is how we match a [go-import to a response](https://github.com/Masterminds/glide/blob/8b683f9ec07fb4463a252ead1ee91b693f1c4cb9/util/util.go#L149).

**Comment by mattfarina** [comment]
Upon reviewing more source, I'm not sure the issue is with multiple go-import statements. But, depending on the response the problem could be there. I'd be really curios to know the response from the curl command in the previous comment.

**Comment by dmitris** [comment]
@mattfarina - I don't think there are multiple go-import statements
```
$ curl "https://go.corp.company.com/dmitris/go-simple-canary-cmd?go-get=1"
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="go-import" content="go.corp.company.com/dmitris/go-simple-canary-cmd git ssh://git@git.corp.company.com/dmitris/go-simple-canary-cmd">
  </head>
  <body>
    <p>Nothing to see here.</p>
  </body>
```

**Comment by mattfarina** [comment]
If you fix the problem manually in your `glide.yaml` file and run `glide up` does it work as expected?

I ask because I'm trying to identify if the issue is in `glide init` or `glide up`. The initialization code scans directories and packages while the update code does de-duping.

**Comment by dmitris** [comment]
I tried to put all the packages as output by "go list" in glide.yaml but when running ```glide up``` it was putting "two" and "three" as subpackages and did not pay attention to the real packages listed in glide.yaml

**Comment by dmitris** [comment]
I tried one more time - I put the following in my glide.yaml file:
```
- package: go.corp.company.com/dmitris/go-simple-canary-lib
- package: go.corp.company.com/dmitris/go-simple-canary-lib
- package: go.corp.company.com/dmitris/go-simple-canary-lib-three
- package: go.corp.company.com/dmitris/go-simple-canary-lib-two
```
and when I ran ```glide --debug up```, I got the following output:
```
$ glide --debug up
[INFO] Fetching updates for go.corp.company.com/dmitris/go-simple-canary-lib.
[DEBUG] Attempting to find current branch for ssh://git@git.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Saving default branch for ssh://git@git.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] ---> Inspecting /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor for changes (1 packages).
[DEBUG] ----> Scanning go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/Godeps/ for a Godeps.json file.
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/vendor/ for a manifest file.
[INFO] Scanning go.corp.company.com/dmitris/go-simple-canary-lib for dependencies.
[DEBUG] => Scanning go.corp.company.com/dmitris/go-simple-canary-lib-two
[DEBUG] Setting final version for 1 dependencies.
[INFO] Project relies on 1 dependencies.
[INFO] Writing glide.lock file
```

The resulting glide.lock file then was the following:
```
hash: 538fb2dd7a18fe6a3692fc67534c2154d7f70892cff8ebfaca1e04bb75918a37
updated: 2015-12-22T18:13:28.718975472+01:00
imports:
- name: go.corp.company.com/dmitris/go-simple-canary-lib
  version: 50cfa0f24c75a099648c023a5548ea37f20e9fdc
  subpackages:
  - -three
  - -two
devImports: []
```

I ran ```go get -u -v github.com/Masterminds/glide``` right before that so i'm using the latest and greatest dev version of glide.

**Comment by dmitris** [comment]
I also tried ```glide --debug get go.corp.company.com/dmitris/go-simple-canary-lib-two```, here's the output:

```
$ glide --debug get go.corp.company.com/dmitris/go-simple-canary-lib-two
[INFO] Preparing to install 1 package.
[WARN] Package "go.corp.company.com/dmitris/go-simple-canary-lib" is already in glide.yaml. Skipping
[INFO] Walking the dependency tree to calculate versions
[INFO] Fetching updates for go.corp.company.com/dmitris/go-simple-canary-lib.
[DEBUG] ---> Inspecting /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor for changes (1 packages).
[DEBUG] ----> Scanning go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/Godeps/ for a Godeps.json file.
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/vendor/ for a manifest file.
[INFO] Scanning go.corp.company.com/dmitris/go-simple-canary-lib for dependencies.
[DEBUG] => Scanning go.corp.company.com/dmitris/go-simple-canary-lib-two
[DEBUG] Setting final version for 1 dependencies.
[INFO] Project relies on 1 dependencies.
[INFO] Writing glide.lock file
```

The glide.lock file has not changed after the ```glide get``` command.

**Comment by mattfarina** [comment]
@dmitris that tells me a big more about where the problem is. Thanks.

When Glide reads a `glide.yaml` file it processes it first. That happens before the configuration gets to the logic from `glide get`. The messages you see tell me something is likely happening when the `glide.yaml` file is being loaded.

I created a branch `bug/issue-182` with some extra debug calls. Can you please fetch glide, checkout that branch, install it, and run `glide --debug up`.

I have some ideas where along the way the issues are happening and this tries to find some of that.

Sorry this is taking so long. There is an edge case bug here that's hard to find.

**Comment by dmitris** [comment]
Here's what I get with the issue-182 branch:
```
$ glide --debug init
[INFO] Generating a YAML configuration file and guessing the dependencies
[INFO] Attempting to import from other package managers (use --skip-import to skip)
[DEBUG] go-import: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[INFO] Found reference to go.corp.company.com/dmitris/go-simple-canary-lib
$ cat glide.yaml
package: go.corp.company.com/dmitris/go-simple-canary-cmd
import:
- package: go.corp.company.com/dmitris/go-simple-canary-lib
$ glide --debug update
[DEBUG] before name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] go-import: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] after name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] subpkg:
[INFO] Fetching updates for go.corp.company.com/dmitris/go-simple-canary-lib.
[DEBUG] Attempting to find current branch for ssh://git@git.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Saving default branch for ssh://git@git.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] ---> Inspecting /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor for changes (1 packages).
[DEBUG] ----> Scanning go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/Godeps/ for a Godeps.json file.
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/vendor/ for a manifest file.
[INFO] Scanning go.corp.company.com/dmitris/go-simple-canary-lib for dependencies.
[DEBUG] => Scanning go.corp.company.com/dmitris/go-simple-canary-lib-two
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Setting final version for 1 dependencies.
[INFO] Project relies on 1 dependencies.
[INFO] Writing glide.lock file
$ cat glide.lock
hash: e22bb0a0fd2d5bd3e544b1880a95c664e34e06f14f5047453e1dd760c565fb24
updated: 2015-12-22T19:07:21.303544857+01:00
imports:
- name: go.corp.company.com/dmitris/go-simple-canary-lib
  version: 50cfa0f24c75a099648c023a5548ea37f20e9fdc
devImports: []
```

**Comment by mattfarina** [comment]
@dmitris can you try it with the manually edited file you shared including

```
- package: go.corp.company.com/dmitris/go-simple-canary-lib
- package: go.corp.company.com/dmitris/go-simple-canary-lib
- package: go.corp.company.com/dmitris/go-simple-canary-lib-three
- package: go.corp.company.com/dmitris/go-simple-canary-lib-two
```

**Comment by technosophos** [comment]
I tested `cmd.NormalizeName` with the above examples, and I can't reproduce there. Looking for other normalization functions. I think there was another place where we were normalizing package names.

**Comment by dmitris** [comment]
I think the problem is in the checkRemotePackageCache function and the fact that it uses the prefix check to check for hits while returning only the prefix portion of the package:
https://github.com/Masterminds/glide/blob/master/util/util.go#L101

```
	for k := range remotePackageCache {
		if strings.HasPrefix(pkg, k) {
			return k, true
		}
	}
```
The cache contains the package like go.corp.company.com/dmitris/go-simple-canary-lib which happens to be a prefix of go.corp.company.com/dmitris/go-simple-canary-lib-two and go.corp.company.com/dmitris/go-simple-canary-lib-three, so it is the shorter version that is being returned from the cache and consequently used by the callers.

One of the debug messages I added shows:
```
[DEBUG] checkRemotePackageCache - found go.corp.company.com/dmitris/go-simple-canary-lib-three returning go.corp.company.com/dmitris/go-simple-canary-lib
```
If I modify the function to contain:
```
	for k := range remotePackageCache {
		if pkg == k {
			msg.Debug("checkRemotePackageCache - found %s returning %s", pkg, k)
			return k, true
		}
	}
```
then glide.lock contains all the expected packages:
```
hash: f8a6aa7b0f80a58d8cb2da4f0b8855c11a22537db671693ef140947fbc9e7325
updated: 2015-12-22T22:57:41.832630641+01:00
imports:
- name: go.corp.company.com/dmitris/go-simple-canary-lib
  version: 50cfa0f24c75a099648c023a5548ea37f20e9fdc
- name: go.corp.company.com/dmitris/go-simple-canary-lib-three
  version: 3fd7cce64311260b89b8be4917eda70d9b12f312
- name: go.corp.company.com/dmitris/go-simple-canary-lib-two
  version: 6b13a9d0d0cfa8892388fae1d995402681054f96
devImports: []
```

-----------------------------------------------------------------------
The output of `glide --debug up` with the manually edited glide.yaml as you suggested:
```
$ glide --debug up
[DEBUG] before name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] go-import: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] after name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] subpkg:
[DEBUG] before name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] after name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] subpkg:
[DEBUG] before name: go.corp.company.com/dmitris/go-simple-canary-lib-three
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] after name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] subpkg: -three
[DEBUG] before name: go.corp.company.com/dmitris/go-simple-canary-lib-two
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] after name: go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] subpkg: -two
[INFO] Fetching updates for go.corp.company.com/dmitris/go-simple-canary-lib.
[DEBUG] ---> Inspecting /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor for changes (1 packages).
[DEBUG] ----> Scanning go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/Godeps/ for a Godeps.json file.
[DEBUG] Looking in /Users/dmitris/go/src/go.corp.company.com/dmitris/go-simple-canary-cmd/vendor/go.corp.company.com/dmitris/go-simple-canary-lib/vendor/ for a manifest file.
[INFO] Scanning go.corp.company.com/dmitris/go-simple-canary-lib for dependencies.
[DEBUG] => Scanning go.corp.company.com/dmitris/go-simple-canary-lib-two
[DEBUG] GetRootFromPackage (getRootFromGoGet): go.corp.company.com/dmitris/go-simple-canary-lib
[DEBUG] Setting final version for 1 dependencies.
[INFO] Project relies on 1 dependencies.
[INFO] Writing glide.lock file
```

**Comment by dmitris** [comment]
sent a one-line fix in https://github.com/Masterminds/glide/pull/183

**Comment by mattfarina** [comment]
@dmitris Thanks for the pull request. My hope with caching was also to catch cases like `golang.org/x/net/context` being part of `golang.org/x/net` but there are cases this is a bad idea. Sorry about that bug.

I just pushed up b07f081 which builds on your fix to avoid some more http requests.

Please let me know how this goes.

**Comment by dmitris** [comment]
It works fine now, thanks! Closing the issue.
