### ISSUE TITLE
Prompted for auth on a public repo:

### ISSUE THREAD

**Issue by colemickens** [Masterminds/glide#184]
```
[INFO] Setting version for github.com/dustin/go-humanize to c20a8bde38c8f5ba06f6600edf473705c96829d1.
Username for 'https://github.com': ^C% 
```

this was when I tried to vendor Kubernetes.

**Comment by colemickens** [comment]
And again:

```
[INFO] Found Godeps.json file.
[INFO] Found Godeps.json file for "github.com/coreos/rkt"
[WARN] Conflict: github.com/appc/cni ref is 2a58bd9379ca33579f0cf631945b717aa4fa373d, but also asked for 5b7aa09e52da1c490ace2ec2c940fe5ef1575d27
[INFO] Keeping github.com/appc/cni 2a58bd9379ca33579f0cf631945b717aa4fa373d
[WARN] Conflict: github.com/bradfitz/http2 ref is 3e36af6d3af0e56fa3da71099f864933dea3d9fb, but also asked for f8202bc903bda493ebba4aa54922d78430c2c42f
[INFO] Keeping github.com/bradfitz/http2 3e36af6d3af0e56fa3da71099f864933dea3d9fb
[WARN] Conflict: github.com/coreos/go-iptables ref is 83dfad0f13fd7310fb3c1cb8563248d8d604b95b, but also asked for 74b0926558061d3a23824e9c18c9cf9c1b9c11f4
[INFO] Keeping github.com/coreos/go-iptables 83dfad0f13fd7310fb3c1cb8563248d8d604b95b
[WARN] Conflict: github.com/coreos/go-semver ref is d043ae190b3202550d026daf009359bb5d761672, but also asked for 6fe83ccda8fb9b7549c9ab4ba47f47858bc950aa
[INFO] Keeping github.com/coreos/go-semver d043ae190b3202550d026daf009359bb5d761672
[WARN] Conflict: github.com/coreos/go-systemd ref is b4a58d95188dd092ae20072bac14cece0e67c388, but also asked for d7b08942d0d85bfcb4694864881c4af7324784d2
[INFO] Keeping github.com/coreos/go-systemd b4a58d95188dd092ae20072bac14cece0e67c388
[WARN] Conflict: github.com/godbus/dbus ref is c7fdd8b5cd55e87b4e1f4e372cdb1db61dd6c66f, but also asked for 41608027bdce7bfa8959d653a00b954591220e67
[INFO] Keeping github.com/godbus/dbus c7fdd8b5cd55e87b4e1f4e372cdb1db61dd6c66f
[WARN] Conflict: github.com/golang/protobuf ref is 7f07925444bb51fa4cf9dfe6f7661876f8852275, but also asked for 6dfb160b2754e3b3fa583fbd0c207dfab2e836e5
[INFO] Keeping github.com/golang/protobuf 7f07925444bb51fa4cf9dfe6f7661876f8852275
[WARN] Conflict: github.com/gorilla/context ref is 215affda49addc4c8ef7e2534915df2c8c35c6cd, but also asked for 50c25fb3b2b3b3cc724e9b6ac75fb44b3bccd0da
[INFO] Keeping github.com/gorilla/context 215affda49addc4c8ef7e2534915df2c8c35c6cd
[WARN] Conflict: github.com/gorilla/mux ref is 8096f47503459bcc74d1f4c487b7e6e42e5746b5, but also asked for e444e69cbd2e2e3e0749a2f3c717cec491552bbf
[INFO] Keeping github.com/gorilla/mux 8096f47503459bcc74d1f4c487b7e6e42e5746b5
[WARN] Conflict: github.com/kr/pty ref is 05017fcccf23c823bfdea560dcc958a136e54fb7, but also asked for f7ee69f31298ecbe5d2b349c711e2547a617d398
[INFO] Keeping github.com/kr/pty 05017fcccf23c823bfdea560dcc958a136e54fb7
[WARN] Conflict: github.com/pborman/uuid ref is ca53cad383cad2479bbba7f7a1a05797ec1386e4, but also asked for cccd189d45f7ac3368a0d127efb7f4d08ae0b655
[INFO] Keeping github.com/pborman/uuid ca53cad383cad2479bbba7f7a1a05797ec1386e4
[WARN] Conflict: github.com/spf13/cobra ref is 1c44ec8d3f1552cac48999f9306da23c4d8a288b, but also asked for 66816bcd0378e248c613e3c443c020f544c28804
[INFO] Keeping github.com/spf13/cobra 1c44ec8d3f1552cac48999f9306da23c4d8a288b
[WARN] Conflict: github.com/spf13/pflag ref is 08b1a584251b5b62f458943640fc8ebd4d50aaa5, but also asked for 67cbc198fd11dab704b214c1e629a97af392c085
[INFO] Keeping github.com/spf13/pflag 08b1a584251b5b62f458943640fc8ebd4d50aaa5
[WARN] Conflict: github.com/syndtr/gocapability ref is 2c00daeb6c3b45114c80ac44119e7b8801fdd852, but also asked for 8e4cdcb3c22b40d5e330ade0b68cb2e2a3cf6f98
[INFO] Keeping github.com/syndtr/gocapability 2c00daeb6c3b45114c80ac44119e7b8801fdd852
[WARN] Conflict: github.com/vishvananda/netlink ref is 1e2e08e8a2dcdacaae3f14ac44c5cfa31361f270, but also asked for ecf47fd5739b3d2c3daf7c89c4b9715a2605c21b
[INFO] Keeping github.com/vishvananda/netlink 1e2e08e8a2dcdacaae3f14ac44c5cfa31361f270
[WARN] Conflict: golang.org/x/crypto ref is 346896d57731cb5670b36c6178fc5519f3225980, but also asked for a7ead6ddf06233883deca151dffaef2effbf498f
[INFO] Keeping golang.org/x/crypto 346896d57731cb5670b36c6178fc5519f3225980
[WARN] Conflict: golang.org/x/tools ref is 4f50f44d7a3206e9e28b984e023efce2a4a75369, but also asked for 27e692e6ec36d8f48be794f32553e1400c70dbf2
[INFO] Keeping golang.org/x/tools 4f50f44d7a3206e9e28b984e023efce2a4a75369
[WARN] Conflict: k8s.io/kubernetes ref is e310e619fc1ac4f3238bf5ebe9e7033bf5d47ee2, but also asked for 53ec66caf4e952a1384ec93b9f0cde37616e4caf
[INFO] Keeping k8s.io/kubernetes e310e619fc1ac4f3238bf5ebe9e7033bf5d47ee2
[INFO] Setting version for github.com/cznic/exp to 36265f1914ea00990ff0b73f72350edf9b1850df.
Username for 'https://github.com': 
```

**Comment by colemickens** [comment]
I've been trying for the last half hour to vendor `k8s.io/kubernetes/pkg/client/unversioned/clientcmd/api` and I keep getting the above errors or it just seems to hang, without the cpu doing anything...

**Comment by mattfarina** [comment]
@colemickens I can help with k8s. It's something I've worked with in a similar way. K8s being such a large monorepo with so many dependencies is a great way to test Glide. It's even lead to ideas on how to speed up Glide (some of which are still coming).

Within k8s there are a couple packages, in the full tree, that have moved. The GitHub case causes auth to be triggered on GitHub in case the repo is private. These are cases where a redirect isn't setup.

Try adding the following to your `glide.yaml` file:
```yaml
- package: github.com/steveeJ/gexpect
  repo: https://github.com/coreos/gexpect
- package: launchpad.net/gocheck
  repo: https://github.com/go-check/check
- package: code.google.com/p/goprotobuf
  repo: https://github.com/golang/protobuf
```

This will tell Glide to pull those packages from the `repo` location instead.

There's also an example module that references a fictitious `appengine` package. To skip that try adding the following to your `glide.yaml` file:

```yaml
ignore:
- appengine
```

I recently did the same type of thing in helm/helm#363 if you're looking for an example.

Does that help?

There are a number of us who wish the k8s client was its own git repo right now.

**Comment by colemickens** [comment]
Hi @mattfarina,

For my needs, it was easier to copy the small struct from the Kubernetes project than pay the cost of vendoring the entire repo.

It sounds that there is a bug in how glide handles redirected packages. Is there another issue to track that problem?

>There are a number of us who wish the k8s client was its own git repo right now.

Yes, I can see why. Go + third party libs is enough... add vendoring and big mono-repos and it only gets more fun...

**Comment by technosophos** [comment]
I don't think it's just when packages are redirected. I think it's when one package is manually moved to a new repo, and the old one is marked private. I seem to recall testing this with another repo and the redirect was fine.

**Comment by colemickens** [comment]
I don't really know. I do know that the very first example is neither a moved, redirected or private repository...

**Comment by colemickens** [comment]
The packages in question must be redirecting anyway, or they'd never build correctly in the first place without glide.

**Comment by mattfarina** [comment]
@colemickens can you share your `glide.yaml` file? I'm interested in the entry for `github.com/dustin/go-humanize` or the one that has something to include that. I want to try and replicate the issue.

**Comment by technosophos** [comment]
What's the status on this one?

**Comment by colemickens** [comment]
I'm not really sure. I abandoned trying to vendor Kubernetes, didn't save a repro and didn't post the glide.yaml when I made the bug. Bad bug reporting on my part. I'll close this and reopen with more information if I run into it again.

**Comment by mattfarina** [comment]
@colemickens we're aware of issues working with k8s. [Helm](github.com/helm/helm) has kubernetes as an import and on occasion I do an import, add a few aliases to the glide.yaml file generated, and test Glide on k8s. It's the aliases that fix the issues I'm aware of.

**Comment by colemickens** [comment]
:+1: :+1: I'm vendoring kubernetes once again for the client. Build times are much longer now but Glide is handling the vendoring like a champ. Thanks again for Glide.
