### ISSUE TITLE
glide update/get/install not working

### ISSUE THREAD

**Issue by atinmu** [Masterminds/glide#188]
When I am running the above it always fail with "Oops! No home directory set to create". What's the issue here?

**Comment by mattfarina** [comment]
@atinmu what version of Glide are you using? `glide --version` will tell you. What environment are you running in?

**Comment by atinmu** [comment]
@mattfarina : its the dev version
Also when I try to to pull the latest using `go get -u` I get the following error:

amukherj@atinmu:~/codebase/PoCs/go_workdir/pkg/linux_amd64/github.com$ go get -u github.com/Masterminds/glide
go install github.com/Masterminds/glide/gb: open /home/amukherj/codebase/PoCs/go_workdir/pkg/linux_amd64/github.com/Masterminds/glide/gb.a: permission denied
go install github.com/Masterminds/cookoo/io: open /home/amukherj/codebase/PoCs/go_workdir/pkg/linux_amd64/github.com/Masterminds/cookoo/io.a: permission denied
go install github.com/Masterminds/glide/msg: open /home/amukherj/codebase/PoCs/go_workdir/pkg/linux_amd64/github.com/Masterminds/glide/msg.a: permission denied
go install github.com/Masterminds/semver: open /home/amukherj/codebase/PoCs/go_workdir/pkg/linux_amd64/github.com/Masterminds/semver.a: permission denied
go install github.com/Masterminds/vcs: open /home/amukherj/codebase/PoCs/go_workdir/pkg/linux_amd64/github.com/Masterminds/vcs.a: permission denied
go install github.com/codegangsta/cli: open /home/amukherj/codebase/PoCs/go_workdir/pkg/linux_amd64/github.com/codegangsta/cli.a: permission denied

**Comment by atinmu** [comment]
@mattfarina I am on Fedora23

**Comment by mattfarina** [comment]
I can't explain the permission issue. That's something on your system.

There was a point when this error happened in the code and we fixed it. Can you get the commit id for the version you're running? Go fetches the repo so you should be able to go to the directory and get it. Want to see if this is the old bug or a new one.

Glide attempts to use the home directory (in the ~/.glide directory).

Also, are you running it in a Docker (rkt, etc) container?

**Comment by atinmu** [comment]
@mattfarina : The problem went away when I deleted ..../pkg/bin/..../Masterminds/glide
Thanks for your help
