### ISSUE TITLE
glide get --update-vendored warning

### ISSUE THREAD

**Issue by favadi** [Masterminds/glide#189]
`--update-vendored` problem in #174 is fixed in glide 0.8.2 but there is new problem.

Now whenever I use `glide get --update-vendored` I got error:

```
[WARN] Skipped getting github.com/miekg/mmark: fatal: destination path '/Users/favadi/code/uba/godeps/vendor/github.com/miekg/mmark' already exists and is not an empty directory.
: exit status 128
```

and

```
[WARN] github.com/codegangsta/inject appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
```

The command still exits with 0 returns code.

The test script: https://github.com/favadi/glide-get-error/blob/0f450a5fe22bea01fe12ad63c9fd2479efacf970/.travis.yml

The build log: https://travis-ci.org/favadi/glide-get-error/builds/98270258

**Comment by mattfarina** [comment]
Your script is [using 0.8.1](https://github.com/favadi/glide-get-error/blob/0f450a5fe22bea01fe12ad63c9fd2479efacf970/.travis.yml#L10). There was a but in 0.8.1 when doing `glide get --update-vendored` that we fixed for 0.8.2.

Can you test this with 0.8.2? I tried with the tip of master and can't reproduce the problem.

**Comment by favadi** [comment]
I copy the wrong link, acutally I tested with 0.8.2: 
https://github.com/favadi/glide-get-error/blob/test/.travis.yml.

You can see the build log, I will try with master branch.

**Comment by mattfarina** [comment]
I can replicate the problem now. Thanks for the bug report.

**Comment by mattfarina** [comment]
The issue appears to be that flattening isn't working for vendoring. There's [a section of code that doesn't handle vendoring properly](https://github.com/Masterminds/glide/blob/2446e8ba9eb47e12d5ceb2060575439603931f01/cmd/flatten.go#L173). [VCSUpdate](https://github.com/Masterminds/glide/blob/2446e8ba9eb47e12d5ceb2060575439603931f01/cmd/get_imports.go#L467) already handles updating, getting, and vendoring so we can simplify the logic around the bug.

**Comment by mattfarina** [comment]
@favadi thanks for the detail. I tested the fix with your script at https://github.com/favadi/glide-get-error/blob/test/.travis.yml.
