### ISSUE TITLE
Allow force re init to add new package to glide.yaml

### ISSUE THREAD

**Issue by netroby** [Masterminds/glide#193]
I tried to add new package using glide. but i failed.
So i have to delete glide.yaml first. then re run glide init to create glide.yaml again.
Why not just let us 

```
glide init -f
```

-f means force.
The project been developing day and day. we add new libraries more and more. we do not want this progress by hand

**Comment by netroby** [comment]
By default, we using go get to add package to project.
so we need a tools like ```glide rescan```
to rescan dependencies again

**Comment by mattfarina** [comment]
You are right that Glide should rescan dependencies in a project. In #162 I was thinking about adding that to `glide update`. So it happens without more work from users. What do you think of that?

**Comment by netroby** [comment]
If merge this feature into ```glide update``` seems not bad.
Good for me at least. if i run ```glide update```, i mean update everything, dependencies and version up to date

**Comment by technosophos** [comment]
`glide up` _does_ rescan dependencies, doesn't it? But it will just try to re-download them if the only copy of a dependency is on $GOPATH.

Is there a reason to not use `glide get PKG` instead of `go get PKG`?

**Comment by mattfarina** [comment]
@technosophos `glide up` does not scan _your_ codebase for new dependencies. It just scans the dependencies in the `vendor/` folder for changes. I think the suggestion here is to rescan _your_ codebase. That way you don't need to `glide get PKG` to make sure everything is present. A little extra automation.

**Comment by technosophos** [comment]
It does now! Yay! I think we can close this out.

**Comment by mattfarina** [comment]
@technosophos should it update the `glide.yaml` with the additions and warn of any unused in the `glide.yaml`?

**Comment by technosophos** [comment]
We should open a new issue for warning on unused dependencies. I need to test how it actually treats discovered dependencies. I might have backed out the change that allowed that, because we talked about it being dangerous to include directly imported packages that were not explicitly set.
