### ISSUE TITLE
Remove hash from lock

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#197]
I'm considering removing the hash from the `glide.lock` file.

**What's the hash used for?**
The hash is based on the `glide.yaml` content and is used to verify that the `glide.lock` file is tied directly to the current state of the `glide.yaml` content.

This type of thing is used by composer (the PHP package manager) but you won't find it in others such as Cargo (for Rust).

**Why consider dropping it?**
There are a few reasons:

1. I'm getting ready to add elements to the `glide.yaml` file such as owner, license, etc. Adding this or making any changes will cause the lock to be invalid. That's annoying when you have a large dependency tree to update.
2. Numerous package managers don't do this today and everything is fine.
3. There have been some hiccups in usability around this. I, who wrote the functionality, have run into issues which are annoyances. I would prefer if others didn't encounter them as well.

@technosophos @sdboyer any insights to add?

**Comment by sdboyer** [comment]
the point i find most convincing is the first. but the hash could still be useful there if, instead of using the hash of the entire file, you just work on a hash of the (alpha sorted) set of specified packages and their vendor ranges. if those are the only things that can affect the dep graph, then there's no reason to include other information in the hash (except the convenience of computing the file's hash as a whole).

i have to ponder a little more on the second point. now that i'm back from the holidays, if i write that blog post that i mentioned last week, it'll entail that i work these issues through. so, hopefully, i'll do that :)

could you elaborate on some of the usability hiccups you've encountered?

**Comment by mattfarina** [comment]
@sdboyer the usability hiccup is when you have to run `glide up` to regenerate the `glide.lock` because you modified something non-interesting (license, updated version range but it doesn't affect your pin, etc) and you have a large project (like helm which pulls in k8s) to figure out.

I also ran into a weird issue that on Windows a known working hash (tested on Mac) was saying it wasn't the right one. A later update fixed it and I never found out why. I think that lowered my trust.

I'm considering removing the check but keeping it in the file. Maybe a message rather than simply failing `glide install`.

**Comment by sdboyer** [comment]
@mattfarina please reread my comment with the suggestion about changing what's computed in the hash and re-address

**Comment by mattfarina** [comment]
@sdboyer potentially. It would require the hash calculation to be more work (create an alpha ordering) and less usable with other tools. For example, is you run `shasum -a 256 glide.yaml` on the `glide.yaml` in the Glide project you'll see the value that's inside the `glide.lock` file.

**Comment by mattfarina** [comment]
Note, I've backed off exiting if the hash doesn't match. Instead there is a warning for now.

**Comment by sdboyer** [comment]
@mattfarina sure, it would make it less portable. But is there a concrete use case there? I can't imagine a workflow offhand where I would manually do `shasum -a 256 glide.yaml`. I'd expect glide would do that for me automatically, or provide a subcommand to tell me if it matches.

If the concern is for other Go tools' ability to work with that data, it's as simple as exporting a func that does the work.

At the end of the day, I don't *think* it makes sense to optimize that particular bit of the relationship for shell scripting. Or at least, not enough to justify hashing more than the actual data you care about.

**Comment by sdboyer** [comment]
Also, as a separate thought - is this perhaps one of those issues that looms much larger for the developer of the project than it would for a user?

**Comment by mattfarina** [comment]
Instead of an error this is now a warning. So, it doesn't stop you but it helps you identify if something is out of date. I'm happy with that.

**Comment by sdboyer** [comment]
I still think this is a mistake, but I'm almost done writing the article in which I lay out the broader case, so I'll let it rest until then.

**Comment by mattfarina** [comment]
What do you think should happen and why?

**Comment by sdboyer** [comment]
there's no change in [my view](https://github.com/Masterminds/glide/issues/197#issuecomment-167874728) on what should happen.

the 'why' is in the article, which is gonna *have to* be completed in the next 36 hrs.

**Comment by gm42** [comment]
> Note, I've backed off exiting if the hash doesn't match. Instead there is a warning for now.
@mattfarina that makes the hash much less useful. As of now, there is no way to verify (via CLI exit code) that you are using what you are supposed to be using.

I created #484 to outline this problem.

**Comment by ecbaldwin** [comment]
I'm pretty new to glide. My problem with the hash is that it (and the `updated` field written on the next line) are merge conflict generators. Let's say I create one commit to update one library and another commit to update another. In most cases, these two commits could easily be merged together and I can test the result. As it is, the hash and updated fields always end up in a merge conflict and the only way I know to resolve it is to rerun glide to regenerate them. This is painful. I don't see these fields as beneficial. I'd recommend revisiting the idea to remove them.
