### ISSUE TITLE
Conservative updating feature

### ISSUE THREAD

**Issue by robaman** [Masterminds/glide#208]
Discussed with @mattfarina  on IRC, the ability to remove a dependency from glide.yaml, and having glide.lock rewritten to reflect the removal without updating any of it's existing depency versions.

With bundler in the Ruby-world this is done by removing the dependency from the Gemfile, running 'bundle install' and then having the Gemfile.lock rewritten with the same versions, but without the dependencies related to the removal in it.

This works with or without having specified versions in the Gemfile.

For bundler the process is described in the bundle-install man page here: http://bundler.io/v1.3/man/bundle-install.1.html#CONSERVATIVE-UPDATING

**Comment by mattfarina** [comment]
Thanks for submitting this. I have some ideas how this can be done.

**Comment by technosophos** [comment]
Is this done with the new `glide rm` command? Can we close this?

**Comment by technosophos** [comment]
I believe this is exactly how `glide rm` works in the new 0.9 release. Marking this closed. Feel free to re-open if I misunderstood.
