### ISSUE TITLE
glide install fails with alias: "The Remote does not match the VCS endpoint"

### ISSUE THREAD

**Issue by colemickens** [Masterminds/glide#210]
My `glide.yaml`:

```
package: azkube
import:
- package: github.com/Azure/azure-sdk-for-go
  subpackages:
  - /arm/resources
- package: github.com/spf13/cobra
- package: code.google.com/p/go-uuid
  subpackages:
  - /uuid
- package: golang.org/x/crypto
  vcs: git
  repo: https://github.com/colemickens/crypto
  version: 147b0a0d44eaebb0e4b9c780d01b9af728575d49
  subpackages:
  - /pkcs12

```

Snippet of log from `glide install`:

```
[INFO] Fetching updates for golang.org/x/crypto.
[WARN] Update failed for golang.org/x/crypto: The Remote does not match the VCS endpoint
[WARN] Failed to set version on golang.org/x/crypto to 147b0a0d44eaebb0e4b9c780d01b9af728575d49: The Remote does not match the VCS endpoint
```

Error originates in source here: https://github.com/Masterminds/vcs/blob/master/repo.go

**Comment by colemickens** [comment]
Apologies, it looks like this is due to me not clearing out the relevant repo under `vendor/` before "switching" via the alias. I executed `rm -rf vendor/`  and then glide was able to install normally.

**Comment by bscott** [comment]
I still get this even while removing vendor directory.

**Comment by sparkLogic** [comment]
Yes, I still see this error even after `rm -rf vendor`

**Comment by JeanMertz** [comment]
Getting the same error, even after `rm`:

```
[ERROR]	Failed to set version on github.com/sirupsen/logrus to : The Remote does not match the VCS endpoint
[ERROR]	Failed to set references: The Remote does not match the VCS endpoint (Skip to cleanup)
```

**Comment by Connor-McGuinness** [comment]
We had the same problem and solved it by modifying the glide.yaml to case-strict match the VCS endpoint (`github.com/Sirupsen/logrus` became `github.com/sirupsen/logrus`) then clearing the glide cache (`glide cc`).

**Comment by bkleef** [comment]
Or try something like this:

```sh
glide cc; rm -rf ~/.glide; rm -rf vendor; rm glide.lock; glide install --force --strip-vendor
```

**Comment by sjansen** [comment]
For the benefit of anyone brought here by Google...

solution: https://github.com/sirupsen/logrus/issues/553#issuecomment-306591437
reason: https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

**Comment by ufukomer** [comment]
`glide cc` only 👍
