### ISSUE TITLE
`glide rebuild` doesn't handled an aliased package

### ISSUE THREAD

**Issue by colemickens** [Masterminds/glide#215]
```
$ glide rebuild
[INFO] Building dependencies.
[INFO] Running go build github.com/Azure/azure-sdk-for-go/arm/resources/resources
[INFO] Running go build github.com/spf13/cobra
[WARN] Error resolving packages: chdir /home/cole/Code/colemickens/azkube_gopath/src/github.com/colemickens/azkube/vendor/code.google.com/p/go-uuid/uuid: no such file or directory
[INFO] Running go build golang.org/x/crypto/pkcs12
```

```
package: azkube
import:
- package: github.com/Azure/azure-sdk-for-go
  version: 05d01d05e50f0fba241862806cc3d6ee20ee8585
  subpackages:
  - /arm/resources/resources
- package: github.com/spf13/cobra
  version: 9c9300901990faada0c5fb3b5730f452585c7c2b
- package: code.google.com/p/go-uuid
  vcs: git
  repo: https://github.com/pborman/uuid
  version: dee7705ef7b324f27ceb85a121c61f2c2e8ce988
  subpackages:
  - /uuid
- package: golang.org/x/crypto
  vcs: git
  repo: https://github.com/colemickens/crypto
  version: 147b0a0d44eaebb0e4b9c780d01b9af728575d49
  subpackages:
  - /pkcs12
```

Easy repro: this revision: https://github.com/colemickens/azkube/commit/b5af0b0eabe1d0a84852c09e80dd86912ab4e34f

Maybe I did the alias wrong? Even though it worked for other things? I've just removed all instances of `go-uuid` and reference the new location. This has unblocked me. Still curious about this though -- aliasing is one of the reasons I'm using glide.

**Comment by technosophos** [comment]
Yeah, that looks like a bug in the way it's building the URL to resolve during rebuild. I'll look into it.

Out of curiosity, are you seeing much in the way of performance improvements with `rebuild`? It was really optimized for Go 1.3-1.4, and doesn't seem to have as much of an impact with 1.5 because of the way it does vendoring. I haven't yet retested on 1.6-RC. I'd like to find out whether people are finding it useful, still, and how effective it is. (And if you have any ideas of how to make it more so, I'd be up for hearing those as well).

**Comment by colemickens** [comment]
RE performance: for the Go versions, are you referring to the changes to Go that have changed it's compile speed? If so, I can't say that I've ever noticed a difference, even when using `glide rebuild`, but the projects that I'm using Glide with generally have a relatively small number of packages and I only rebuild when I suspect it will help `vim-go` figure out my completions.

As for this bug... actually, when I pull that revision on my project, delete the lock file, and use whatever glide is available at this very second... `glide install` is actually hanging:

```
[INFO] Lock file (glide.lock) does not exist. Performing update.
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/spf13/cobra.
[INFO] Fetching updates for github.com/Azure/azure-sdk-for-go.
[INFO] Fetching updates for code.google.com/p/go-uuid.
[INFO] Fetching updates for golang.org/x/crypto.
[INFO] github.com/spf13/cobra is already set to version 9c9300901990faada0c5fb3b5730f452585c7c2b. Skipping update.
[INFO] code.google.com/p/go-uuid is already set to version dee7705ef7b324f27ceb85a121c61f2c2e8ce988. Skipping update.
[INFO] github.com/Azure/azure-sdk-for-go is already set to version 05d01d05e50f0fba241862806cc3d6ee20ee8585. Skipping update.
[INFO] golang.org/x/crypto is already set to version 147b0a0d44eaebb0e4b9c780d01b9af728575d49. Skipping update.
[INFO] Setting version for github.com/spf13/cobra to 9c9300901990faada0c5fb3b5730f452585c7c2b.
[INFO] Setting version for code.google.com/p/go-uuid to dee7705ef7b324f27ceb85a121c61f2c2e8ce988.
[INFO] Setting version for github.com/Azure/azure-sdk-for-go to 05d01d05e50f0fba241862806cc3d6ee20ee8585.
[INFO] Setting version for golang.org/x/crypto to 147b0a0d44eaebb0e4b9c780d01b9af728575d49.
[INFO] Resolving imports
[INFO] Found Godeps.json file.
[INFO] Fetching updates for github.com/spf13/pflag.
[WARN] Conflict: golang.org/x/crypto ref is 147b0a0d44eaebb0e4b9c780d01b9af728575d49, but also asked for 346896d57731cb5670b36c6178fc5519f3225980
[INFO] Keeping golang.org/x/crypto 147b0a0d44eaebb0e4b9c780d01b9af728575d49

**nothing happens, glide is still running**
```

**Comment by mattfarina** [comment]
Two things.

1. `glide rebuild` was used for prior to the vendor experiment. Everyone should use `go install` instead.
2. The issue here is an error inside the resolver. The following is stuck in a loop:

```
[DEBUG] Found /Users/mfarina/Code/go/src/github.com/colemickens/azkube/vendor/code.google.com/p/go-uuid
[DEBUG] Dependency code.google.com/p/go-uuid has already been pinned. Setting version skipped.
[DEBUG] Trying to open /Users/mfarina/Code/go/src/github.com/colemickens/azkube/vendor/code.google.com/p/go-uuid/uuid
[DEBUG] ImportDir error on /Users/mfarina/Code/go/src/github.com/colemickens/azkube/vendor/code.google.com/p/go-uuid/uuid: open /Users/mfarina/Code/go/src/github.com/colemickens/azkube/vendor/code.google.com/p/go-uuid/uuid: no such file or directory
```

So, we have a bug. Thanks for finding this.

**Comment by mattfarina** [comment]
To add some more detail...

* `code.google.com/p/go-uuid` is aliased to `github.com/pborman/uuid`
* The package `code.google.com/p/go-uuid/uuid` is being imported (notice the subdirectory). The `uuid` directory doesn't exist in `github.com/pborman/uuid`.

**Comment by mattfarina** [comment]
Glide now catches this recursion and reports the underlying error.

I also added a new deprecating rebuild with a note to use go install instead.

If there is still an issue please let us know.

@colemickens thanks for all the great feedback.

**Comment by technosophos** [comment]
Just to wind this down... the point of `glide rebuild` was to build `.a` files in $GOPATH/pkg`, which used to substantially speed up things like editor support, build times, and test runs. Once the vendor experiment was introduced, the speed advantage pretty much disappeared.

If enough people use this feature, I'd like to take another shot at improving this. Otherwise, I think we should deprecate it before 1.0
