### ISSUE TITLE
add a 'glide rm' command

### ISSUE THREAD

**Issue by arschles** [Masterminds/glide#218]
Similar to how `glide get my/package/name` adds the package to the `glide.yaml`, computes dependencies, and adds everything to the `glide.lock`, it would be helpful to have a `glide.rm` do the opposite.

Currently, I'm getting around this issue by manually removing the dependency I don't need anymore and then running `glide up my/removed/dependency`

**Comment by technosophos** [comment]
Based on my discussions with @arschles, this would be distinct from `glide up` in that it would not update any of the pinned versions for existing non-removed dependencies.

**Comment by arschles** [comment]
ah, right. I forgot that, but it's a very important clarification. :+1:

**Comment by technosophos** [comment]
I think this is all done now.

**Comment by arschles** [comment]
thanks @technosophos
