### ISSUE TITLE
Parallel Glide Up

### ISSUE THREAD

**Issue by gerred** [Masterminds/glide#225]
Right now, it appears as if `glide up` is sequential. This is sort of painful for larger sets of dependencies.

It'd be really nice if Glide could fetch updates for multiple dependencies at a time. Any particular architecture barriers to that right now? Happy to PR it.

**Comment by technosophos** [comment]
It's on a feature branch due to be merged very shortly (`feat/no-cookoo`).

**Comment by technosophos** [comment]
@mattfarina can I close this now that we have this feature merged onto `master`?
