### ISSUE TITLE
EnsureGoPath fails when GOPATH has multiple directories listed

### ISSUE THREAD

**Issue by gus** [Masterminds/glide#226]
So, if your GOPATH has multiple directories listed, the new `EnsureGoPath` function fails when calling a stat on `$GOPATH/src`.  e.g.

```
> export GOPATH=/tmp/foo/.go:/tmp/foo
> GO15VENDOREXPERIMENT=1 glide install
[ERROR] Could not find /tmp/foo/.go:/tmp/foo/src.
[INFO] As of Glide 0.5/Go 1.5, this is required.
[ERROR] Wihtout src, cannot continue. stat /tmp/foo/.go:/tmp/foo/src: no such file or directory
```

This was introduced with [the latest commit](https://github.com/Masterminds/glide/commit/87489e82b1ac46345089552b7a6736c10f582ece#diff-fbd61ea1f28a9198f93880a8e505bc37R90).

**Comment by charneykaye** [comment]
+1 .. As of this morning, I'm experiencing the same failure.
