### ISSUE TITLE
resolving imports on "appengine"

### ISSUE THREAD

**Issue by abrykajlo** [Masterminds/glide#228]
Somewhere in the dependencies of our project there is an:

```
import "appengine"
```

in the main.go folder of a subpackage we are not using. In the case of an appengine app this makes sense and will import properly but in the case of calling `glide up` this depency with give a:

```
[ERROR] Failed to fetch appengine: Cannot detect VCS
```

**Comment by mattfarina** [comment]
I can help with this. Two things:

1. [Helm uses the `ignore` property to skip that. Try doing the same thing.](https://github.com/helm/helm/blob/e71f845ca56fa21509d942c71f0d68201eb105d8/glide.yaml#L3)
2. We are going to try and make waling the import tree more intelligent so it automatically skips things like this.

Does that help?

**Comment by abrykajlo** [comment]
@mattfarina yes thank you
