### ISSUE TITLE
install does not create a lock file if it does not exist

### ISSUE THREAD

**Issue by dmitris** [Masterminds/glide#229]
https://github.com/Masterminds/glide#glide-install says at the end of the section:
```
If no glide.lock file is present glide install will perform an update and generate a lock file.
```
but after the recent change, it no longer happens.  `glide install` just dies with the message:
```
[INFO] Lock file (glide.lock) does not exist. Performing update.
[ERROR] No update performed. FIXME.
```
which must be coming from https://github.com/Masterminds/glide/blob/master/action/install.go#L23

We relied on the documented `go install` behavior so now it breaks the builds...

@technosophos @mattfarina

**Comment by dmitris** [comment]
actually after some thought (and fixing failing builds), I would be in favor of keeping the commands' functionality focused and free from overlaps - so that `glide update` and `glide install` each does its own thing without calling each other.  Maybe we could turn the bug into the feature and document accordingly? I don't think it is big overheard or problem for users to call `go update && go install` if you don't have a lock file...

**Comment by mattfarina** [comment]
For now I wanted to replicate the 0.8.3 setup. In other package managers, such as composer for PHP, it installs the packages whether is needs to figure them out first or already has an existing lock file so it doesn't need to do that work.

**Comment by dmitris** [comment]
thanks for the quick fix and response!
