### ISSUE TITLE
glide exits with status code 0 when it fails to fetch dependency.

### ISSUE THREAD

**Issue by james-lawrence** [Masterminds/glide#250]
```bash
> glide install
# ...
# ...
[WARN] Update failed for golang.org/x/text: Cloning into '/var/app/current/vendor/golang.org/x/text'...
fatal: remote error: Git repository not found
: exit status 128
> echo $?
0
```

**Comment by technosophos** [comment]
Warnings to not result in an error code.

Was that really the last line of output from Glide?

**Comment by james-lawrence** [comment]
no it wasn't the last line sorry but the fact a dependency can't be fetched should be an error.

**Comment by mattfarina** [comment]
@james-lawrence you're right. That should be an error instead of a warning. We'll get that fixed prior releasing.
