### ISSUE TITLE
glide get should support specifying a commit/tag/branch at the CLI.

### ISSUE THREAD

**Issue by james-lawrence** [Masterminds/glide#254]
if it doesn't already, didn't see any hints in --help or the readme.

**Comment by mattfarina** [comment]
@james-lawrence `glide get` already supports that. You can read about it in [the docs](http://glide.readthedocs.org/en/latest/getting-started/#adding-more-dependencies). I just added a link to the readme pointing to the docs. We're just getting started with them.

**Comment by james-lawrence** [comment]
great sorry, for the spurious issue. =)

**Comment by mattfarina** [comment]
@james-lawrence no problem. I realized the documentation for it wasn't all the visible because of the issue.
