### ISSUE TITLE
glide list prints "[WARN] Package %s found in vendor/ folder format error"

### ISSUE THREAD

**Issue by chancez** [Masterminds/glide#255]
Looks like a missing argument to a Printf style function in `glide list`
```
~/g/s/g/c/soy ❯❯❯ glide list                                                                          glide ✭ ✚ ✖ ➜ ◼
[WARN] Package %s found in vendor/ folder
[WARN] Version not set for package github.com/golang/protobuf/proto
[WARN] Version not set for package github.com/golang/protobuf/proto
```

**Comment by pbennett** [comment]
Seeing same (w/ 0.9.0-rc1)

**Comment by james-lawrence** [comment]
try tip, I fixed one of those the other day.
https://github.com/Masterminds/glide/pull/251/files

**Comment by mattfarina** [comment]
@chancez @pbennett the warn you saw was fixed by @james-lawrence PR. I've also updated this to be info rather than a warning because that makes more sense. That change was in 8e813cf.
