### ISSUE TITLE
'create' command does not yield sub-packages in yaml field if root directory is not 'github.com'

### ISSUE THREAD

**Issue by jrsanz1** [Masterminds/glide#258]
Executing 'glide create' on this project structure:
**$GOPATH/src/test.com/test/goo
|-- main.go
|
|-- foo
|    |
|    |-- foo.go
|**

creates a yaml file with content:
**package: test.com/goo
import:
-package: test.com/goo/foo**

renaming 'test.com' to 'github.com' on project structure and imports in go files yields yaml file with content:
**package: github.com/test/goo
import:
-package: github.com/test/goo
  subpackages:
  -foo**

Would be nice if devs could name root directory of project structure whatever fits them. In my case I use a internal git server and would like the base directory to match the hostname.

glide version 0.9.0-rc1

**Comment by jrsanz1** [comment]
Had a chance to look at the code this morning. Looking at glide/utitl/util.go there's a set of regex for supported VCSs along with their hostnames. Easy fix for me is to hard-code my git repo hostname and regex pattern into this list.

Would be nice to dynamically define valid hostnames for glide to use thru a command and/or configuration file.

**Comment by james-lawrence** [comment]
imo glide needs to actually support git (and other vcs) natively. this https crap causes too many issues.

**Comment by mattfarina** [comment]
@jrsanz1 Glide supports the same patterns the `go` tool does for import paths including the naming for VCS related paths.

The `go` tool has a [lookup](https://github.com/golang/go/blob/387d5b8cfb085ed8d2a074586a0ee0e6e6cb9820/src/cmd/go/vcs.go#L817) that does special cases for GitHub, BitBucket, and some others. For others it [expects the root repo location to end in `.git`, `.hg`, etc](https://github.com/golang/go/blob/387d5b8cfb085ed8d2a074586a0ee0e6e6cb9820/src/cmd/go/vcs.go#L869). For example, `test.com/foo.git/bar/baz`.

Glide supports git, hg, bzr, and svn (the 4 VCS supported by the `go` tool) using [the same patterns the `go` tool does](https://github.com/Masterminds/glide/blob/31630140f540d4bf7a936dfd56309d7c5f095374/util/util.go#L185).

I'm not sure this is documented clearly anywhere by the Go team which means it can be a little confusing. Does this help?

**Comment by mhoglan** [comment]
@mattfarina that only occurs if the URL is HTTP based I believe.  Maybe that is the confusion?  I did notice on my usage that if I have a SSH style URL, I have to explictly specify `vcs: git` in my `glide.yaml`

Looking a the regex for GitHub for instance
```
pattern: `^(?P<rootpkg>github\.com/[A-Za-z0-9_.\-]+/[A-Za-z0-9_.\-]+)(/[A-Za-z0-9_.\-]+)*$
```

That would need to be 
```
pattern: `^(?P<rootpkg>github\.com(/|:)[A-Za-z0-9_.\-]+/[A-Za-z0-9_.\-]+)(/[A-Za-z0-9_.\-]+)*$
```

Then you could have `git@github.com:Masterminds/glide.git` and the extension `.git` would be picked up.

**Comment by jrsanz1** [comment]
It does, thanks.
