### ISSUE TITLE
Caching should be disabled when flag is not present

### ISSUE THREAD

**Issue by mhoglan** [Masterminds/glide#264]
Currently it looks like caching is disabled if you do not pass in the `--cache` flag, but really it is just erroring out because the directory does not exist and skips the caching step.

This is because the `cacheEnabled` var in repo/cache.go is always set to true and is never changed to false based on the `Installer.UseCache` value.

I explicitly set it to false in the code and rebuilt to see the difference.   I am not sure where the best place to set the var to false is.  The `cache.go` is not an object you interact with, but utility functions, so there is no singleton to change the value.   Could have the `installer.go` set the var when it is called on since it is in the same scope of the package, but that does not satisfy other files in the package if the installer is never called.   

When watching the DEBUG printout you can see the difference

```
[DEBUG] Attempting to find current branch for https://github.com/jmespath/go-jmespath
[DEBUG] Saving default branch for https://github.com/jmespath/go-jmespath
[DEBUG] Error saving https://github.com/jmespath/go-jmespath to cache - Error: open /root/.glide/cache/info/https-github.com-jmespath-go-jmespath.json: no such file or directory
[DEBUG] Attempting to find current branch for https://github.com/spf13/pflag
[DEBUG] Saving default branch for https://github.com/spf13/pflag
[DEBUG] Error saving https://github.com/spf13/pflag to cache - Error: open /root/.glide/cache/info/https-github.com-spf13-pflag.json: no such file or directory
[DEBUG] Attempting to find current branch for https://github.com/spf13/viper
[DEBUG] Saving default branch for https://github.com/spf13/viper
[DEBUG] Error saving https://github.com/spf13/viper to cache - Error: open /root/.glide/cache/info/https-github.com-spf13-viper.json: no such file or directory
```

vs

```
[DEBUG] Attempting to find current branch for https://gopkg.in/logfmt.v0
[DEBUG] Saving default branch for https://gopkg.in/logfmt.v0
[DEBUG] Unable to cache default branch because caching is disabled
[DEBUG] Attempting to find current branch for https://gopkg.in/stack.v1
[DEBUG] Saving default branch for https://gopkg.in/stack.v1
[DEBUG] Unable to cache default branch because caching is disabled
[DEBUG] Attempting to find current branch for https://github.com/hashicorp/hcl
[DEBUG] Saving default branch for https://github.com/hashicorp/hcl
[DEBUG] Unable to cache default branch because caching is disabled
```

Additionally it should not have tried to cache the default branch either, it just happens the branch logic is outside the `if cache { ... }` block in `Vcs.VcsGet`;   Wrapping the branch logic with `if cache { ... }` will save trying to determine the branch name and then trying to store it.   Did feel like it sped it up some, but may be just seeing the differences in download times per run.  Submitted pull request with the change.

**Comment by mattfarina** [comment]
@mhoglan Aside from the PR #265 is there anything else here?

**Comment by mhoglan** [comment]
What about the setting of the variable in the `cache.go` to the value that was determined by the command line?  Then you would get the proper error returned that the cache is disabled, where right now you get the error that the directory does not exist.

**Comment by mattfarina** [comment]
Caching is now always on. There is no on/off switch. The entire flow of handling has changed. I believe this is overcome by events.

If there is an issue with the latest code please let me know.
