### ISSUE TITLE
Glide ignoring windows dependencies

### ISSUE THREAD

**Issue by LK4D4** [Masterminds/glide#267]
I tried to run glide over docker/docker project and found that Windows dependencies weren't vendored.
I don't know how glide tracks dependencies for OS different from host OS, but seems like only way to collect all dependencies is `UseAllFiles` field in `build.Context`.
Also I tried to use os and arch fields for top package - it doesn't work :/

**Comment by mattfarina** [comment]
@LK4D4 Thanks for the issue.

First, @technosophos and I were recently chatting about the OS dependency issue. Glide works the same the go tool does. For example, to pickup linux dependencies on darwin you'd do:

```sh
$ GOOS=linux glide up
```

This isn't ideal. In the next release (likely 0.10) I'd like to make this situation better. I'll look at using `UseAllFiles`. Given our typical pace I would expect this out in the next month.

Now, can you provide a detailed example of the `os` and `arch` work you did. That should be working and I'd like to try to reproduce your problem if you can.

**Comment by LK4D4** [comment]
@mattfarina Yup, I'll post my experiments little later.

**Comment by mattfarina** [comment]
@LK4D4 Two things:

1. In the not to distant future we'll do a release likely using `UseAllFiles` to bring back better dependency walking. It's a small change and the current situation is a bug that comes up most often in docker work. Thanks for pointing this out.
2. The `os` and `arch` properties are on each import. So an import can only be used in certain environments. It's not for the entire file. I just looked at the docs and found them lacking here. I consider that a bug, too. I'll get that updated before the 0.9.1 release.

**Comment by LK4D4** [comment]
@mattfarina Ok, thanks. Actually just os, arch args for glide create would work for us, but `UseAllFiles` will be just awesome.

**Comment by mattfarina** [comment]
This fix will go out in version 0.9.1 early next week. Thanks again.
