### ISSUE TITLE
Glide fails on two packages in same dir

### ISSUE THREAD

**Issue by LK4D4** [Masterminds/glide#273]
Not sure if I should post issues against a master, but there is a pretty bad bug, which was brought by `UseAllFiles`. I encountered it as well when tried to write vendoring tool.
Error is next:
```
Failed to build an initial list of packages to scan: found packages archive (archive.go) and main (example_changes.go) in /home/moroz/project/workspace/src/github.com/docker/docker/pkg/archive
```
It's pretty obvious what's going on here, and it can happen in any dependency too. A possible way to avoid this is to catch that specific error and parse all files and collect all tags by hands except `ignore` and import it with custom `context`.
Thanks!

**Comment by bwiggs** [comment]
We're having a similar issue:

```
[ERROR] Error scanning github.com/lib/pq/oid: found packages oid (doc.go) and main (gen.go) in /home/ubuntu/.go_workspace/src/github.com/evosure/kraken/vendor/github.com/lib/pq/oid
```

**Comment by mattfarina** [comment]
@LK4D4 please feel free to post issues against master. I'll take a look at this in a bit.

**Comment by mattfarina** [comment]
If you use the `--resolve-current` flag on update it will disable `UseAllFiles`. Hopefully this can unblock anyone until I get a better look at it.

**Comment by mattfarina** [comment]
To add a little more detail... since you can't have two packages with different packages loaded in the same directory this is because build flags are skipped. In both examples here the differing package had a build flag to simply ignore.

**Comment by technosophos** [comment]
If we do a custom build context, we'll probably have to whitelist instead of blacklist. I'll try to look into that this weekend.

Thanks for the quick catch @LK4D4 and @bwiggs

**Comment by soul9** [comment]
couldn't this be a warning instead of an error, since go happily builds these packages.

**Comment by technosophos** [comment]
What if we set `build.Context.BuildFlags` manually to include the known architectures and operating systems? Essentially, I think we could build a "whitelist" that way.

**Comment by mattfarina** [comment]
@technosophos Build flags can be both positive (included) and have the `!` to be excluded. If something on that white list is a `!` in the file won't that file be excluded?

**Comment by technosophos** [comment]
Yeah, you're right.

**Comment by mattfarina** [comment]
FYI, I'm working on a fix. hope to have something up for review in the next day.

**Comment by mattfarina** [comment]
Can you please test the fix in the [pull request](https://github.com/Masterminds/glide/pull/277). Any feedback would be appreciated.
