### ISSUE TITLE
Error with golang.org/x/text

### ISSUE THREAD

**Issue by itscaro** [Masterminds/glide#276]
I got these errors with golang.org/x/text:

[ERROR] Error scanning golang.org\x\text: found packages text (doc.go) and main (gen.go) in ...\vendor\golang.org\x\text
[ERROR] Error scanning golang.org\x\text\language: found packages language (common.go) and main (gen_common.go) in ...\vendor\golang.org\x\text\language
[ERROR] Error scanning golang.org\x\text\unicode\norm: found packages norm (composition.go) and main (maketables.go) in ...\vendor\golang.org\x\text\unicode\norm

What does that mean?

**Comment by mattfarina** [comment]
This is a duplicate of #276. Working on a fix today.

**Comment by itscaro** [comment]
What is the ticket I need to follow? You quoted the same ticket here.

Thanks.

**Comment by nadermx** [comment]
I'm also getting this, and as @itscaro said you refrenced the same issue @mattfarina  trying to upgrade but can't seem to figure it out.

**Comment by hstern** [comment]
Was this ever fixed?
