### ISSUE TITLE
`glide update` vendors current repo if it contains subpackages

### ISSUE THREAD

**Issue by neilpa** [Masterminds/glide#290]
Trying to setup `glide` for first time on an application target that contains subpackages. The problem I'm running into is that it vendors the current repo subpackages since they're imported from the main package. That means `go build` uses the vendor directory rather than the primary source which may contain local edits.

It's a private repo but the glide project has the same setup and repros the issue. 

```
~/code/go/src/github.com/masterminds/glide ❯ glide update
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Masterminds/semver.
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for github.com/Masterminds/vcs.
[INFO] Fetching updates for github.com/codegangsta/cli.
[INFO] Detected semantic version. Setting version for github.com/Masterminds/semver to 1.0.1.
[INFO] Detected semantic version. Setting version for github.com/Masterminds/vcs to 1.4.0.
[INFO] Resolving imports
[INFO] Not found in vendor/: github.com/Masterminds/glide/action (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/msg (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/path (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/repo (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/util (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/cfg (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/dependency (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/gb (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/godep (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/gpm (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/tree (1)
[INFO] Not found in vendor/: github.com/Masterminds/glide/importer (1)
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Masterminds/glide.
[INFO] Setting references for remaining imports
[INFO] Project relies on 5 dependencies.
```

Is there some other way I should be bootstrapping my project so that `glide` doesn't try to vendor these subpackages? In the glide example those subpackages aren't in the `glide.lock` file but a `glide update` adds them.

**Comment by neilpa** [comment]
Similarly `glide init` generates a yaml file where the main package depends on itself. Using this project as an example if I nuke the existing `glide.yaml` and regenerate it

```
~/code/go/src/github.com/masterminds/glide ❯ rm glide.yaml glide.lock

~/code/go/src/github.com/masterminds/glide ❯ glide init
[INFO] Generating a YAML configuration file and guessing the dependencies
[INFO] Attempting to import from other package managers (use --skip-import to skip)
[INFO] Found reference to github.com/Masterminds/glide/action
[INFO] Adding sub-package cfg to github.com/Masterminds/glide
[INFO] Adding sub-package dependency to github.com/Masterminds/glide
[INFO] Adding sub-package gb to github.com/Masterminds/glide
[INFO] Adding sub-package godep to github.com/Masterminds/glide
[INFO] Adding sub-package gpm to github.com/Masterminds/glide
[INFO] Adding sub-package importer to github.com/Masterminds/glide
[INFO] Adding sub-package msg to github.com/Masterminds/glide
[INFO] Adding sub-package path to github.com/Masterminds/glide
[INFO] Adding sub-package repo to github.com/Masterminds/glide
[INFO] Adding sub-package tree to github.com/Masterminds/glide
[INFO] Adding sub-package util to github.com/Masterminds/glide
[INFO] Found reference to github.com/Masterminds/semver
[INFO] Found reference to github.com/Masterminds/vcs
[INFO] Found reference to github.com/codegangsta/cli
[INFO] Found reference to gopkg.in/yaml.v2

~/code/go/src/github.com/masterminds/glide ❯ cat glide.yaml
package: github.com/masterminds/glide
import:
- package: github.com/Masterminds/glide
  subpackages:
  - action
  - cfg
  - dependency
  - gb
  - godep
  - gpm
  - importer
  - msg
  - path
  - repo
  - tree
  - util
- package: github.com/Masterminds/semver
- package: github.com/Masterminds/vcs
- package: github.com/codegangsta/cli
- package: gopkg.in/yaml.v2
```

**Comment by mattfarina** [comment]
What version of Glide are you using (`glide --version`), how did you install Glide (homebrew, `go get`, a binary), and what OS/version are you running?

Glide has logic that detects when an import package is the same as the one it's in. We need to understand why that's not happening.

**Comment by neilpa** [comment]
I'm using version 0.9.1 installed via homebrew on OSX 10.11.3

**Comment by neilpa** [comment]
Just tried via `go get` and see the same issue.

**Comment by itscaro** [comment]
Env: go 1.6 windows/amd64 - glide 0.9.1

I have no problem with **Masterminds/glide**

**glide install**
`
PS C:\Users\itsca_000\workspace\git\go\src\github.com\Masterminds\glide> glide i
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Masterminds/semver.
[INFO] Fetching updates for github.com/Masterminds/vcs.
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for github.com/codegangsta/cli.
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references.
[INFO] Setting version for github.com/Masterminds/vcs to 9c0db6583837118d5df7c2ae38ab1c194e434b35.
[INFO] Setting version for github.com/Masterminds/semver to 513f3dcb3ecfb1248831fb5cb06a23a3cd5935dc.
[INFO] Setting version for github.com/codegangsta/cli to c31a7975863e7810c92e2e288a9ab074f9a88f29.
[INFO] Setting version for gopkg.in/yaml.v2 to f7716cbe52baa25d2e9b0d0da546fcf909fc16b4.
`

**glide init**
`
PS C:\Users\itsca_000\workspace\git\go\src\github.com\Masterminds\glide> glide init
[INFO] Generating a YAML configuration file and guessing the dependencies
[INFO] Attempting to import from other package managers (use --skip-import to skip)
[INFO] Found reference to github.com\Masterminds\semver
[INFO] Found reference to github.com\Masterminds\vcs
[INFO] Found reference to github.com\codegangsta\cli
[INFO] Found reference to gopkg.in\yaml.v2
`

**Comment by atombender** [comment]
Don't know if this applies to you, but this will happen if your project is not located in `$GOROOT` according to the Go maintainer's specifications. I discovered this when I [tried using symlinks](https://github.com/Masterminds/glide/issues/253).

**Comment by sbxalex** [comment]
@atombender Thanks, that's helpful. The problem indeed goes away when I enter my `$GOPATH` directly, instead of being in a different path on the filesystem that is symlinked under `$GOPATH`. It looks like these two issues might be closely related.

**Comment by atombender** [comment]
If you're using symlinks, then it's the same issue.

**Comment by neilpa** [comment]
In my case I'm not using symlinks and everything is under `$GOPATH`, `~/code/go` in my case above.

**Comment by mattfarina** [comment]
@neilpa This is a tough one. I can't remember seeing this. Can you share the results of `go env`. How did you install Go?

**Comment by neilpa** [comment]
I installed go via homebrew. 

```sh
~ ❯ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/neilpa/code/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.6/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.6/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

I can help debug this further if you point me toward potential offending code since I can repro this against `glide` master.

**Comment by hjkelly** [comment]
For the record, I had this problem and it _was_ because my `$GOPATH/src/github.com/<username>/<project>` was a symlink to the more convenient directory I normally work in. Deleting the symlink and moved the convenience directory there *did* keep it from finding/installing duplicates of my submodules

**Comment by mattfarina** [comment]
@neilpa Do you have any symlinks to the to any of the projects involved?

**Comment by veqryn** [comment]
I can confirm I have the same or a similar issue to the original poster.
I am running:
Windows 7, updated to latest service pack, etc.
Golang 1.6.
Glide version 9.3 pulled right from master today (2014-03-14, commit d5fc6b676a752b37f2646d91e9a463c97eb00519).

I have no symlinks at all, and GOPATH is set properly.

`glide update` fails to update my `glide.lock` file with the new commit hashes.
If I update them manually and then `glide install` it will work fine.  And if I `glide update` inside a docker container that has golang and glide installed, that also works just fine.

I run my commands, such as `glide update` through either `git-bash` or `mingw`.  I don't seem to have these issues if I run them through the horrible `cmd`.  I have a feeling this is a Windows issue.

Example output below.  In this case `api/ciolite` is my own code, and glide should not be trying to update it.  It also fails to update the version of logrus in the lock file, though it doesn't say any errors about it below.
```
$ glide update
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Sirupsen/logrus.
...
[INFO] Resolving imports
[INFO] Fetching api\ciolite into c:\Users\xxxxxx\workspace\xxxxxx\golang\src\vendor
[ERROR] Error looking for api\ciolite: Cannot detect VCS
...
[WARN] Unable to checkout api/ciolite
[ERROR] Update failed for api/ciolite: Cannot detect VCS
...
Cannot detect VCS
```

**Comment by neilpa** [comment]
Nope symlinks whatsoever.

**Comment by mattfarina** [comment]
@veqryn The errors are blocking the `glide.lock` file from being generated. Can you share your `glide.yaml` file or a representative version?

@neilpa are you on the latest 0.9.3 now? I asked because we fixed a number of bugs between 0.9.1 and 0.9.3. At the moment I'm a bit stumped because I cannot reproduce it (and I've tried on a couple macs). Any insight would be useful.

**Comment by neilpa** [comment]
After updating to 0.9.3 I can't repro consistently anymore. I was able to repro the `glide init` issue from above a couple of times but most of the time it works.

**Comment by veqryn** [comment]
My yaml looks approximately like this, but with more packages (all of which start with `github.com`):
```
package: .
import:
- package: github.com/Sirupsen/logrus
```

I can also confirm that I got the error today on linux ubuntu, when specifying the yaml file:
```
glide --home ./src/glide.yaml install
[INFO] Lock file (glide.lock) does not exist. Performing update.
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/Sirupsen/logrus.
...
[INFO] Resolving imports
[INFO] Fetching api/ciolite into /xxxxxx/xxxxxx/vendor
[ERROR] Error looking for api/ciolite: Cannot detect VCS
...
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for api/ciolite.
...
[WARN] Unable to checkout api/ciolite
[ERROR] Update failed for api/ciolite: Cannot detect VCS
...
Cannot detect VCS
```

**Comment by tve** [comment]
I encountered the same issue. My GOPATH was a symlink (i.e. GOPATH=/home -> /mnt/home). No symlinks under GOPATH, though. This used to work fine ('been using glide for months with this exact set-up). I understand that symlinks below GOPATH don't work, but above??

**Comment by mattfarina** [comment]
@veqryn I think the problem may be that your top level package is `.` rather than the path within the `GOPATH`. Can you update and try again. We use that path to determine things. If that's the issue it will help me determine a better experience for this problem.

@tve are you also using `.` as the package name or is it something else?

**Comment by tve** [comment]
I'm using github.com/yyy/zzz as top-level package

**Comment by veqryn** [comment]
@mattfarina do you mean that my glide.yaml and glide.lock file should be underneath a subdirectory of `$GOPATH/src`?

**Comment by veqryn** [comment]
Not sure if related, but I tried going up a directory (to `$GOPATH/src/api/`).
When running `glide init` inside a regular windows `cmd` terminal, Glide generated a yaml file like this:
```
package: api
import:
- package: github.com/Sirupsen/logrus
  subpackages:
  - github.com\Sirupsen\logrus
- package: github.com/aws/aws-sdk-go
  subpackages:
  - github.com\aws\aws-sdk-go\aws
  - github.com\aws\aws-sdk-go\aws\credentials
```
This looks fine I suppose, except that the slashes are forwardslash instead of backslash under subpackages, and the subpackages needlessly duplicate the regular package, and that the subpackages contain the root of the packages.


And when I ran `glide init` under `mingw`, I get something like this:
```
- package: api/ciolite
  subpackages:
  - api\ciolite
- package: github.com/Sirupsen/logrus
  subpackages:
  - github.com\Sirupsen\logrus
- package: github.com/aws/aws-sdk-go
  subpackages:
  - github.com\aws\aws-sdk-go\aws
  - github.com\aws\aws-sdk-go\aws\credentials
```

I have no idea why it is insisting on listing my own code as a package...

**Comment by chenziliang** [comment]
May i ask i how to get this workaround ? i still saw this issue by using version  `0.12.3`

**Comment by sdboyer** [comment]
@chenziliang these issues should have been resolved, so if you're still seeing them, could you please provide a detailed description of the context in which they're occuring? your go env, `glide.yaml`, the shape of your current project, etc.

**Comment by giniedp** [comment]
I am facing the same issue. However, i can workaround that in my case but i am not totally happy with the solution. Here is the setup

* the projects main directory is called `gbc3`
* it is located in a convenient location.
* it is symlinked into the `$GOPATH/src` directory
* main directory does not contain any go code
* all go code is in the subdirectory `backend`

Glide vendors all local dependencies if i run `glide init` from within `$GOPATH/src/gbc3` (or `CONVENIENTDIR/gbc3`) 

Glide vendors only external dependencies if i run it from `$GOPATH/src/gbc3/backend`. This is currently my workaround. However, i would like be able to run glide from the projects root directory.

My Env:
* macOS Sierra
* glide version 0.12.3 via homebrew
* glide version 0.13.0-dev via go get
here is the go env
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/alex/repositories/go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k1/wpppkyn91v7239smq8l90flh0000gn/T/go-build837011296=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by ggerrietts** [comment]
I came here with this problem -- I have `/Volumes/source/golang` as my `GOPATH` and a symlink in my home directory `~/golang` for ease of navigation. I kept seeing my subpackages submoduled and I could not understand why.

I'm glad this issue exists, but it might be a good FAQ entry.
