### ISSUE TITLE
GetRepo() error

### ISSUE THREAD

**Issue by itscaro** [Masterminds/glide#292]
I got this error with 0.9 and 0.9.1

[WARN] Unable to checkout github.com/itsjamie/gin-cors
[ERROR] Update failed for github.com/itsjamie/gin-cors: fatal: could not create work tree dir 'C:\workspace\git\go\src\app\vendor\github.com\itsjamie\gin-cors
': No such file or directory
: exit status 128

If in GetRepo() in glide/cfg/config.go, before calling newXXXRepo(), I create all the path (dest), it works.

Env: windows 10 + go 1.6 + glide 0.9.0/1 + git 2.6.2

Thank you.

**Comment by mattfarina** [comment]
Thanks for the level of detail. Are you using Cygwin, PowerShell, cmd.exe, or something else?

**Comment by itscaro** [comment]
PowerShell

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  63
```

CMD: same issue

Cygwin: same issue

**Comment by itscaro** [comment]
On windows, I think there is an issue with this configuration: (Other packages are well installed)

```
  - package: github.com/mattn/go-isatty
    os:
      - win
```

```
[ERROR] Failed to set version on github.com/mattn/go-isatty to 95b19fc23a6e8a63f2f0929f83c107fb85b869c3: open C:\workspace\git\go\src\app\vendor\github.com\mattn\go-isatty: Le fichier spécifié est introuv
able.
```

**Comment by mattfarina** [comment]
I think this is an issue where the parent directory needs to exist before the Git repo can be cloned into it on Windows.

**Comment by itscaro** [comment]
I would be happy to work on a PR.

**Comment by mattfarina** [comment]
That would be great! The work needs to be on the [Masterminds/vcs](https://github.com/Masterminds/vcs) project. Creating the directory, [like what was done for bzr](https://github.com/Masterminds/vcs/blob/master/bzr.go#L69), needs to be added to Git.

**Comment by elan100cs** [comment]
I created a pull request for this. The fix suggested here seems work for me.
