### ISSUE TITLE
glide up could handle changing aliased repos better

### ISSUE THREAD

**Issue by colemickens** [Masterminds/glide#294]
If you have a package aliased and change the repo the alias points to, git complains. It could check to see if the are unstaged/uncommited changes, and if not, add the new remote and switch quietly.

```
[ERROR] Update failed for github.com/Azure/go-autorest: The Remote does not match the VCS endpoint
```

**Comment by mattfarina** [comment]
I've gone back and forth on this. Should this be silent or automatic? Should it be an error to catch the users attention? I don't know if I like just doing it because this is the kind of change a user should be aware of.

I wonder if this is something we should put behind the `--force` flag.

**Comment by colemickens** [comment]
I guess in retrospect it's pretty obvious what the message is telling me. Not sure if it's worth the code to special case changing the repository.

I'm actually going to close this after reconsidering. Feel free to reopen it if you want to do something about it, but I think it's probably fine as-is.

**Comment by mattfarina** [comment]
@colemickens if you want to explore this in a pull request I'm open to it. As long as the UX is sane. Given all the other todos I'm likely not going to get to it myself anytime soon.
