### ISSUE TITLE
Code dependencies

### ISSUE THREAD

**Issue by nlamirault** [Masterminds/glide#296]
it is possible to push golang dependencies code into remote repository (like [1]).
My remote repository doesn't contains code [2], but beats project seems to push dependencies code [3].
How to do this ? Thanks

[1] : https://github.com/elastic/beats
[2] : https://github.com/nlamirault/abraracourcix/tree/master/vendor/github.com/garyburd
[3] : https://github.com/elastic/beats/tree/master/vendor/github.com/garyburd/redigo

**Comment by itscaro** [comment]
Why would you like to push dependency codes into your projet? The idea with a dependency manager is that you just need a configuration file and when you checkout your project you ask the dependency manager to get all dependencies at the version you defined in your configuration file.

**Comment by nlamirault** [comment]
To be safe the recovered code (broken repository, deleted repository, ....). Beats seems to used glide and add dependencies code too.

**Comment by smousa** [comment]
Hi, this could be related to the conversation here: https://github.com/Masterminds/glide/issues/289

**Comment by mattfarina** [comment]
If you want to strip the VCS information from the `vendor/` directory and have Glide still manage the updates you can do that. [I wrote about it yesterday](http://engineeredweb.com/blog/2016/glide-strip-vendor-vcs/).

We have some plans to enable doing this in an better and easier manner in the future.

**Comment by nlamirault** [comment]
Thanks it works now using the new tool.

**Comment by mattfarina** [comment]
While it's very new, someone just tweeted about https://github.com/sgotti/gvc. It's worth checking out. I'm going to poke at it some more in the coming week.
