### ISSUE TITLE
Glide Update is Unusable on Windows

### ISSUE THREAD

**Issue by kumarharsh** [Masterminds/glide#297]
I have a project with this structure:

```
| my-go-project
---| frontend
    ---| node_modules
---| vendor (glide packages go here)
---| glide.yaml
---| glide.lock
```

Whenever I do `glide update`, glide tries, for some baffling reason, to go into my node_modules folder right down to the absolute bottom of each node_module, and then dies because of running into the `MAX_PATH` problem in windows, and throws this error:

> [ERROR] Failed to build an initial list of packages to scan: GetFileAttributesEx D:\Workspace\<my-project-directory>\<frontend>\node_modules\babel\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\braces\node_modules\expand-range\node_modules\fill-range\node_modules\is-number\LICENSE: The system cannot find the path specified.

And hence, it never installs any new package - basically it's pointless having it.

**Comment by mattfarina** [comment]
I can explain what's happening.

Glide, like the `go` tools, scans the file system to figure out the dependencies. This was a feature request some time ago and it's an expectation because tools like `go get` do it as well.

This issue may be due to the Windows path length issues that come up in node.js with the deep nesting. Is that a problem? What version of npm are you using?

**Comment by mattfarina** [comment]
Glide walks the complete tree to be able to fetch all the dependencies. Glide creates reproducible packages and versions. Go projects can have go files in nested subdirectories to it needs to scan for them.

Glide can ignore some packages now. We likely need to add the ability to ignore some directories. That would solve your issue.

**Comment by kumarharsh** [comment]
Thanks. I understand that that's how go works, but if we are "absolutely" sure that no go file can be in some directories, it might be useful to save that trouble (and time) on every `glide update`

**Comment by kyteague** [comment]
Why does glide update look at all of the go files again when update is ran?

This is really non-standard behavior for package mangers.  I understand looking through the files to generate the initial glide.yaml, but after that it creates a lot of headaches.  In fact, I believe this behavior is the cause of most issues on GitHub.

I really want to use glide, but it just behaves in unpredictable ways and I have spent way too much time getting it to work (and still doesn't).

**Comment by kumarharsh** [comment]
@mattfarina any updates on this?

**Comment by mattfarina** [comment]
@kumarharsh I've personally got this as a use case so I'm working on it this week. Right now I'm attempting to figure out the new key for the `glide.yaml` file.

**Comment by mattfarina** [comment]
@kumarharsh Can you review the PR on #334?

**Comment by kumarharsh** [comment]
@mattfarina looks good, although I don't understand what you mean by review... I did this:

1. I pull your changes into the existing glide folder in my Go workspace, and then I built it using this command:
```
go build .\github.com\Masterminds\glide\glide.go
```

which gave me a `glide.exe` which I then placed in my project folder (for ease-of-use) and ran this:

```
./glide.exe update
```

and it still gives me the same error. Is there some more step involved, or maybe I'm doing something wrong since I'm not very familiar with how go builds the executable...

Also, the `excludes` option is set to `node_modules` - does it apply recursively, or only on first-level directories? Maybe that is why the error is coming

**Comment by kumarharsh** [comment]
Yes, I've verified it, it works! Only _top-level_ directories are ignored right now. For my use-case that's more than enough. Thanks a ton! :smile:

**Comment by mattfarina** [comment]
@kumarharsh There was a bug with directory separators between *nix and Windows preventing subdirectories. Thanks for catching that. I just fixed it on master.

With that I believe this can be closed. If there's anything else please let us know.
