### ISSUE TITLE
Go packages registry

### ISSUE THREAD

**Issue by ziflex** [Masterminds/glide#299]
Hi there,
You created cool package manager and I'm wondering are there any plans to create registry of go packages like npmjs.org or rubygems.org.
GitHub is a good place for source code, but it's not so good for publishing packages.

**Comment by mattfarina** [comment]
Let me state a few things:

1. I would like a central metadata repo (see http://packagist.org for an example with PHP)
2. Conversations have been happening for some time. I don't personally have the time but am working to help find the right home for something.
3. What should and should not be in something like this is under discussion. The Glide issue queue isn't the right place for those conversations.

For now I'm going to close this. If nothing happens in the Go community in the near future something may happen around Glide and I may try to organize people.

It's staying on the minds of a bunch of collective folks.
