### ISSUE TITLE
Semantic of install/update commands unclear

### ISSUE THREAD

**Issue by roblillack** [Masterminds/glide#30]
Hi,

the terminology of the two commands _install_ and _update_ ist somewhat misleading to me:

- Why is there a difference at all? If _update_ also installs dependencies, why have another command for that?
- If I change the `repo` of one of the packages in glide, I expect _update_ to:
  - Check, if there are local changes to the package, and FAIL with an error message.
  - If only the ref was changed, try to use whatever methods the VCS provides to check out that new ref.
  - If repo or VCS was changed, completely clear the src directory and re-fetch it using the configured VCS and repo.

  I _think_ that right now, only the second part is done, but the documentation is not really clear about this. Also, does it only do something along the lines of `git pull` or, does it check `glide.yaml` for changes, too?

**Comment by mattfarina** [comment]
I'd like to close this issue out. Most of the elements have their own issues carrying forward. In 0.5.0 `install` and `update` are commands aliased to each other. It's a matter of semantics at that point.

If there is some unresolved issue not documented somewhere please re-open or create a new issue.
