### ISSUE TITLE
deduce git VCS from the 'git@[...]' repo values

### ISSUE THREAD

**Issue by dmitris** [Masterminds/glide#301]
Would it be possible for glide to deduce the vcs value being 'git' (if not explicitly given) in cases where the the repo value starts with 'git@'?  It seems a bit strange and makes the glide.yaml unnecessarily longer if you have to keep adding `vcs: git` even though the vcs is clearly git from the `repo: git@opensource.mirror.company.com:foo/bar` values.  If agreed in principle, I'd be happy to send a PR.

**Comment by mattfarina** [comment]
I would like to see this. Someone has already started work on Masterminds/vcs#10 to get this going. I need to find a few minutes to finish getting that in and then we can roll that up the higher levels. It would be great if you did the PR here. It will get it in far faster that way.

**Comment by dmitris** [comment]
I see there is already https://github.com/Masterminds/vcs/pull/14 - would it solve the issue? (Don't want to duplicate the effort and waste reviewers' time :smile: )

**Comment by mattfarina** [comment]
@dmitris I'm going to put some focus on Masterminds/vcs now and we'll get some of this in soon.

**Comment by dmitris** [comment]
In my case, https://github.com/Masterminds/vcs/pull/14 did not help though I just installed the current glide with 'go get -u github.com/Masterminds/glide'.  I'm still getting errors: 
```
[ERROR] Update failed for github.com/dimfeld/httptreemux: Cannot detect VCS
```
The `import` entry looks similar to:
```
- package: github.com/dimfeld/httptreemux
  repo: git@opensource.mirror.acompany.com:dimfeld/httptreemux
  version: 25b5c5c1171b178c6df897f2043af4f72f488225
```

I think it is clear from the repo value that the vcs is Git; it would be great to avoid having to enter the redundant `vcs: git` for every import.

**Comment by mattfarina** [comment]
@dmitris That case is actually not handled yet. But, it's coming. I'll be continuing to iterate on it. I'll post here once that's in.

**Comment by dmitris** [comment]
ok thanks.

**Comment by mattfarina** [comment]
@dmitris this is now on the tip of master for github.com/Masterminds/vcs.
