### ISSUE TITLE
fetches deps more than once

### ISSUE THREAD

**Issue by thockin** [Masterminds/glide#308]
We have a dep ox X.  Something else we depend on has a dep on X, too.  When glide runs I get duplicate "Fetching updates for X".  One fix is to keep a map[string]bool that tracks updated packages.  To pass that through into both of the places that call VcsUpdate() is a little messy (ConcurrentUpdate() and InVendor() both call it).  As a hack, I added it to cfg.Config and plumbed it around.  It does seem to work but it's not the most clean.

Thoughts?

**Comment by jackspirou** [comment]
@thockin https://github.com/govend/govend uses a `map[string]bool` for that purpose: https://github.com/govend/govend/blob/master/deps/vend.go#L54

**Comment by technosophos** [comment]
Is it actually fetching twice? There is a map that tracks fetches, but
looking at what you typed, I am wondering if there is an edge case where
that map isn't shared between two fetch contexts (initial fetch and fetches
during addition dependency resolutions).

I've noticed that a few log messages are actually a little misleading. They
print before duplicate checks are run.

**Comment by thockin** [comment]
It does end up calling VcsUpdate() twice.

**Comment by ericchiang** [comment]
Since glide has a global cache as of 0.12.0 this is resolved, right?
