### ISSUE TITLE
update --update-vendored suggests I try --update-vendored

### ISSUE THREAD

**Issue by thockin** [Masterminds/glide#313]
I have all my deps vendored in with their .git directories stripped.  When I run `glide update -u` I get a bunch of warnings:

```
bitbucket.org/bertimus9/systemstat appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
[WARN] bitbucket.org/ww/goautoneg appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
[WARN] github.com/ClusterHQ/flocker-go appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
[WARN] github.com/Sirupsen/logrus appears to be a vendored package. Unable to set new version. Consider the '--update-vendored' flag.
```

and then some error:

```
[INFO] Setting version for github.com/aws/aws-sdk-go to bf2f8fe7f45e68017086d069498638893feddf64.
[ERROR] Failed to set version to b237c68bab4756507baf6840023be103853e77db: exit status 128
[ERROR] Failed to set version on github.com/influxdb/influxdb to b237c68bab4756507baf6840023be103853e77db: exit status 128
```

I'm not sure I understand what is happening or why it is telling me to do what I just did...

**Comment by thockin** [comment]
I may have totally horked my testing tree.  I'll try to rebuild my experiment from scratch.  Still, interesting error...

I will be OOO for 3 days, so not until after that at earliest

**Comment by mattfarina** [comment]
I can't seem to reproduce this problem. I'd like to. Can you share an environment or provide some instructions?

**Comment by thockin** [comment]
I rebuilt my whole repo and walked through `glide init` and `glide install` again, and I can not repro it either.
