### ISSUE TITLE
Resolve devImports

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#320]
In addition to imports, Glide should be able to resolve imports in test files.

**Comment by IvanMalison** [comment]
Status?

**Comment by mattfarina** [comment]
@IvanMalison A PR was started in #331. It still needs to be finished.

**Comment by mattfarina** [comment]
I'm moving this to the 0.11 release since it's not complete. The work has already been started.

**Comment by mattfarina** [comment]
Implemented on the tip of master.
