### ISSUE TITLE
Glide should default versions to latest commit.

### ISSUE THREAD

**Issue by abiosoft** [Masterminds/glide#323]
Hi,

I expect `glide init` and `glide get` to add `version` of the last commit hash to `glide.yaml`. Currently, version is not added. I know you can specify version for `glide get` but when the version is missing, I expect it to have the same version as the one in the `glide.lock` file.

Is there anything that I am missing ?

Thanks.

**Comment by mattfarina** [comment]
@abiosoft The `glide.yaml` file is about the intent. The version listed in there is the intended version with the tip of the default branch being the default. The version can be a semantic version, semantic version range, a branch (to follow), a tag, or a commit id. The `glide.lock` file holds the current state. If you're following a branch it holds the commit id from the last update. If you're using a semantic version range it holds the commit id for the latest version resolved on update.

Does that help? Are you familiar with package manager tools for node.js, Rust, PHP, or other languages with similar tools?

**Comment by abiosoft** [comment]
Yeah I am familiar with npm and composer. I take that as a similar behaviour to `latest`. 
Thanks.
