### ISSUE TITLE
--delete flag to remove unspecified dependencies from _vendor

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#34]
From #30 

> a `--delete` flag to remove dependencies from `_vendor`, which are not specified (anymore) in `glide.yaml`

**Comment by technosophos** [comment]
To be more specific: `-delete` applies only to `go up[date]`, right?

**Comment by mattfarina** [comment]
That was the plan. I started the code (very rough) as a separate command so it could be reused elsewhere if we decided to. I need to get back to this.

**Comment by mattfarina** [comment]
@technosophos Do you think this should be a `--delete` flag to opt-in to deleting or a `--preserve-unused` to opt-out of deleting? I'm tempted to do the opt-out because I think deleting on update is the better default.

**Comment by technosophos** [comment]
Agreed.

On Tuesday, June 16, 2015, Matt Farina <notifications@github.com> wrote:

> @technosophos <https://github.com/technosophos> Do you think this should
> be a --delete flag to opt-in to deleting or a --preserve-unused to
> opt-out of deleting? I'm tempted to do the opt-out because I think deleting
> on update is the better default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Masterminds/glide/issues/34#issuecomment-112433681>.
>


-- 
http://technosophos.com
https://github.com/Masterminds
