### ISSUE TITLE
Eliminate duplicate caching code

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Masterminds/glide#343]
`VcsGet` has two checks for the `cache` boolean, with two blocks of code that appear to be redundant:

- [first block](https://github.com/Masterminds/glide/blob/master/repo/vcs.go#L394-L414)
- [second block](https://github.com/Masterminds/glide/blob/master/repo/vcs.go#L446-L465)

It appears that the second is redundant... but changes are scary [without tests](https://github.com/Masterminds/glide/issues/341).

**Comment by mattfarina** [comment]
This cache code was all removed now that the cache is all default. The `VcsGet` code is now far simpler.
