### ISSUE TITLE
Detect tags from commit ids for conflict resolution

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#353]
When resolving conflicts and possibly importing from others lock files detect tags associated with a listed commit. This will aide automating the SemVer handling.

See Masterminds/vcs#19 for implementation details with the VCS. This can be done fairly easily.

**Comment by technosophos** [comment]
That is a fabulous idea. Knowing that a commit ties to a tag actually makes life much easier for us.

**Comment by sdboyer** [comment]
big ups here. support for this is also on my TODO list in the solver.

ideally, the lock files generated should include both a tag (when applicable) and a revision. it doesn't actually obviate the need for this check - it mostly allows us to detect if/when upstream does something naughty and moves a tag. so...sorta related to this.

**Comment by mattfarina** [comment]
It's now displayed. See #459.
