### ISSUE TITLE
git submodules in vendor directory

### ISSUE THREAD

**Issue by dhawal55** [Masterminds/glide#357]
When i create the vendor directory using ```glide create``` or ```glide update --all-dependencies```, the vendor directory is created with dependencies having .git folder. This leads to issues when i commit my vendor directory as the ones with .git folder are ignored till i add them as submodules. It will be nice if glide strips out .git folder when downloading dependencies. I think godep does that.

**Comment by technosophos** [comment]
There are two ways to handle this:

1. Don't commit `vendor/` (which is what we usually recommend). `glide init` will re-fetch those dependencies on each system, and you won't need the overhead of checked-in dependencies.
2. Use the `--strip-vcs` (`-s`) flag, which will remove the various VCS folders. You can then safely check in your `vendor/` directory. When you update, you'll need to use `glide up -u` to have it re-calculate the dependency changes.

**Comment by dhawal55** [comment]
Great. `--strip-vcs` was what i was looking for.
