### ISSUE TITLE
Equivalent of `godep restore` ?

### ISSUE THREAD

**Issue by thockin** [Masterminds/glide#366]
This is going to be weird, but we need something...

First, we want to vendor code into the vendor dir with glide.  

Issue: we still build using go-1.4 for production binaries (we have a major perf hit in 1.5 and 1.6, we're working on it).  Obviously, go-1.4 does not support the vendor dir.  With Godep we have a choice - `godep restore` will check out the vendored revisions into my GOPATH so I can `go build`, or I can say `godep go build` and it will munge my GOPATH and build.

Glide seems to sort of kind of, but not really, support something similar in the form of `glide update -u --cache-gopath --strip-vcs --strip-vendor` - this pulls all the revisions from upstream and stores them in my GOPATH.  But in so doing, it removes and re-adds them in my project (which leaves a mess if it is aborted or crashes or anything) and it always updates glide.lock (just the timestamp).

We also do this in our CI to make sure that our vendor dir is still recreate-able from upstream and that the Godeps file (soon to be a glide file) is valid.  Changing glide.lock makes it harder to detect success (defined as no net change).

Is there any way to do a "non-modifying" operation that doesn't futz with glide.lock or my local vendor dir, but still pulls the versioned code from upstream into my GOPATH and strips VCS and vendor dirs?  Or maybe we can live with messing with the local dirs but not changing glide.lock ?

**Comment by sdboyer** [comment]
FWIW, i would generally prefer to see the timestamp either removed, or not updated if the file isn't changed - i'm not clear on what valuable information it's communicating by updating just the timestamp. (anybody interested in that information can effectively get it from the controlling VCS).

Maybe @mattfarina can enlighten me?

**Comment by thockin** [comment]
@vishh a less huge issue for kubernetes

**Comment by mattfarina** [comment]
Since this problem is generally going to go away I would suggest this as a plugin. I've seen this request a couple times. Basically, I could suggest a plugin that copies the contents of the `vendor/` folder to the appropriate location in the `GOPATH`. Would that work?

@sdboyer The timestamp is to tell people or tooling when the last update occurred. If nothing has changed we can likely skip updating the timestamp.

**Comment by thockin** [comment]
Both suggestions sound good to me.

Specifically:

1) something like `glide copy-to-gopath` which copies from vendor/ to GOPATH
2) don't change timestamp on `glide update` unless something has changed

**Comment by sdboyer** [comment]
> The timestamp is to tell people or tooling when the last update occurred. If nothing has changed we can likely skip updating the timestamp.

:+1:

**Comment by thockin** [comment]
Given that we're going to embrace go-1.6, I only really need the fix to not touch timestamp unless other things have changed.  thoughts?

**Comment by mattfarina** [comment]
Two address the issues here.

* The timestamp is now only changed if the content has changed.
* With Go 1.7 not allowing for the disabling of the vendor experiment and security updates only for 1.7 and 1.6 I think we can skip the copy to gopath functionality.

I'm going to close this. If k8s does adopt glide and we need the copy-to-gopath I can make a plugin as part of my k8s time.

**Comment by thockin** [comment]
I think the main requirement is to test that I can recreate the currently
committed vendor/ tree from the various upstream sources.

**Comment by mattfarina** [comment]
@thockin with the exception of the new `client-go` that resides within the `staging` area of k8s and needs to be copied to `vendor/` you can do that. Do you need to maintain that workflow for long?

**Comment by thockin** [comment]
The client-go hack?  yeah, that's a temporary hack.  The general "must be
able to restore from the wild" flow we want.
