### ISSUE TITLE
glide get --quick isn't

### ISSUE THREAD

**Issue by thockin** [Masterminds/glide#369]
running `glide get --quick --update-vendored --strip-vcs --strip-vendor` takes O(minutes) to run and re-downloads ALL of my vendor directory.

That's not "quick".  why does it need to do all that?

**Comment by martinb3** [comment]
I'm seeing this too. Asking to `glide get` a single dependency seems to make glide try to touch the remote repos for _all_ dependencies.

**Comment by rilinor** [comment]
The same for me. Maybe we don't understand meaning of this option? -)
