### ISSUE TITLE
Why is glide vendoring the project that it's controlling

### ISSUE THREAD

**Issue by colemickens** [Masterminds/glide#371]
Right now I'm running `glide up` and glide is vendoring one of my subpackages? How and why is this happening?

**Comment by colemickens** [comment]
I assume this is related to the source code scanning which I still don't understand the need for.

**Comment by colemickens** [comment]
seems like setting the project to the fully qualified name in glide.yaml resolved this.

**Comment by mattfarina** [comment]
I've seen this before. We are relying on the `package` name to detect other projects that import the parent. This isn't the first time this has caused an issue. We may want to auto-detect it and do some handling around that.

**Comment by colemickens** [comment]
Thanks @mattfarina. Even just a warning would be great.
