### ISSUE TITLE
The golang.org/x/net package has issues depending on context

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#373]
Go 1.7 will have `context` in the standard library. The `golang.org/x/net` package has a build tag for go 1.7 and that file depends on the standard library version of `context`.

Glide looking at all the packages across all the build flags has a problem with this.

See https://github.com/golang/net/commit/afc22ee9133171570a267463982b542fb3edff5a#diff-22b1e0bcbf56beea47fa8ad88e890286R5

**Comment by sdboyer** [comment]
:sob:

**Comment by rschmukler** [comment]
Just ran into this as well...

**Comment by bfitzsimmons** [comment]
Ran into this today.

**Comment by mattfarina** [comment]
I hope to have this fixed (with a release) in the next day.

**Comment by mattfarina** [comment]
There's a fix posted to #376.

**Comment by caarlos0** [comment]
me too :(
