### ISSUE TITLE
Glide does not build git repos with code in subdirectories properly

### ISSUE THREAD

**Issue by baliw** [Masterminds/glide#38]
I'm trying to use a package that has it's code in a subdirectory of the repo.  This works fine for 'go get' style in glide.yaml

    - package: github.com/ryszard/goskiplist/skiplist

However, it fails in git style config

    - package: github.com/ryszard/goskiplist/skiplist
      vcs: git
      ref: master
      repo: https://github.com/ryszard/goskiplist.git

The error:

    [WARN] Failed to run 'go install' for github.com/ryszard/goskiplist/skiplist/: can't load package: package github.com/ryszard/goskiplist/skiplist: no buildable Go source files in /Users/dan/projects/pie/_vendor/src/github.com/ryszard/goskiplist/skiplist

When checking out the file structure, it seems Glide has added an additional `skiplist` in the path.  So now the buildable files are actually under _vendor/src/github.com/ryszard/goskiplist/skiplist/skiplist

**Comment by technosophos** [comment]
Yeah, that looks like a bug.

If you remove `/skiplist` from the package URL, it should work fine. You can also add `subpackage: ...` if you want that package to be prebuilt into a `.a` file.

**Comment by mattfarina** [comment]
Should we look for github packages, pull off those that are subpackages and append them to the subpackage list automatically?

**Comment by mattfarina** [comment]
This should now be fixed with b78f4d78775e1f9c345ef76e16494f683087bd14. If there's still a problem please re-open the issue.
