### ISSUE TITLE
Don't change the lock's timestamp if nothing else changed

### ISSUE THREAD

**Issue by sdboyer** [Masterminds/glide#396]
Per the discussion in #366, if nothing else has changed when it comes time to write out a lock, then the timestamp shouldn't change either.

**Comment by mattfarina** [comment]
Yup, totally

**Comment by thockin** [comment]
Looking forward to this one...  We have only a small list of issues left...

**Comment by mattfarina** [comment]
Please see #420. It's a PR to implement this change.
