### ISSUE TITLE
"glide update" does not work as expected

### ISSUE THREAD

**Issue by roblillack** [Masterminds/glide#40]
This is somewhat related to #30 but got forgotten when you created single issues.

Adding a new dependency to glide is somewhat of a hassle. After adding `github.com/spf13/viper` to my `glide.yaml` this is what the output of `glide update` looks like:

```
[INFO] Updating github.com/spf13/viper with Git (From )
[INFO] Looks like github.com/spf13/viper is a new package. Cloning.
[WARN] Update failed for github.com/spf13/viper: exit status 128

…

fatal: reference is not a tree: 90734830d1ec30c19cb03e3ecd76a43dc1618b01

[WARN] Failed to set version on github.com/spf13/viper to 90734830d1ec30c19cb03e3ecd76a43dc1618b01: exit status 128

…

[INFO] Running go build github.com/spf13/viper
[WARN] Failed to run 'go install' for github.com/spf13/viper: can't load package: package github.com/spf13/viper: cannot find package "github.com/spf13/viper" in any of:
        /usr/local/Cellar/go/1.4.1/libexec/src/github.com/spf13/viper (from $GOROOT)
        /Users/rob/dev/darling/_vendor/src/github.com/spf13/viper (from $GOPATH)
```

Three errors here:
* Update should resort to installing this dependency. Glide notices this but still fails.
* This error shall be reflected in glide's exit code.
* Ideally, glide stops at the first error.

If I run `glide install` I get lot of warnings about all those other dependencies which are up-to-date. spf13/viper is installed correctly but cannot be built due to missing dependencies. Again, I'd expect glide to stop here, but it will build all other dependencies so I have to scan the whole output for errors.

glide version 0.2.0-43-g1a5c44e

**Comment by roblillack** [comment]
Pull request #41 fixes the first point, #42 the third.

**Comment by mattfarina** [comment]
@roblillack thanks for providing this. I'll take a look at it soon.

**Comment by technosophos** [comment]
I think we can mark this closed now, right @mattfarina ?

**Comment by mattfarina** [comment]
I think so. If there is a continued issue that's not been address or isn't in one of the other issues this can be re-opened.
