### ISSUE TITLE
To use Glide, you must set GO15VENDOREXPERIMENT=1

### ISSUE THREAD

**Issue by Integralist** [Masterminds/glide#402]
Hi,

I'm using Go 1.6 (which has native support for vendored directories), but it seems Glide _still_ requires the `GO15VENDOREXPERIMENT` environment variable to be set?

```
[WARN] To use Glide, you must set GO15VENDOREXPERIMENT=1
```

I would've expected this to not be needed once passed Go 1.5 and into 1.6+ releases?

**Comment by mattfarina** [comment]
@Integralist what version of Glide are you using? Glide now does detection. For Go 1.5 it makes sure it's enabled. In Go 1.6 it checks to make sure it's no disabled. In Go 1.7 (in dev) the environment variable is removed so detection is skipped.

**Comment by Integralist** [comment]
@mattfarina interestingly if I run `glide -v` I get back `glide version dev` ?

**Comment by Integralist** [comment]
OK so although I had done a `go get github.com/Masterminds/glide` I already had an old version and so it was just reusing that code base. I jumped into the location of glide in my GOPATH and did a `git pull` from `master` and then a fresh `go install` and so running `glide -v` now gives me back `glide version 0.11.0-dev` (which matches up to `go run glide.go -v` as well so I at least know I'm using the same version as what's in the master branch)

**Comment by Integralist** [comment]
Closed the issue as it seems the upgrade to the latest version of Glide resolved the problem

**Comment by mattfarina** [comment]
@Integralist you can also use `go get -u github.com/Masterminds/glide` to tell `go get` to pull the latest bits and install.
