### ISSUE TITLE
glide install --cache-gopath should cache the deps even if they are already vendored

### ISSUE THREAD

**Issue by dcu** [Masterminds/glide#407]
when you use that option and the deps are vendored they are not copied to gopath, so tools that don't use the vendor dir won't find the dependency.

**Comment by sdboyer** [comment]
> tools that don't use the vendor dir

Could you give an example of the tools you mean? Anything compiled with go 1.6 (or 1.5 with `GOVENDOREXPERIMENT=1`) and relying on the stdlib `build` package should pretty much pick up vendor dirs transparently.

I know there are still rough edges in places - my own vim setup still has some issues - but specifics would help.

**Comment by dcu** [comment]
in our case it's `apex` https://github.com/apex/apex
but in general the option says it caches the packages to the $GOPATH and it isn't

**Comment by mattfarina** [comment]
@dcu are the packages already in the `vendor/` folder?

Can you share tools that don't work with the `vendor/` directory? I'd like to make sure issues are filed against them then Go 1.4 is no longer supported by the Go team and Go 1.7 will be coming out soonish without a flag to turn off `vendor/`.

What uses do you have for copying it to the `GOPATH` as well? We're going to do some internal refactoring soon and I would like to know some uses cases folks have.

**Comment by dcu** [comment]
since this flag is deprecated I'm closing this ticket
