### ISSUE TITLE
Update brew formula

### ISSUE THREAD

**Issue by AlmogBaku** [Masterminds/glide#410]
The brew formula is outdated. The 10 version solves some very major issues (such as the context issue), and I think it'll be useful to update it.

**Comment by zerok** [comment]
What brew version are you referring to? https://github.com/Homebrew/homebrew-core/blob/master/Formula/glide.rb points to 0.10.2 :-)

**Comment by mattfarina** [comment]
@AlmogBaku did you try running `brew update`? I typically update homebrew myself the same day I perform a release.

**Comment by AlmogBaku** [comment]
@mattfarina sorry, i guess the reason was that i haven't update the brew... (in the meanwhile i compiled glide from the go sources)
