### ISSUE TITLE
Glide Install in Container Fails for Specified Repo

### ISSUE THREAD

**Issue by mikeln** [Masterminds/glide#421]
Overview:
Executing initial glide install within a golang 1.6 container (+glide 0.10.2).  (git version 2.1.4)
Dependency on kubernetes 1.2 packages.

glide --debug install --strip-vendor --strip-vcs --update-vendored
[INFO] Lock file (glide.lock) does not exist. Performing update.
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for speter.net/go/exp/math/dec/inf.
[INFO] Fetching updates for k8s.io/kubernetes.
[WARN] Unable to checkout speter.net/go/exp/math/dec/inf
[ERROR] Update failed for speter.net/go/exp/math/dec/inf: Cloning into '/go/src/github.com/samsung-cnct/barrel/vendor/speter.net/go/exp/math/dec/inf'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
[ERROR] Failed to do initial checkout of config: Cloning into '/go/src/github.com/samsung-cnct/barrel/vendor/speter.net/go/exp/math/dec/inf'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128

Note: this is the only glide.yaml package that I had to specify  vcs/repo.

Full gist: https://gist.github.com/mikeln/fab95b4e607fcccb57f25a0b93172e81

This does work if I run by hand in an os-x term instead. (different env, I realize).
I hope this is just some missing config setup in my container.

**Comment by mikeln** [comment]
Ok, it WAS my issue...but hopefully this will help others that run into this.

The issue was the specified git repo was the ssh version.  They container did not have any ssh keys known to github.  Changing it to the https:// version fixed the issue.

**Comment by mikeln** [comment]
Closing this since it wasn't a glide issue!

**Comment by AlmogBaku** [comment]
@mikeln have you succeed to force the container to use the ssh key?

**Comment by mikeln** [comment]
No.  We use the github repo https://<blah>  url vs the ssh version - git@github.com:<blah>

**Comment by AlmogBaku** [comment]
for whom who look for a solution- you can define a `repo` for a dependency and force it to use ssl. also- make sure you update your `glide.lock` file
