### ISSUE TITLE
*_test.go files aren't considered for package usage

### ISSUE THREAD

**Issue by terinjokes** [Masterminds/glide#423]
I'm running into a situation where a package (github.com/stretchr/testify/assert) gets installed because it's listed in my glide.yaml file. It vendors its dependencies. Because none of my non-test files import the assert package, Glide doesn't consider any of these packages as being used. It's fine though, since the packages exist in the vendor directory.

At least, until you use the `--strip-vendor` flag. Then the vendor directory is removed (as told). Since Glide doesn't consider any of the packages as being used, it doesn't install the dependencies anywhere else. 😢

**Comment by sdboyer** [comment]
I think this is another flavor of a known issue: #320

**Comment by terinjokes** [comment]
@sdboyer Yep, definitely. Didn't think that issue would be relevant.

I got stung by this when working on a project on a flight, I expected all my dependencies to be there.

**Comment by mattfarina** [comment]
Can you please test #461 which handles resolving test deps.

**Comment by mattfarina** [comment]
Fixed. Tip of master now handles test imports.
