### ISSUE TITLE
Wrong path in go test -coverprofile?

### ISSUE THREAD

**Issue by kamilchm** [Masterminds/glide#43]
Hi,
I'm trying to generate coverage report from my project root (where glide.yaml lives). When I d ``go test -coverprofile=c.out`` it produces files paths like:
```
_/home/kamil/projects/myproject/under_test.go
```
When I try to use it later with ``go tool cover -html=c.out`` it fails with:
```
cover: can't find "under_test.go": cannot find package "_/home/kamil/projects/myproject/" in any of:
	/opt/go/src/_/home/kamil/projects/myproject (from $GOROOT)
	/home/kamil/projects/myproject/_vendor/src/_/home/kamil/projects/myproject (from $GOPATH)
``` 
Does anyone know how to fix it?

**Comment by technosophos** [comment]
I am very interested in discovering what the root of this issue is. Can you post your $GOPATH?

**Comment by kamilchm** [comment]
```
$ echo $GOPATH
/home/kamil/projects/myproject/_vendor
```
I'm running ``go test`` under ```/home/kamil/projects/myproject`

**Comment by technosophos** [comment]
Just a quick update: @mattfarina and I are both looking into this one. Please let us know if you find out anything else.

**Comment by kamilchm** [comment]
I was off for last week and probably be for the next one, so I don't mind if you just leave it till I'll provide some better sample.

**Comment by jriquelme** [comment]
Hi, same issue here:

```
go tool cover -html=cover.out -o coverage.html
cover: can't find "downloader.go": cannot find package "_/home/jriquelme/r/yutubaas/" in any of:
	/home/jriquelme/local/usr/local/go/src/_/home/jriquelme/r/yutubaas (from $GOROOT)
	/home/jriquelme/r/yutubaas/_vendor/src/_/home/jriquelme/r/yutubaas (from $GOPATH)
make: *** [cover] Error 1
```

to make it work, I had to edit the cover.out file from:

```
mode: set
_/home/jriquelme/r/yutubaas/downloader.go:32.88,34.2 1 1
_/home/jriquelme/r/yutubaas/downloader.go:36.67,40.16 3 0
_/home/jriquelme/r/yutubaas/downloader.go:48.2,50.16 3 0
_/home/jriquelme/r/yutubaas/downloader.go:56.2,56.36 1 0
...
```

to:

```
mode: set
github.com/jriquelme/yutubaas/downloader.go:32.88,34.2 1 1
github.com/jriquelme/yutubaas/downloader.go:36.67,40.16 3 0
github.com/jriquelme/yutubaas/downloader.go:48.2,50.16 3 0
github.com/jriquelme/yutubaas/downloader.go:56.2,56.36 1 0
...

The project is in https://github.com/jriquelme/yutubaas

**Comment by mattfarina** [comment]
@jriquelme Thanks for the details. This is the kind of thing we needed.

Here's how I reproduced and what I observed. I cloned the repo at https://github.com/jriquelme/yutubaas. Then from the root of the repo I ran:
```
$ glide install
$ go test -coverprofile=cover.out
$ go tool cover -html=cover.out -o coverage.html
```
This failed because the second command created a cover.out file with the wrong paths. But, If i changed directory to `_vendor/src/github.com/jriquelme/yutubaas` and re-ran the second two commands it worked.

It seems the go cover tool expects to be nested down inside the GOPATH when generating coverage. I don't have a fix yet but I'm better understanding the problem.

**Comment by mattfarina** [comment]
I've discovered deep inside the go source (see inside the `go/build` package) it looks for directories inside the `src` directory and treats that differently from those that don't have a parent `src` directory. It expects a package to be inside a `GOPATH`. This is bubbling up to a problem here.

I don't have a fix, yet. Suggestions welcome.

In unrelated news, Go has goto and uses it in the `go/build` package.

**Comment by mattfarina** [comment]
Glide 0.5.0 took a quite different path. It now uses the Go vendor experiment and works with Go 1.5 and newer. In this new setup this should no longer be an issue. We're working within the bounds of what the go tool expects.

Please re-open if there is still a problem.
