### ISSUE TITLE
Binary for Linux ARM

### ISSUE THREAD

**Issue by wiget** [Masterminds/glide#448]
Please, add binary release for Linux ARM.

**Comment by mattfarina** [comment]
There are multiple ARM architectures. Are you asking for arm64 or a different variant?

**Comment by wiget** [comment]
Suitable for my BananaPi - armv7h :smile: . Users of Raspberry Pi 2/3 will benefit from this too.

**Comment by mattfarina** [comment]
Do you mean [`GOARM=7`](https://github.com/golang/go/wiki/GoArm)?

**Comment by wiget** [comment]
Yes

**Comment by cescoferraro** [comment]
armv6 is the rpi2.
armv7 is for the rpi3

**Comment by mattfarina** [comment]
I've been using [gox](https://github.com/mitchellh/gox) for cross compilation. It seems gox doesn't let you set the GOARM variable. Will need to look into alternative setups to build the release.

**Comment by cescoferraro** [comment]
@mattfarina have you filed it as a bug upstream? it seems odd

**Comment by franciscocpg** [comment]
Hi @cescoferraro 
I opened this [issue](https://github.com/mitchellh/gox/issues/67) proposing a PR, but no response yet.

**Comment by mattfarina** [comment]
With the v0.12.0 release there are arm binaries.
