### ISSUE TITLE
Unclear how to manage devImports

### ISSUE THREAD

**Issue by bartek** [Masterminds/glide#455]
Hiya,

Great project! I see my generated `glide.lock` file contains a `devImports` array, but how is this managed by `glide.yaml`? I am not able to see any documentation around how to either specify a dev import with `glide get` or if there's a specific flag I should set on a package within `glide.yaml`

Am happy to amend the documentation once I discover how to do this :)

Thank you!

**Comment by jredville** [comment]
http://glide.readthedocs.io/en/latest/glide.yaml/ discusses a `devImports` section in the yaml, with the same format as the `import` section of the yaml

**Comment by mattfarina** [comment]
PR #461 takes this and makes test imports work. Reviews appreciated.

**Comment by mattfarina** [comment]
Fixed. Tip of master now handles test imports.
