### ISSUE TITLE
Bitbucket and subpackages: Cannot detect VCS

### ISSUE THREAD

**Issue by vburenin** [Masterminds/glide#469]
It happened so, that we are using bitbucket for our internal Git repository. It seems like glide has some problems with it.

Our internal repository is configured like this. All git ssh keys are available on the system.

Glide version:
glide version 0.11.0-dev (c25976f8059b0749f821d4e9c3faf7a205114097)

config
```yaml
- package: go-superlib
  repo: ssh://git@stash.local.net:7999/superlib/go-superlib.git
  vcs: git
```
Glide version: glide version 0.11.0-dev

During the run of 'glide up' command I am getting the following set of warnings and errors:
```text
[INFO]	Downloading dependencies. Please wait...
....
[INFO]	Fetching updates for go-superlib.
....
[INFO]	Resolving imports
[INFO]	Downloading dependencies. Please wait...
[INFO]	Fetching updates for go-superlib/lib1.
[INFO]	Fetching updates for go-superlib/lib2.
[WARN]	go-superlib/lib1 appears to be a vendored package. Unable to update. Consider the '--update-vendored' flag.
[INFO]	Fetching updates for go-superlib/lib3.
[INFO]	Fetching updates for go-superlib/lib4.
[INFO]	Fetching updates for go-superlib/lib5/lib6.
[WARN]	go-superlib/lib2 appears to be a vendored package. Unable to update. Consider the '--update-vendored' flag.
[WARN]	go-superlib/lib3 appears to be a vendored package. Unable to update. Consider the '--update-vendored' flag.
[WARN]	go-superlib/lib4 appears to be a vendored package. Unable to update. Consider the '--update-vendored' flag.
[WARN]	go-superlib/lib5/lib6 appears to be a vendored package. Unable to update. Consider the '--update-vendored' flag.
[ERROR]	Failed to set version on go-superlib/lib1 to : Cannot detect VCS
[ERROR]	Failed to set version on go-superlib/lib2 to : Cannot detect VCS
[ERROR]	Failed to set version on go-superlib/lib3 to : Cannot detect VCS
[ERROR]	Failed to set version on go-superlib/lib4 to : Cannot detect VCS
[ERROR]	Failed to set version on go-superlib/lib5/lib6 to : Cannot detect VCS
[INFO]	Project relies on 38 dependencies.
An Error has occurred
```
All these lib1,lib2... are just the internal packages which are the part of "superlib".

There is a workaround. I just add go-superlib/lib1 and others into ignore section, once it's done glide up and glide install work as expected.
However, it would be great to fix this problem when glide tries to dig deeper then necessary.

**Comment by vburenin** [comment]
Any feedback on this? At least there is some interest in provided patch.

**Comment by technosophos** [comment]
Does it exist in `vendor/`?

**Comment by vburenin** [comment]
I tried both.

**Comment by mattfarina** [comment]
So, the issue is slightly different than what's being done in the PR #470.

Glide expects the package names to conform to the way `go get` does. In this case `go-superlib` isn't a valid remote location name.

If you are using stash 3.8.0 or later the package name should be `stash.local.net/superlib/go-superlib`. Glide should be able to work with this (in theory).

There's an [issue on Atlassians site related to this](https://answers.atlassian.com/questions/22652647/go-get-on-stash-repository).

Unrelated to that is the idea of breaking from conforming with `go get` package paths. @technosophos or anyone else... any thoughts?
