### ISSUE TITLE
Consider adding GO15VENDOREXPERIMENT support

### ISSUE THREAD

**Issue by kardianos** [Masterminds/glide#47]
In 1.5 the go command will read the environment variable GO15VENDOREXPERIMENT. If enabled, it will use the local "/vendor/" folder for dependencies. This replaces the need to manage GOPATH variables as dependencies can be fetched directly into the vendor folder and resolved there when built. This allows the GOPATH to not be modified. The contents of the vendor folder can be ignored.

Will you consider supporting this approach?

**Comment by technosophos** [comment]
Yes, we've been following this development pretty closely, and I would very much like to integrate it.

I guess we should build the nightlies and see how much of an impact this would have, but my reading of RSC's posts suggest that the integration should be pretty easy.

I'm very excited for the possibility that Glide would be able to focus on version and dependency management, and let the GOPATH management problems fade into the distance.

**Comment by kardianos** [comment]
A beta should be tagged soon. You may want to wait for that. In the
meantime you could think about migration strategies over the course of this
experiment and document it.

**Comment by mattfarina** [comment]
Done. See pre-release 0.5.0-beta1 and we'll soon be releasing 0.5.0. This is a major change for glide so we appreciate any feedback. We are fully embracing GO15VENDOREXPERIMENT.
