### ISSUE TITLE
Resolving transitive dependency versions

### ISSUE THREAD

**Issue by s-urbaniak** [Masterminds/glide#471]
Given we have a `project` depending on libraries `a`, and `b`, both having a transitive dependency to `c`, implying the following dependency tree:

```
        /--> a (v2.0) -> c (v1.0)
project
        \--> b (v2.0) -> c (v2.0)
```

It is unclear to me which version `c` is being inherited by `project`. Both libraries `a`, and `b` are being tagged and use glide for dependency management:
```
$ cd a
$ cat glide.yaml
package: github.com/s-urbaniak/a
import:
- package: github.com/s-urbaniak/c
  version: 1.0

$ cd b
$ cat glide.yaml
package: github.com/s-urbaniak/b
import:
- package: github.com/s-urbaniak/c
  version: 2.0
```

If I specify the following `glide.yaml` for `project`:
```
$ cd project
$ cat glide.yaml
package: github.com/s-urbaniak/glideFoo
import:
- package: github.com/s-urbaniak/a
  version: v2.0
- package: github.com/s-urbaniak/b
  version: v2.0

$ glide update
glide update
[INFO]	Downloading dependencies. Please wait...
[INFO]	Fetching updates for github.com/s-urbaniak/a.
[INFO]	Fetching updates for github.com/s-urbaniak/b.
[INFO]	Setting version for github.com/s-urbaniak/a to v2.0.
[INFO]	Setting version for github.com/s-urbaniak/b to v2.0.
[INFO]	Resolving imports
[INFO]	Fetching github.com/s-urbaniak/c into /home/sur/src/go/src/github.com/s-urbaniak/glideFoo/vendor
[INFO]	Downloading dependencies. Please wait...
[INFO]	Setting references for remaining imports
[INFO]	Project relies on 3 dependencies.

$ cat glide.lock
hash: ce94055020659e86340e3f552ab313b2f0baeeb9da1bd2d632196ff4990f70ba
updated: 2016-06-14T09:42:43.847865929+02:00
imports:
- name: github.com/s-urbaniak/a
  version: 7cc609c6efdb428053278d10ffb919b4ca268ece
- name: github.com/s-urbaniak/b
  version: 13f5b9c8d65387dd756eb280f27aaffb21ca942d
- name: github.com/s-urbaniak/c
  version: 28d7707bf8ec02afb4cb52805d5e96215002f843
devImports: []
```

glide lets `c` point to `28d7707` which is [`v2.0`](https://github.com/s-urbaniak/c/tree/v2.0).

Does glide simply always fetch the newest version of `c`? Also I don't see any output in the output of `glide update` giving a hint for this conflict.

**Comment by sdboyer** [comment]
@s-urbaniak atm, glide uses a simple algorithm - first-to-`c`'s constraint wins.

[`vsolver`](https://github.com/sdboyer/vsolver) is a new engine that we're working on integrating into glide (#384) which will change that to allow constraint reconciliation and formal conflict handling in arbitrarily complex depgraphs.

**Comment by s-urbaniak** [comment]
@sdboyer thanks for the quick clarification! closing this, since there is nothing to be fixed.
