### ISSUE TITLE
glide update deletes working dir

### ISSUE THREAD

**Issue by szank** [Masterminds/glide#48]
Hi, 
I did go get -u glide to newest version just now, and noticed a serious problem
When I call `glide update` on in my repo dir, it gets removed completely. 
I am not gliding in, and my repo is in dir 
```
~/work/go/src/github.com/szank/repo
```
where gopath is
```
~/work/go
```
Obviously --preserve-packages fixes the problem, but i lost quite a bit of code that I didn't push upstream because of this problem. 

I am not "gliding in", and I am not using _vendor dir (for now)

This is a nasty backwards compatibility breaking change if user is not rewriting gopath.
And there was no warning. 

Glide assumes that my own package can be removed because it is not in glide.yaml file. 
I think the best way to fix it is to check if glide.yaml file is not inside  $GOPATH/** subdirectory when deleting packages.

**Comment by mattfarina** [comment]
@szank Sorry about that. Not gliding in was not a case tested. I'll work to get a fix out soon. Likely sometime next week.

There will be some changes coming to glide over the next year that do some breaking. For example, we're going to support the movement to vendor/ in Go.

**Comment by szank** [comment]
Thanks for a quick reply, 
We are planning to use /vendor dir ourselves, when it becomes part of the language in go 1.5 I suppose. 

I don't mind breaking changes, as long as it doesn't delete my files :D
