### ISSUE TITLE
List of Plugins

### ISSUE THREAD

**Issue by heewa** [Masterminds/glide#491]
Is there a list of third party plugins somewhere, where glide users can discover extra functionality?

I wrote a plugin, so partly I'm looking for a way to share the thing I made to serve my own needs with the community. But also I'd love to see what others have made. I bet there's some useful stuff out there!

Maybe a section on the main Readme?

**Comment by mattfarina** [comment]
Thanks. Coming soon (in the next week).

**Comment by mattfarina** [comment]
Do we have an initial list of plugins to include? I'm aware of:

- glide-vc
- glide-hash

What others are out there?

**Comment by heewa** [comment]
There's [glide-brew](https://github.com/heewa/glide-brew) for turning glide deps into Homebrew resources.

**Comment by mattfarina** [comment]
#501 implements this.

**Comment by mattfarina** [comment]
Done. See http://glide.readthedocs.io/en/latest/plugins/
