### ISSUE TITLE
vendor code not in remote repo

### ISSUE THREAD

**Issue by torfuzx** [Masterminds/glide#493]
Hi:
There is no code in vendor directory because of git subproject.
I want to push vendor code to my private repo because pull dependencies too time consuming in a production environment.
How should I do?

**Comment by sdboyer** [comment]
I think what you probably want to run most of your `glide` commands - `get`, `update` and `install` - with `--strip-vcs --strip-vendored --updated-vendored`. This will give you a vendor dir that's free of `.git` directories, allowing you to commit it. Then, you'll no longer have to re-download those dependencies in your build environment.

Is that what you're looking for?

**Comment by torfuzx** [comment]
yeah.
This is it.
