### ISSUE TITLE
Cannot use `glide -v` when compiling from source using `make build`

### ISSUE THREAD

**Issue by RochesterinNYC** [Masterminds/glide#497]
When you compile glide from source (ex. https://github.com/Masterminds/glide/archive/0.10.2.tar.gz), `glide -v` will return `glide version` instead of `glide version 0.10.2` (if you had compiled using `go build` or something).

This is because the tarred source artifact is not a git repo and the following lines in the Makefile (https://github.com/Masterminds/glide/blob/master/Makefile#L2 and https://github.com/Masterminds/glide/blob/master/Makefile#L6) will set the `VERSION` incorrectly/to some empty value.

**Comment by mattfarina** [comment]
Good catch. I don't think we thought of that when crafting those scripts.
