### ISSUE TITLE
Glide release versioning tags have changed format

### ISSUE THREAD

**Issue by RochesterinNYC** [Masterminds/glide#503]
For Glide release version `0.10.2`, the release tag was [`0.10.2`](https://github.com/Masterminds/glide/releases/tag/0.10.2). For the latest Glide release version `0.11.0`, the release tag was [`v0.11.0`](https://github.com/Masterminds/glide/releases/tag/v0.11.0).

Why was the `v` prepared to the version number in the tag and going forward, will this be the format of release tags? I.e. `v0.12.0` for release version `0.12.0` and so forth?

Thanks for the clarifications.

**Comment by mattfarina** [comment]
This is a good question.

First, Glide doesn't care if the SemVer tag begins with a `v` or not. It handles both through the same process.

There are a few reasons for the change:

1. [GB](https://getgb.io/) recently started supporting SemVer but it requires the `v` and they don't appear to be interested in making it optional. This has been a long standing view espoused by Dave Cheney.
2. On the release page for GitHub they recommend SemVer and the `v` prefix.
3. An overwhelming majoring of Go apps and package that use SemVer have the `v` prefix. I did an analysis several months ago and found it to be a majority. I recently went back and looked again. The majority using the `v` has actually increased.

So, with that in mind I wanted package and sub-packages to work with other tools. At this release I added the `v`.

Does that help?

**Comment by RochesterinNYC** [comment]
Yup, I don't have a strong opinion about the prepended `v` or not, I was primarily looking for clarification as to what the version tags would look like going forward (my team does some auto-updating of dependencies and glide is one of them, we watch the github tags as an indicator for new releases). And it seems that they will have the `v` prefix going forward. Thanks for that clarification!
