### ISSUE TITLE
Ignored dependency in testImports

### ISSUE THREAD

**Issue by bakks** [Masterminds/glide#505]
I have a project with a `glide.yaml` file with the following (among other things):
```
ignore:
  - common
  - common/http
```

This project has a test file that imports `common/http`. After running `glide update` on v0.11.0 I see the following in my `glide.lock`
```
testImports:
- name: common/http
  version: ""
```

Basically an explicitly ignored module is showing up in the in `glide.lock`. I'm aware that doing relative imports in this way isn't the advised pattern. However - this was pretty unexpected behavior and I would guess is a bug? The reason I noticed it was that it broke the `glide install` I ran later on.

Hope this is helpful, let me know if any more clarification would be useful.

**Comment by mattfarina** [comment]
Thanks for filing the bug. I usually follow up a change release with at least one bug release before we work on more interesting changes. I'll add this to that release which should be out in the next week.

**Comment by charneykaye** [comment]
Same thing happening to us here. Every time we add deps via `glide get` or do a `glide update` these dependencies that ought to be ignored keep being re-added to the `glide.lock` file under `testImports` only. Thanks!

**Comment by mattfarina** [comment]
I believe #512 fixes this. If there are no issues found I'll merge on Tuesday.

**Comment by bakks** [comment]
Just to confirm - I ran `glide upgrade` on my project using `v0.11.1` and the issue appears to have been resolved. Thanks for fixing - Glide is awesome 👍
