### ISSUE TITLE
Add glide install --verbose flag

### ISSUE THREAD

**Issue by peterbourgon** [Masterminds/glide#509]
When fetching large deps (e.g. Kubernetes) on shaky internet, `glide install` can take a long time or fail mysteriously. A `--verbose` options, with more granular updates to the console, would help a lot.

**Comment by peterbourgon** [comment]
Really, any `glide <subcommand>` that interacts with the internet can make do with a `--verbose`.

**Comment by mattfarina** [comment]
@peterbourgon does the `--debug` flag provide what you're looking for is are you thinking of something different?

**Comment by peterbourgon** [comment]
Ah! Missed it. Thank you.
