### ISSUE TITLE
The script at https://glide.sh/get has an incorrect shebang

### ISSUE THREAD

**Issue by 7heo** [Masterminds/glide#524]
The script hosted at https://glide.sh/get has the following shebang:

    #!/usr/bin/env sh

while the correct one is:

    #!/bin/sh

##### Reason:
 `/bin/sh` is the *only* binary that is guaranteed to be at this path (excepted on Android, which has it in `/system/bin/sh`), as per [this document](http://in-ulm.de/~mascheck/various/shells/). And as per [that document](http://in-ulm.de/~mascheck/various/shebang/#env):

> However, the location of env(1) might vary. [...] it cannot strictly assure "portability" of a script.

I would open a PR if I could find the aforementioned script, but I couldn't find it. My guess is that it is not versioned.

**Comment by franciscocpg** [comment]
Hi @7heo.
The script is here https://github.com/Masterminds/glide.sh/blob/master/get.
Could you close this issue and reopen it at the project https://github.com/Masterminds/glide.sh?
Then, when you propose the PR you can reference this new issue.

**Comment by 7heo** [comment]
Sure. :+1:
