### ISSUE TITLE
Discussion: Multiple versions of the same dependency

### ISSUE THREAD

**Issue by whitlockjc** [Masterminds/glide#526]
Let's say I want to write a package that should compile against `k8s.io/kubernetes` but I really don't care about the version as long as it's `1.x`.  So in my `glide.yaml`, I have the following:

```yaml
# ...
- package: k8s.io/kubernetes
  version: 1.x
# ...
```

Now someone wants to use my package and they too build against `k8s.io/kubernetes` and their version is `1.3.x`.  Which version of Kubernetes would be installed into `vendor`?

Please forgive me if this has been answered already but my searching didn't find anything.  I will keep looking and if I find something, I'll close this and point to it.

**Comment by whitlockjc** [comment]
What I would hope for would be that the `1.3.x` constraint would be honored since that value also honors the `1.x` constraint.  I'm trying to figure out how I can say _"Build against the version of Kubernetes the building project uses as long as it's `1.x`"_.

**Comment by mattfarina** [comment]
@whitlockjc This is a good questions. Right now Glide tries to work out the best version and tell you about any conflicts it can't solve. Then you can resolve them by changing you `glide.yaml` file as you see fit.

In the near future we hope to have an update that solves the exact problem you are asking about without ever needing for you to manually make a change. The PR exists and is nearly ready so the feature is coming.

**Comment by whitlockjc** [comment]
Thanks @mattfarina.  Any answer to the specific scenario above?  I _think_ you're saying it would work as I expect but I just want to be sure.

**Comment by sdboyer** [comment]
@whitlockjc yes, it would work as you expect - the `1.3.x` constraint and `1.x` constraint are intersected together - the result of which is `1.3.x`, as you note - and that constraint is what's ultimately enforced on Kubernetes' version.

**Comment by whitlockjc** [comment]
Excellent.  Thanks a lot.
