### ISSUE TITLE
Glide 0.11.x not working on Windows

### ISSUE THREAD

**Issue by jonbo** [Masterminds/glide#527]
Any Glide command causes the process to hang and not print anything.

I tried both the release binary (https://github.com/Masterminds/glide/releases) and building from source (with Go 1.7rc3).

I decided to try an older release 0.10.2 and that works. (I'm new to Glide.)

**Comment by franciscocpg** [comment]
Hi @jonbo. Did you try with the latest go stable release (1.6.3)?

**Comment by mattfarina** [comment]
@jonbo what version of Windows are you on and how are using it (cmd.exe, cygwin, etc)?

Have you tried running the `--debug` flag. Running `glide --debug init` or `glide --debug update` to get a more verbose output.

**Comment by jonbo** [comment]
@franciscocpg Okay, I tried with Go 1.6.3 with no luck (built and even tried your release binary again).

@mattfarina I use Windows 7 (sorry, I thought I posted that earlier). I mainly use MINGW64 (from https://git-for-windows.github.io/) but also tried from cmd.exe and the terminal inside IntelliJ IDEA 15.0.6. I just tried your --debug flag suggestion, and like everything else, it just hangs the process, and doesn't print nor do anything at all (on 0.11.x).

**Comment by jonbo** [comment]
Wow, the good ole restart-your-computer fix. Sorry to have bothered you guys. Although it would be nice to know what the cause ultimately was. It doesn't make sense that 0.10.2 would work but not 0.11.x. I knew something was entirely wrong when my 'go **run** file.go' now had the exact same issue, so I restarted and that seems to have fixed everything. Anyway, again, sorry to have bothered you all.

**Comment by franciscocpg** [comment]
Cool @jonbo.
The  restart-your-computer fix is quite common on windows environment, :)
