### ISSUE TITLE
Why are subdirectories downloaded?

### ISSUE THREAD

**Issue by orloffm** [Masterminds/glide#531]
For example, I'm importing `golang.org/x/oauth2` and  `golang.org/x/oauth2/github`.

This is my lock file regarding this package (`internal` is referenced by files in the package itself):

	- name: golang.org/x/oauth2
	version: 1364adb2c63445016c5ed4518fc71f6a3cda6169
	subpackages:
	- github
	- internal

When I run `glide install -s -v`, I get all project's subdirectories in `vendor/golang.org/x/oauth2`. I don't need them. If I did, I would've added particular sub-packages to `import`s. Isn't this a bug?

**Comment by mattfarina** [comment]
There are a couple things here (with a near term solution at the end).

1. You have to fetch and download a complete repo. The repo systems do not provide another means of just fetching subdirectories. Tools that alter this either strip directories or copy in directories to final locations.
2. Dependencies all have licenses. Removing sub-directories may be seen as altering a codebase and subject to clauses in those licenses. Right now we're not stripping directories as to not touch on this issue until we have a better idea of the legal impact and how we should proceed.

The short term fix is there's a plugin called [glide-v](https://github.com/sgotti/glide-vc) that can strip out unused elements.
