### ISSUE TITLE
glide.yaml filename / extension

### ISSUE THREAD

**Issue by pkieltyka** [Masterminds/glide#54]
Hi,

I think glide looks cool.. but personally I can't stand to look at glide.yaml in my repository. Any chance you could drop the yaml extension and call the file: `Glidefile` or .. `Vendorfile`  ..? and keep it as yaml?

**Comment by mattfarina** [comment]
Thanks for the feedback. I'm not sure about dropping the extension. When you do that IDEs and text editors can't pickup the type for do source highlighting correctly. Some of these tools will even do linting and find bugs for you and that would stop working.

**Comment by technosophos** [comment]
Did we add the option to manually override the name? I know the code supports it, but I can't remember if we added a flag for that.

**Comment by mattfarina** [comment]
We've not implemented that yet.

**Comment by technosophos** [comment]
There is the `glide -y FILENAME` flag, which sets the name of the YAML file.

**Comment by mattfarina** [comment]
With `glide -y FILENAME up` you can do something like `glide -y Glidefile up --import`. This will be recursive, too. For dependent projects it will look for a `glide.yaml` file. The only one affected by `-y` is your local file.

This does mean that others won't be able to use your projects glide config as a dependency.

I'm going to mark this as close as I think it's handled for now.
