### ISSUE TITLE
Glide fails to detect some dependencies

### ISSUE THREAD

**Issue by arekkas** [Masterminds/glide#542]
I have two packages in one directory. One is [ladon](https://github.com/ory-am/ladon/blob/master/ladon.go) and one is [ladon_test](https://github.com/ory-am/ladon/blob/8319836a6390b366724fe2395513e3ed0d52689b/manager_test.go). When running `glide init` or `glide up`, dependencies from the `ladon_test` do not show up in `glide.yaml` nor in `glide.lock` nor in the vendor directory. I am using `glide version 0.11.0-dev`.

**Comment by arekkas** [comment]
`glide list` gives me:

```
INSTALLED packages:
        github.com/Sirupsen/logrus
        github.com/cenk/backoff
        github.com/davecgh/go-spew/spew
        github.com/go-errors/errors
        github.com/golang/mock/gomock
        github.com/golang/protobuf/proto
        github.com/hailocab/go-hostpool
        github.com/oleiade/reflections
        github.com/ory-am/common/compiler
        github.com/ory-am/common/pkg
        github.com/pmezard/go-difflib/difflib
        github.com/stretchr/testify/assert
        github.com/stretchr/testify/require
        golang.org/x/crypto/pbkdf2
        golang.org/x/net/context
        golang.org/x/sys/unix
        gopkg.in/dancannon/gorethink.v2
        gopkg.in/dancannon/gorethink.v2/encoding
        gopkg.in/dancannon/gorethink.v2/ql2
        gopkg.in/dancannon/gorethink.v2/types
        gopkg.in/fatih/pool.v2

```

**Comment by arekkas** [comment]
When renaming `ladon_test` to `ladon`, everything works as expected.

**Comment by arekkas** [comment]
Having packages like `ladon_test` around is quite important because it avoids import cycles when writing tests

**Comment by mattfarina** [comment]
@arekkas glide does handle tests. It seems you're using a dev version rather than a release. When is this dev version from? Can you try a release version?

**Comment by arekkas** [comment]
i update glide using `go get -u github.com/masterminds/glide`

**Comment by arekkas** [comment]
let me clarify, it is not about `foobar_test.go`, it's about naming a package `package foobar_test` instead of `package foobar`

**Comment by arekkas** [comment]
Running

```
$ cd $GOPATH/src/github.com/Masterminds/glide
$ git checkout v0.11.1
$ go install .
$ which glide
/Users/aeneas/workspaces/go/bin/glide
$ cd other_go_project

$ glide install / up / init
```

yields the same outcome.

**Comment by mattfarina** [comment]
@arekkas so, you have two packages with different names in the same directory? Is that the issue?

That should work as well. If that is the case we'll need to look into that.

**Comment by arekkas** [comment]
> @arekkas so, you have two packages with different names in the same directory? Is that the issue?

exactly

**Comment by arekkas** [comment]
It doesn't seem to be linked solely to having two packages in the same directory. For example: https://github.com/ory-am/fosite/blob/master/integration/helper_setup_test.go#L8 

Directory integration knows only packages `integration_test` but is missing the gorilla/mux package. You can probably reproduce this by doing:

```
$ go get github.com/ory-am/fosite
$ cd $GOPATH/src/github.com/ory-am/fosite
$ glide create
$ glide up
$ cat glide.yaml | grep mux
# should be empty
```

**Comment by arekkas** [comment]
This problem is annoying because you find the missing dependencies only on a clean GOPATH, which happens most likely on your CI system, which then again takes 5-10 minutes to run.

**Comment by sdboyer** [comment]
seems like the issue arises specifically when relying on the `package <pkg>_test` idiom? i have a feeling i might know where the issue is...

Ah, yep. The current resolver only reads `build.Package.TestImports`, but does not include `build.Package.XTestImports`. Imports from the secondary test package are kept in the latter property.

**Comment by arekkas** [comment]
Thanks for tracing this, unfortunately I have no idea how to fix this, so it's probably better if somebody else takes a shot at it

**Comment by sdboyer** [comment]
yep, i got it
