### ISSUE TITLE
PROPOSAL: Add ability to declare how to deal with multiple copies of the same package

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#55]
With Glide 0.5, it is now possible for two packages to declare the same dependency. During deep imports (`glide up` and `glide get`), each time a dependency is found, it is stored in the `vendor/` directory closest to the dependency.

So you can end up with cases where the same dependency appears multiple times:

```
vendor/foo/bar
vendor/x/y/z/vendor/foo/bar
```

This naively resolves the case of package collisions. However, there are some clear cases where this is not desired. Namely, where having one code base using multiple versions will lead to bugs.

## Proposed solution:

It seems that that the best place to handle this is in the top-level `glide.yaml`. I propose adding the following directives to the `glide.yaml` `package` object:

```
- package: foo
  required: once
- package: bar
  required: never
- package: baz
  required: any
```

Here's the behavior of `required`:

* once: Only one copy of this library is ever checked out, and the version is set to the version in the topmost `glide.yaml`. Thus, the combination of `once` plus `ref` will effectively pin the package on any sub repositories. The definitive copy will be stored in the top-level `vendor/`.
* never: Regardless of what Glide finds in the dependency tree, don't ever import a copy. This is a good idea to add, since we want to play nicely with other package management tools and techniques, which may need to manage a dependency on their own.
* any: The default strategy. Get any number of copies of the dependency. Store as close to the import as possible. This will result in deeply nested repos.

**Comment by abourget** [comment]
I also think this is needed.. however the semantics don't stand out as being ultra clear to me.. especially `require: never` and `require: any`.. someone not having this proposal would have a hard time knowing exactly what to expect out of this.

I'm trying to think of other ways to name this.. names stick.. so let's choose well.

**Comment by technosophos** [comment]
How about something like `allowMultipleCopies` with values `yes`, and `no`. For the `never` case, maybe we should handle that separately.

**Comment by abourget** [comment]
`canonical: true`, `singlecopy: true`, `topmost: true`, `resolve: canonical`, `once: true`, `no_copy: true`, `no_checkout: true`, 

I think the `never` isn't related to the fact we're doing a single import, or multiple imports, but rather the fact that we're doing an import at all.. so something like `no_import: true`, `ref_only: true`, `reference: true`.. but that doesn't sit well with the goal of a `glide.yaml` which is to list deps.. not sure about this one

`import_nested: true`, `import_nested: false` ? if you want `any` as the default strategy, then I guess that wouldn't be a good solution.. we'd need a `squash: true`, or `reduce: true` or something ?

`squash: true` (with default `false`) and `no_copy: true` ?

**Comment by abourget** [comment]
`flatten: true` ?

**Comment by interlock** [comment]
:+1:

**Comment by interlock** [comment]
Anyone working on this? I may fork and take a stab if no one is. We can settle the semantics of naming once a PR is submitted.

**Comment by technosophos** [comment]
With #70 merged, I think we should close this.
