### ISSUE TITLE
export step returning error with docker

### ISSUE THREAD

**Issue by adamwilbert** [Masterminds/glide#553]
[ERROR]	Unable to export dependencies to vendor directory: rename /tmp/glide-vendor378089091/vendor /go/.../vendor: invalid cross-device link

This is causing an error in my build step, formerly fetching/setting worked fine, but now exporting step is creating an issue.

**Comment by mattfarina** [comment]
Can you test the PR at #556.

**Comment by mattfarina** [comment]
Merged PR. This is fixed.
