### ISSUE TITLE
Vendor directory is empty on freebsd

### ISSUE THREAD

**Issue by testhmaa** [Masterminds/glide#566]
I recently started with glide on FreeBSD ( testing with trivial projects )
glide worked fine.
then disk crashed and i set-up similar things on new disk.
i used **glide install**, glide downloads all packages successfully into cache. However at the end, it gives an error

[INFO]  Replacing existing vendor dependencies
[ERROR] Unable to export dependencies to vendor directory: rename /tmp/glide-vendor747570618/vendor /home/xyz/vendor: cross-device link

and the vendor directory is empty(though it has directory structure )

NOTE: i found a temporary workaround over this, by doing glide install by keeping project in /tmp directory and then copying the vendor directory into my home directory. however i would like to get it fixed.
NOTE: the cache in home dir is complete

I suggest you use the same code as you use to extract the projects from homedir cache to /tmp/vendorxyz directory for moving vendor directory from tmp to project's vendor directory.

**Comment by testhmaa** [comment]
btw, if this is of any help, my go workspace $GOPATH is outside of home dir

**Comment by mattfarina** [comment]
This issue is due to inconsistent error message responses between different operating system. Glide attempts to detect a problem that can arise at a lower level and correct. Fix coming shortly.
