### ISSUE TITLE
Should recursive deps be listed in glide.yaml

### ISSUE THREAD

**Issue by lukehowell** [Masterminds/glide#584]
Wondering if sub-packages should be listed in the `glide.yaml`.  Using the example of `github.com/gorilla/mux` when it is installed `github.com/gorilla/context` is installed with it.  `context` is locked in the `glide.lock` file, however it is not in the `glide.yaml` file.

Using composer and npm for example the subdeps are versioned because they are all using vendoring in the package.  What happens when an imported package does not use vendoring?  When `glide update` is ran and the subpackage is updated to `master` it may be broken.  Is there a preferred method to handle this and if not would tagging the subdeps help?

**Comment by lukehowell** [comment]
I guess one possible solution is if there is a broken package after an update the broken package could be then version?  Open to suggestions or solutions.

**Comment by bweston92** [comment]
If you make use of it directly then yes that way is the package gets rid of it then you still have it.
