### ISSUE TITLE
why glide init is sooo slow than godep ?

### ISSUE THREAD

**Issue by imiskolee** [Masterminds/glide#589]
why glide init is sooo slow than godep ? 

its more than a few mutinues.

**Comment by mattfarina** [comment]
@imiskolee They are doing very different things.

Godep is coping the source from the `GOPATH` with the version of the package in the `GOPATH`. This is a fairly quick operation.

Glide is doing a bunch of things:
* It fetches missing packages to have locally including fetching forks and storing them safely.
* It attempts to work out the right version of the dependency to use and checks out that release (it does update VCS metadata to have versions in this process).
* It them puts the right version of the dependency in the `vendor/` directory (the equivalent step to what Godep does)

So, Glide is doing more.

**Comment by imiskolee** [comment]
@mattfarina thxs.
