### ISSUE TITLE
Add glide run (similar to npm run)?

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#59]
In issue #15 it was suggested a command, `glide run [script]` be introduced to have scripts listed in the `glide.yaml` file. The suggestion was to be similar to npm (https://docs.npmjs.com/cli/run-script).

While I don't have an opinion, yet, I wanted to entertain the discussion.

There are two things to consider:
1. There are security implications when sharing scripts this way. For example, someone could do something nefarious such as a script that does `rm -rf /`. This would then be easily shared and was a problem for npm.
2. Being cross platform scripts need to work for *nix/windows. Something like a Makefile for a project isn't always an option if you have windows devs.

**Comment by technosophos** [comment]
I'm nervous about the potential for misuse/security/accidents with this feature. If it was a popularly requested feature, I'd be inclined to do it. But...

**Comment by gdm85** [comment]
Ahem..but why? Do one thing and do it well, just saying.. ;)

**Comment by technosophos** [comment]
I'm closing this one, because it just doesn't feel in scope, and we haven't really had an requests for it.

**Comment by xxxtonixxx** [comment]
I would love to see this feature in glide 👍
