### ISSUE TITLE
lock.json not cleaned up on signals

### ISSUE THREAD

**Issue by chancez** [Masterminds/glide#590]
When I ctrl-c glide while running the `~/glide/lock.json` file is not cleaned up. It probably should be. 

I know glide resolve the file already existing itself, but it would be good to handle this normal case.

**Comment by mattfarina** [comment]
@chancez you're right. This should be pretty easy to handle since we can start a goroutine, look for the signal to quit, and then do the cleanup.

**Comment by mattfarina** [comment]
PR on #591
