### ISSUE TITLE
internal_test.go file doesn't seem to be linked when running tests

### ISSUE THREAD

**Issue by gsalgado** [Masterminds/glide#6]
I've setup a project of mine to use glide and with that I can get all of its dependencies (some aliased) and build everything. However, one of the packages in that project uses an internal_test.go bridge file to make private bits available to tests, and when I run the tests they fail because the names defined there can't be found. This obviously works as expected (i.e. tests pass) when I'm not using glide

In order to reproduce:

  1. clone https://github.com/monetas/btcwallet/tree/vp-test
  2. run 'glide in/install'
  3. run 'go test ./waddrmgr'

==== Test output =====

$ go test ./waddrmgr/
 _/home/salgado/tmp/btcwallet/waddrmgr_test
waddrmgr/common_test.go:71: undefined: waddrmgr.TstSetScryptParams
waddrmgr/manager_test.go:1016: undefined: waddrmgr.TstReplaceNewSecretKeyFunc
waddrmgr/manager_test.go:1021: undefined: waddrmgr.TstResetNewSecretKeyFunc
waddrmgr/manager_test.go:1039: tc.manager.TstCheckPublicPassphrase undefined (type *waddrmgr.Manager has no field or method TstCheckPublicPassphrase)
waddrmgr/pool_test.go:274: undefined: waddrmgr.RunWithReplacedCryptoKeyScript
waddrmgr/pool_test.go:360: pool.TstExistsSeries undefined (type *waddrmgr.VotingPool has no field or method TstExistsSeries)
waddrmgr/pool_test.go:423: pool.TstPutSeries undefined (type *waddrmgr.VotingPool has no field or method TstPutSeries)
waddrmgr/pool_test.go:443: manager.EncryptWithCryptoKeyPub undefined (type *waddrmgr.Manager has no field or method EncryptWithCryptoKeyPub)
waddrmgr/pool_test.go:447: manager.EncryptWithCryptoKeyPriv undefined (type *waddrmgr.Manager has no field or method EncryptWithCryptoKeyPriv)
waddrmgr/pool_test.go:452: undefined: waddrmgr.TstValidateAndDecryptKeys
waddrmgr/pool_test.go:452: too many errors
FAIL	_/home/salgado/tmp/btcwallet/waddrmgr [build failed]

**Comment by technosophos** [comment]
This is resolved now that we don't munge GOPATH.
