### ISSUE TITLE
can't Install Glide in Freebsd 10.x x86 or x64 

### ISSUE THREAD

**Issue by skythink** [Masterminds/glide#605]
hi ... 

im try to install glide to my freebsd for install graylog-collector-sidecar 

when im installing im have error like this 

get: [[: not found
Sorry, we dont have a dist for your system: freebsd i386

what can i do ? 

thanks :)

**Comment by mattfarina** [comment]
This is a bug in the installer script. I'll fix it shortly.

In the meantime you can download it from https://github.com/Masterminds/glide/releases.

**Comment by mattfarina** [comment]
I just updated the installer script to handle this situation. Should be fixed now.
