### ISSUE TITLE
glide get updates other deps

### ISSUE THREAD

**Issue by caarlos0** [Masterminds/glide#607]
I started an empty project with `glide init`, added some deps and did some work.

Some days later, I needed to add mixpanel to the mix, so I `glide get github.com/nitrous-io/go-mixpanel/...`.

That added the `go-mixpanel` dep, but also updated other unrelated deps, like sendgrid, for example.

Is this expected?

**Comment by sdboyer** [comment]
Expected, yes, but desired, no. Known issue (#328), and one that'll be resolved with the move to gps (#384).

**Comment by caarlos0** [comment]
@sdboyer oh, I searched for it and for some reason didn't found it.

Will close this one as dup, then.

Thanks
