### ISSUE TITLE
vendor/src directory is gone when we do "glide install"

### ISSUE THREAD

**Issue by suexcxine** [Masterminds/glide#613]
Here is part of my Makefile:

```
deps:                                                                            
    mkdir -p $(CURDIR)/vendor/src/github.com/username                              
    test -d $(CURDIR)/vendor/src/$(CURRENT_PKG) || ln -s $(CURDIR) $(CURDIR)/vendor/src/$(CURRENT_PKG)
    glide install
```

when glide install is done, the src directory is gone..

Things was OK in 0.11

**Comment by sdboyer** [comment]
As of glide v0.12.0, the vendor dir is removed and rebuilt as needed. There's a fair bit of pushback on this, and we're actively discussing it - see #597
