### ISSUE TITLE
V0.12.2 tag ref master branch

### ISSUE THREAD

**Issue by franciscocpg** [Masterminds/glide#616]
Hi @mattfarina.
I don't know what is happening (maybe a git rebase?) here but the master branch does not have the tag v0.12.2 ref in any commit.
You can check this with `git checkout master` and then `git describe --abbrev=0 --tags` or `git log --decorate`.
If you use some tool like `tig` or `gitk` you can see this issue graphically.

**Comment by mattfarina** [comment]
Master has diverged from the [0.12.x branch](https://github.com/Masterminds/glide/tree/Release-branch-0.12.x) of releases which is just getting bug fixes. That's where you'll find the v0.12.2 tag.

This is a similar to how go itself does release tags. You'll find those on the corresponding release branches.

Does that make sense?

**Comment by franciscocpg** [comment]
Thank you @mattfarina 
So this [PR](https://github.com/Masterminds/glide-ppa/pull/13/files#diff-81616a3b17429a2d7a410eca8a567de8R21) is going to fix a problem that was occurring in glide-ppa build script because I was expecting that master always have the latest release.
