### ISSUE TITLE
Optional subtree vendoring support

### ISSUE THREAD

**Issue by abourget** [Masterminds/glide#62]
About subtree merges: http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

I know this would be tying to some specific vendoring method, but I do feel optional tooling around this would be great.  I'm thinking in the veins of `gb-vendor` (https://godoc.org/github.com/constabulary/gb/cmd/gb-vendor) which is an external command, and optional.. but that understands the semantics of the `manifest` therein, and can help vendoring in different ways. `glide-subtree` ?

Right now with glide, the default flows really seems to suggest you either put nothing in your current repo, or you use submodules (which suck badly).  I'd like to be able to define the glide.yaml file properly, and then decide if certain libs should be merged as subtrees, and in that case, the same versioning info with branches and commit revisions would be really useful, as git doesn't keep that. The subtree commands are quite verbose and could be shrinked with the help of glide.yaml.

I was thinking of using the repository to define a slug that would be the Git remote, in a deterministic way.. so the glide.yaml would always checkout the same Git remote, etc..

**Comment by abourget** [comment]
Again, this could be a separate project.. I might be interested in working it out.. althought I'm currently having issues with panics and wrongly pinned revs! :)

thanks for the great tool.. I think the vendor experiment is the way to go too..

**Comment by technosophos** [comment]
Glide does support "plugins", which actually are more like the git porcelain/plumbing model.

The idea is that a separate program called `glide-subtree` would be available as the command `glide subtree`. We haven't built any plugins since very early in Glide's history, and this seems like it might be the perfect candidate for one.

**Comment by technosophos** [comment]
I'm also curious about whether or not this is a feature that the VCS library would be able to provide, @mattfarina

**Comment by mattfarina** [comment]
I've used both subtrees and submodules. I get how and when to use them and I've seen that they are a niche thing. I also wonder if it matters for those who vendor the dependencies in their app repo and aren't using git.

What about a flow that allows for something like `glide up --update-vendored` (a short flag name, too) that checks if a package location exists but is not a VCS repo. If so, it deletes it, fetches the specified version, in the `glide.yaml` file, and then deletes the VCS directory (e.g., `.git`).

I've figured out the basics of doing something like this but am less sure of the best way to track it. A flag? Something in the `glide.yaml` file?

It could be smart enough to only do this for the packages that are vendored and this should work with git subtree as well.

**Comment by mattfarina** [comment]
For reference, in case anyone else is following along...

https://developer.atlassian.com/blog/2015/05/the-power-of-git-subtree/
http://www.git-scm.com/book/en/v1/Git-Tools-Subtree-Merging

**Comment by abourget** [comment]
I like the simplicity of `glide`.. perhaps having a niche plugin to handle a specific flow, without sticking too much features and concepts in the main tool would be good.

I just want people to be able to checkout my repo, and hit "go build" right away, without needing to do any sort of external commands (let alone install them before they need them).

Most of my users will never touch the dependencies.. those who will will be aware of the `glide-subtree` or whatever `subtree` commands there are to manage them, back and forth to upstreams.

**Comment by technosophos** [comment]
I agree with the intent behind @abourget's last comment. I feel like a truly good vendoring tool will be as easy to use as possible for the end user, and not even having to install Glide is about as easy as it could get for them. Subtrees are a good route to get there.

Keeping in mind that this is not a thing we seem to be able to do with all 4 VCSes, I'm feeling like we should provide a generic (albeit sort of destructive) version as @mattfarina suggests. This would make it possible for maintainers to vendor packages into the current VCS, regardless of what the original VCS was.

But I think that there is the potential to add a git-specific plugin that maybe even allowed an extra YAML attribute like `subtree-ref` that would make it easy to track the upstream subtree against the locally checked out copy.

**Comment by mattfarina** [comment]
@abourget since this is a Git specific feature request and we now have a way to update vendored dependencies where git subtree could be used independently to push the changes to different locations I'm going to close this.

If you want to write a subtree add on (we handle add-ons in a Git style) I'd be happy to list it in the Readme and share its existence. I'd like to keep the features in Glide itself as being VCS agnostic (as best as possible) and I don't foresee @technosophos or I creating this ourselves.

Thank you for this suggestion. It caused me to look at this problem in a new way which lead to my view (and bug catching) around vendoring.

**Comment by gdm85** [comment]
:+1: very interesting idea! @abourget any plans to write such addon? otherwise I might try something :)
