### ISSUE TITLE
`glide guess` adds the local project as a dependency

### ISSUE THREAD

**Issue by abourget** [Masterminds/glide#63]
I have a `cmd/thing` subdir that loads `github.com/abourget/myproject`.. in which it lives.

Doing a `glide guess` adds that as a `package:`.. shouldn't it be ignored when its the parent package ?

**Comment by technosophos** [comment]
What's the value of the initial `package:` in the `glide.yaml` file?

**Comment by abourget** [comment]
it's `main`, but the local package is `frog` .. not sure why.

**Comment by abourget** [comment]
What I do is `go list --json|less` and check for the imported things from elsewhere.. and then I `glide get` .. I'd assume that's what `glide guess` does, doesn't it ?

**Comment by technosophos** [comment]
Yes, basically. It uses the `go/build` library directly. The project gets its own name from the `package:` line on the current file (instead of looking at the parent directories). So if the package line is `main`, it believes its package is `main`, and would then see `github.com/abourget/myproject` as a separate project.

**Comment by abourget** [comment]
hmm.. but why would it resolve `package` to `main` ? `go list --json` says:

```
        "Dir": "/home/abourget/go/src/github.com/abourget/frog",
        "ImportPath": "github.com/abourget/frog",
        "Name": "frog",
        "Target": "/home/abourget/go/pkg/linux_amd64/github.com/abourget/frog.a",
        "Stale": true,
        "Root": "/home/abourget/go",
...
```

**Comment by technosophos** [comment]
Actually, this is a vestige of the previous version of Glide, where the import path `go list` reported might not have been correct (because we were managing GOPATH at the time). I think it's time for me to take a look at this and see if we can do better now.

**Comment by technosophos** [comment]
Now that i look at the code, I see that we did refactor it to do essentially what go list does. Would you mind giving us an example of a problematic glide.yaml? I'm trying to reproduce locally and not having any luck.

**Comment by abourget** [comment]
Use this script, reproduces the problem:
```
#!/bin/bash

rm -rf $GOPATH/src/boo

mkdir -p $GOPATH/src/boo/vendor/mama
mkdir -p $GOPATH/src/boo/vendor/papa
echo "package mama
var Mama = 1" > $GOPATH/src/boo/vendor/mama/mama.go
echo "package papa
var Papa = 1" > $GOPATH/src/boo/vendor/papa/papa.go
echo "package boo
import \"mama\"
import \"papa\"
import \"fmt\"
func Start() {
    fmt.Println(mama.Mama, papa.Papa)
}" > $GOPATH/src/boo/main.go
cd $GOPATH/src/boo
glide init
glide guess
```

**Comment by mattfarina** [comment]
Using this script against the latest mater I got

```
[INFO] Found reference to mama
[INFO] Found reference to papa
package: main
import:
  - package: mama
  - package: papa
```

I didn't add the package `boo` but it also misnamed it as `main`.

**Comment by mattfarina** [comment]
I moved the `boo` directory inside a `foo` one. Other than that the same as the script above with the latest on master and I get...

```
[INFO] Found reference to mama
[INFO] Found reference to papa
package: foo/boo
import:
  - package: mama
  - package: papa
```

Does this fix the problem? Or, is something else still going on?

**Comment by abourget** [comment]
oh yeah :) way better thanks a lot :)
