### ISSUE TITLE
How to update only one library listed in glide.yaml?

### ISSUE THREAD

**Issue by com314159** [Masterminds/glide#638]
It will west time to update all of the libraries listed in the glide.yaml , many times I just need to update one , how to do it ?

I can use glide get to get only one library, but I have some config like versions or repo url in glide.yaml, so it really useful to update only one library listed in glide.yaml, can anybody help me ?

Thank you.

**Comment by sdboyer** [comment]
Can't right now, known issue. We're working on it!

#252

**Comment by com314159** [comment]
Thank you
