### ISSUE TITLE
auto detect new dependecies

### ISSUE THREAD

**Issue by mehdy** [Masterminds/glide#648]
There should be command to scan the code and detect the new deps that have been added to the project and it's being used and automatically add them to `glide.yaml`.

maybe something like `glide scan-deps` or `glide sd` for shortcut 
and even maybe not a new command! just adding the feature to the current `config-wizard` command

**Comment by sdboyer** [comment]
It's not necessary to do this (unless you actually want to add a constraint for those deps). The import path simply being present in your project is sufficient to ensure those imports are considered when computing dependencies.
