### ISSUE TITLE
May be can't support subpackages?  

### ISSUE THREAD

**Issue by penhauer-xiao** [Masterminds/glide#653]
[ERROR] Error scanning github.com/penhauer-xiao/concurrent-map/ucmap: open /home/igo/.glide/cache/src/https-github.com-penhauer-xiao-concurrent-map/ucmap: no such file or directory
[ERROR] This error means the referenced package was not found.
[ERROR] Missing file or directory errors usually occur when multiple packages
[ERROR] share a common dependency and the first reference encountered by the scanner
[ERROR] sets the version to one that does not contain a subpackage needed required
[ERROR] by another package that uses the shared dependency. Try setting a
[ERROR] version in your glide.yaml that works for all packages that share this
[ERROR] dependency.

**Comment by sdboyer** [comment]
Please file a proper bug report. Simply copying in an error message, absent any context, is not helpful.
