### ISSUE TITLE
[ERROR]	Update failed for golang.org/x/crypto/bcrypt: Cannot detect VCS

### ISSUE THREAD

**Issue by alex4Liang** [Masterminds/glide#660]
How can I install `golang.org/x/crypto/bcrypt`?

I have a glide.yaml which contains the following:
```
- package: golang.org/x/crypto/bcrypt
```
When I run `glide install`, it starts getting all the other packages and then exits with following error message:
```
[ERROR]	Update failed for golang.org/x/crypto/bcrypt: Cannot detect VCS
[ERROR]	Failed to do initial checkout of config: Cannot detect VCS
```

Also, when I tried `go get golang.org/x/crypto/bcrypt`,  error messages would be:
```
package golang.org/x/crypto/bcrypt: unrecognized import path "golang.org/x/crypto/bcrypt" (https fetch: Get https://golang.org/x/crypto/bcrypt?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```

I'm on OS X 10.11.6. I've also observed the same problems on our CI and build servers which run Ubuntu.
Any solution? Thanks.

**Comment by franciscocpg** [comment]
@alex4Liang, you stated that `go get golang.org/x/crypto/bcrypt` return
```
package golang.org/x/crypto/bcrypt: unrecognized import path "golang.org/x/crypto/bcrypt" (https fetch: Get https://golang.org/x/crypto/bcrypt?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```
As you can see, there is a i/o timeout from your machine to 216.239.37.1:443.
I just run the command now without any problem.

**Comment by alex4Liang** [comment]
Yeah, Thanks for reply. I just check the problem of GWT in China。
After I fixed my network, I rebuild my glide.yaml. When the option comes: 
```
[INFO]	Updating github.com/dgrijalva/jwt-go to use the release v3.0.0 instead of no release
[INFO]	The package github.com/dgrijalva/jwt-go appears to use semantic versions (http://semver.org).
[INFO]	Would you like to track the latest minor or patch releases (major.minor.patch)?
[INFO]	Tracking minor version releases would use '>= 3.0.0, < 4.0.0' ('^3.0.0'). Tracking patch version
[INFO]	releases would use '>= 3.0.0, < 3.1.0' ('~3.0.0'). For more information on Glide versions
[INFO]	and ranges see https://glide.sh/docs/versions
[INFO]	Minor (M), Patch (P), or Skip Ranges (S)?
```
I typed `M`, while I chose `S` last time. Then I works.
