### ISSUE TITLE
Can't fetch github.com/dolmen-go/shuffle-slice/shuffle with glide

### ISSUE THREAD

**Issue by dolmen** [Masterminds/glide#663]
I'm the author of [`github.com/dolmen-go/shuffle-slice`](/dolmen-go/shuffle-slice). The real go code is in `github.com/dolmen-go/shuffle-slice/shuffle`.

In `$GOPATH/src/github.com/dolmen-go/toto` I try to fetch `shuffle-slice` with the following `glide.yaml`:
```yaml
package: github.com/dolmen-go/toto
import:
- package: github.com/dolmen-go/shuffle-slice/shuffle
  version: fde1bc20ca2fd5fb2d73815270e548dc1cd0ffc2
```

But with glide v0.12.3 I always get « **The Remote does not match the VCS endpoint** »:
```
$ glide install
[INFO]	Lock file (glide.lock) does not exist. Performing update.
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching updates for github.com/dolmen-go/shuffle-slice.
[ERROR]	Update failed for github.com/dolmen-go/shuffle-slice: The Remote does not match the VCS endpoint
[ERROR]	Failed to do initial checkout of config: The Remote does not match the VCS endpoint
```

**Comment by dolmen** [comment]
This morning it works without any change on my side (well, a good night of sleep). Is it a GitHub issue?

**Comment by dolmen** [comment]
In any case it would be helpful to have verbose log for this case.

**Comment by dolmen** [comment]
I suspect I would have solved the issue by cleaning `~/.glide/cache`...

**Comment by sdboyer** [comment]
I'm glad your issue went away, but...

> `- package: github.com/dolmen-go/shuffle-slice/shuffle`

Even if this works for now, it's not the intended use pattern. You provide the project/repo root in the package list, and the tool statically analyzes your code to determine which packages are actually needed.
