### ISSUE TITLE
Option to bust glide cache for rebased repos.

### ISSUE THREAD

**Issue by TamalSaha** [Masterminds/glide#667]
We have a few repos which we occasionally need to rebase. This is done because those repos are maintained as a fork of some external repo.

Now, we would like an option that we can set in the glide.yml file for those repos to tell glide to bust its `.glide` cache when it does not match with remote. I would go as far as to say that this should be the default behavior. I feel this is a reasonable request since `.glide` is supposed to be a cache and remote vcs is always right.

Is this possible today? If not, can this feature be added?

**Comment by sdboyer** [comment]
> I would go as far as to say that this should be the default behavior. I feel this is a reasonable request since .glide is supposed to be a cache and remote vcs is always right.

This is the intended behavior, absent any flags, for the reason you give. So no, we won't add a flag, because it should just do this anyway :) #592 is the issue for the fix.
