### ISSUE TITLE
[ERROR]	Update failed for golang.org/x/net/context: Cannot detect VCS

### ISSUE THREAD

**Issue by penhauer-xiao** [Masterminds/glide#676]
[DEBUG]	Locking https-google.golang.org-grpc
[INFO]	--> Fetching updates for google.golang.org/grpc.
[WARN]	Unable to checkout golang.org/x/net/context
[ERROR]	Update failed for golang.org/x/net/context: Cannot detect VCS
[DEBUG]	Unlocking https-golang.org-x-net-context
[DEBUG]	Locking https-gopkg.in-mgo.v2
[INFO]	--> Fetching updates for gopkg.in/mgo.v2.
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Cannot detect VCS
[DEBUG]	Unlocking https-golang.org-x-crypto
[DEBUG]	Locking https-gopkg.in-vmihailenco-msgpack.v2
[INFO]	--> Fetching updates for gopkg.in/vmihailenco/msgpack.v2.
[WARN]	Unable to checkout golang.org/x/net/html/charset
[ERROR]	Update failed for golang.org/x/net/html/charset: Cannot detect VCS
[DEBUG]	Unlocking https-golang.org-x-net-html-charset
[DEBUG]	Locking https-gopkg.in-xmlpath.v2
[INFO]	--> Fetching updates for gopkg.in/xmlpath.v2.
[DEBUG]	Unlocking https-gopkg.in-vmihailenco-msgpack.v2
[DEBUG]	Locking https-rsc.io-letsencrypt
[INFO]	--> Fetching updates for rsc.io/letsencrypt.
[DEBUG]	Unlocking https-gopkg.in-mgo.v2
[DEBUG]	Unlocking https-gopkg.in-xmlpath.v2
[DEBUG]	Unlocking https-rsc.io-letsencrypt
[DEBUG]	Unlocking https-github.com-gorilla-context
[DEBUG]	Unlocking https-github.com-TykTechnologies-leakybucket
[DEBUG]	Unlocking https-github.com-TykTechnologies-openid2go
[DEBUG]	Unlocking https-github.com-clbanning-mxj
[DEBUG]	Unlocking https-github.com-TykTechnologies-goverify
[DEBUG]	Unlocking https-github.com-kelseyhightower-envconfig
[DEBUG]	Unlocking https-github.com-mavricknz-ldap
[DEBUG]	Unlocking https-github.com-oschwald-maxminddb-golang
[DEBUG]	Unlocking https-github.com-rubyist-circuitbreaker
[DEBUG]	Unlocking https-google.golang.org-grpc
[DEBUG]	Unlocking https-github.com-lonelycode-gabs
[DEBUG]	Unlocking https-github.com-lonelycode-osin
[DEBUG]	Unlocking https-github.com-pmylund-go-cache
[DEBUG]	Unlocking https-github.com-lonelycode-gorpc
[DEBUG]	Unlocking https-github.com-robertkrimen-otto
[DEBUG]	Unlocking https-github.com-TykTechnologies-tykcommon
[DEBUG]	Unlocking https-github.com-rcrowley-goagain
[ERROR]	Failed to do initial checkout of config: Cannot detect VCS
Cannot detect VCS
Cannot detect VCS

**Comment by sdboyer** [comment]
Please file a proper bug report.
