### ISSUE TITLE
 Failed to connect to go.googlesource.com port 443: Connection timed out

### ISSUE THREAD

**Issue by penhauer-xiao** [Masterminds/glide#677]
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Unable to get repository
[DEBUG]	Output was: Cloning into '/home/kent/.glide/cache/src/https-golang.org-x-net'...
fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Connection timed out[DEBUG]	Unlocking https-golang.org-x-net
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Unable to get repository
[DEBUG]	Output was: Cloning into '/home/kent/.glide/cache/src/https-golang.org-x-crypto'...
fatal: unable to access 'https://go.googlesource.com/crypto/': Failed to connect to go.googlesource.com port 443: Connection timed out[DEBUG]	Unlocking https-golang.org-x-crypto
[ERROR]	Failed to do initial checkout of config: Unable to get repository
Unable to get repository

**Comment by sdboyer** [comment]
Possibly an issue with the Chinese firewall? #449

**Comment by penhauer-xiao** [comment]
You are right. :)

**Comment by zhucan** [comment]
how to slove it?

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/126972907-49bd04e4-555d-4ae8-9075-40ec155a2b11.png)
But I can ping google.

**Comment by huixisheng** [comment]
1. add content into ~/.zshrc

```
export http_proxy=http://127.0.0.1:1087
export https_proxy=http://127.0.0.1:1087
export ALL_PROXY=socks5://127.0.0.1:1086
```
2. source ~/.zshrc

**Comment by bamboo-cp3** [comment]
> Possibly an issue with the Chinese firewall? #449
shide

**Comment by lt421** [comment]
i encounter the same problem,if you use something to cross the Great FireWall my solution is add proxy to git.
```
git config --global http.proxy "localhost:1080"
```
