### ISSUE TITLE
Glide does not play well with GVM

### ISSUE THREAD

**Issue by Taik** [Masterminds/glide#68]
I'm currently using GVM to switch between go versions on my machine, and am trying to convert an existing Godep project over to using vendor with Glide.

When doing `glide up --import godep`, it spits out this error:

```
$ glide up --import godeps
[ERROR] Could not find /Users/thinhnguyen/.gvm/pkgsets/go1.5/dev:/Users/thinhnguyen/.gvm/pkgsets/go1.5/global/src.
[INFO] As of Glide 0.5/Go 1.5, this is required.
Oops! stat /Users/thinhnguyen/.gvm/pkgsets/go1.5/dev:/Users/thinhnguyen/.gvm/pkgsets/go1.5/global/src: no such file or directory
```

Here're my GOPATH and GOROOT, set by GVM:

```
$ echo $GOPATH
/Users/thinhnguyen/.gvm/pkgsets/go1.5/dev:/Users/thinhnguyen/.gvm/pkgsets/go1.5/global
$ echo $GOROOT
/Users/thinhnguyen/.gvm/gos/go1.5
```

Any help would be appreciated. Thanks!

**Comment by mattfarina** [comment]
I think I see the issue. In our handling of the `GOPATH` we expect it to be a single path rather than a list of paths separated by a `:`.

You can see an example of how the Go build tool deals with it at https://github.com/golang/go/blob/91976aa676706d579331cb34090550e44f4505df/src/cmd/doc/main.go#L266

**Comment by mattfarina** [comment]
We have an idea for a fix. What would happen if we just assumed the first path found in the `GOPATH`?

**Comment by technosophos** [comment]
Okay, so here's what I did:

- Added support for multiple Gopaths
- When I had to choose one particular path before doing something, I pick the first
- When trying to resolve where something is, I scan paths until I find one that looks like a match.

@Taik If you can, please try against `master` and see if this meets your needs. There are some cases where I'm really not sure what the right action is, so some input would help a lot.

**Comment by Taik** [comment]
Thanks guys for the quick fix; It seems to be working now. I'll play around with this for a few days and see if anything else comes up.

**Comment by technosophos** [comment]
Great! We're going to go ahead with today's release and include this fix. For now I'll close this issue. But please open a new one if you run into additional problems.
