### ISSUE TITLE
why having two different config files for vendoring?

### ISSUE THREAD

**Issue by xh3b4sd** [Masterminds/glide#684]
I am wondering why there need to be two different files to make glide work. IMO there should only be one. Beyond that I would love to have this single file in the `vendor` directory and not in the project root. This is kind of cosmetic but maybe there are similar or other opinions I would all like to hear.

**Comment by sdboyer** [comment]
there don't strictly _need_ to be two files - it would be possible to hold all the information in a single file. but they hold very different types of information, and so, we keep them in two files.

note that the two-vs.-one file debate, as well as whether to keep the files under vendor or at the project root, are extraordinarily well-traveled territory in the general discussions of go package management. you may find the [design space doc](https://docs.google.com/document/d/1TpQlQYovCoX9FkpgsoxzdvZplghudHAiQOame30A-v8/edit#), put together by the pkg mgmt committee, informative. the [tool spec doc](https://docs.google.com/document/d/1qnmjwfMmvSCDaY4jxPmLAccaaUI5FfySNE90gB0pTKQ/edit#heading=h.4d61hnb1y8gc) (where we settled on two files at the repo root, like glide) may also be informative.

**Comment by xh3b4sd** [comment]
Thanks for your feedback.
