### ISSUE TITLE
Retaining .git folders inside the vender repos

### ISSUE THREAD

**Issue by deepakprabhakara** [Masterminds/glide#687]
I updated glide and realised that the .git folder are now cleaned up from the vendor directories. Is there a command line option that will allow me to retain it? It is much easier to manage development on the vendored repos if they appear as git repos instead of just plain directories and files.

I currently have to manually remove the vendor repo, git clone the repo in it's place, makes changes and commit, run glide up again and repeat for every change I need to make in the vendor repos.

There's probably not many people who use this model but would be useful to have it through an option if possible.

Thanks.

**Comment by sdboyer** [comment]
sorry, but it's not feasible to return to the model of having the `.git` dirs (or other vcses) present under `vendor/`.

we realize that this does hamper the multi-project development case, and are working on more comprehensive solutions. in the meantime, you might be interested to have a look at the discussions in #548 - they've got some scripts going there, at least.
