### ISSUE TITLE
Add a `glide install --no-cache` option to install without filling caches

### ISSUE THREAD

**Issue by stevenroose** [Masterminds/glide#692]
Especially for usage in Docker containers, this is really helpful.

**Comment by sdboyer** [comment]
this would be a *lot* of work.

"cache" isn't really the best word to describe the behavior of that subsystem, but it's close enough and it's in the right ballpark, so we use it. in fact, it's more like a scratch/workspace for the tool. it's not a simple matter to bypass.

...which isn't a "no" to this, or saying this is impossible. just, please don't think it's as easy as bypassing a cache might be in other circumstances 😸

**Comment by stevenroose** [comment]
Wouldn't this be as easy as pointing the cache temporarily to somewhere in
`/tmp` and clean it up afterwards?

**Comment by sdboyer** [comment]
If that's an acceptable solution for your case, then you can achieve the same effect today with the `--home` parameter. The cache dir is always a subdir of the homedir. (sorry, I realize this isn't documented directly)

**Comment by stevenroose** [comment]
@sdboyer well, in fact the main usage of a --no-cache option is to not have to run `glide cc` afterwards :p

So consider this no longer a concrete request, just the believe that it should be possible to use Glide without leaving traces.

**Comment by sdboyer** [comment]
Ahhhh ok, i was imagining the goal to be that it not *use* the intermediary scratch space at all. If it's sufficient to just clean up the space it uses when it's done, then that's very different.

still, idk about an option for it (@mattfarina thoughts?), but hey, at least i understand the goal.

**Comment by stevenroose** [comment]
Yeah in docker containers you want to minimize the FS. That's why you also
remove your package dependencies after installs and use Alpine instead of
Ubuntu images. But it's nowhere near to important. I just thought it would
be a useful feature. Maybe an `--clear-cache` that clears the cache after
the install should even be all-right. In all honesty it's not more than not
wanting to do `glide cc` afterwards :)

**Comment by sdboyer** [comment]
seems like probably safe to close this, then :)
