### ISSUE TITLE
`glide {get,install,update}` breaks `vendor` submodule

### ISSUE THREAD

**Issue by dt** [Masterminds/glide#697]
In our vendor workflow, we opted to make `vendor` a submodule, so we'd get the benefits of _checking in_ deps (e.g. maintaining distribution, reproducibility, etc) without adding the actual content of dep changes to our main repo history (our `vendor` is ~200mb right now).

However, glide _replaces_ the `vendor` directory with a newly built one after every operation, which has the side effect of deleting the `vendor/.git` submodule pointer.

Our current [workaround](https://github.com/cockroachdb/cockroach/blob/master/scripts/glide.sh) is to just move `.git` aside and replace it after.

**Comment by sdboyer** [comment]
We've had a few issues raised about the underlying issue here (recreating the vendor dir in its entirety, every time). Handling this particular case might not actually be that bad, though. Lemme see...
