### ISSUE TITLE
fetched dependencies missing content of their submodules

### ISSUE THREAD

**Issue by dt** [Masterminds/glide#698]
Demo repo here:
https://github.com/dt/glide-fetch-submodule

Essentially, `github.com/dt/subparentdemo` is a little demo library that uses a git submodule for one of its internal libraries.

When glide fetches `subparentdemo` it doesn't fetch its submodule `subdemo` so that subpackage, which `subparentdemo` depends on, is missing.

**Comment by sdboyer** [comment]
Yeah, I think it's pretty unequivocal that we have to do this. All the git handling needs to be made recursive.

That's more or less easy for clones and fetches, but I'm concerned about how it's going to affect our checkout logic for within the installer.

gps suffers from this same issue.

**Comment by dt** [comment]
fwiw, `gvt` and `govendor` appear to have the same issue, e.g. https://github.com/FiloSottile/gvt/issues/81

**Comment by sdboyer** [comment]
well i think those fixes in Masterminds/vcs should do it

**Comment by alexanderbez** [comment]
Is there a resolution on this? I'm facing a similar issue with one of my packages rendering the pkg unusable. 

```
$ glide --version
glide version 0.12.3
```

**Comment by dt** [comment]
@alexanderbez deps that include submodules seem to be handled correctly, at least in my usage, since #748 (though that isn't in a "release" yet AFAIK).

**Comment by alexanderbez** [comment]
Ahhh thanks @dt. Seems you're right -- looks like the last release was on Oct 3, 2016.I take it'll be in the next release then?

Just curious, how did you use the latest from `master` then? Just building locally?

**Comment by dt** [comment]
@alexanderbez a  simple `go get -u gitHub.com/Masterminds/glide` should do the trick. If you want to get fancy, I vendor glide along with everything else though and then just `go install ./vendor/github.com/Masterminds/glide` along with other dev tools.

**Comment by alexanderbez** [comment]
Awesome. Thanks @dt. This ticket should be closed then I suppose.
