### ISSUE TITLE
glide install deletes packages under ignore directive in vendor directory

### ISSUE THREAD

**Issue by ganesh-karthick** [Masterminds/glide#701]
Packages which are placed under vendor directory, for example abc ( in the below yaml file)  gets deleted on running glide install 

glide.yaml

```
package: xyz
ignore:
- abc/proto
```

version 0.12.3

**Comment by sdboyer** [comment]
Sorry, but this is working as intended. `ignore` in `glide.yaml` is about ignoring packages during analysis, not about the behavior of how packages are installed into vendor. As of 0.12.0, glide does not attempt to maintain any state that it does not create itself in `vendor/`. See #579.
