### ISSUE TITLE
glide up should just read glide.yaml, not read all my imports

### ISSUE THREAD

**Issue by treeder** [Masterminds/glide#713]
I was unable to do a glide up because it would error saying that an import package doesn't exist, even though that package wasn't in my glide.yaml. I wanted to fix the import (which was moved) after I got the latest dependencies which have the new import location. I even deleted glide.lock and the glide cache. The only way to get this to work was to remove the import, do the glide up, then add the import back.

**Comment by sdboyer** [comment]
Sorry, but this is an explicit design choice, and it's here to stay. See #249 for protracted discussion.

I'm not sure if the current `ignore` directive would address your problem (you could `ignore` the package with the problem import, even if temporarily), but it's worth a shot.
