### ISSUE TITLE
Guidance needed: glide setup leaves kubernetes broken

### ISSUE THREAD

**Issue by thockin** [Masterminds/glide#714]
I am trying glide against kubernetes again.

`glide init` processes my Godep state.

`glide install` fetches all my deps into vendor.  It pulls a LOT more files than Godep does.  If I recall it's because godep prunes the tree to just dirs that are needed, yes?

We're starting to use `bazel`, so I run the bazel update script, which walks the codebase and checks BUILD files.  It throws a bazillion errors for missing code.  It turns out that there are hundreds of deps that are only referenced by those files that Godep didn't import, but glide does.

So now what?  Do I import literally hundreds of deps (megabytes of code) that I don't need?  Do I do it one-by-one manually?  Is there another option?

**Comment by thockin** [comment]
@mikedanese FYI

**Comment by sdboyer** [comment]
@thockin https://github.com/sgotti/glide-vc may strip them out for you.

sorry we haven't progressed further, here. my obligations on the pkg mgmt committee have taken a lot of the time that might otherwise have gone towards getting a gps-based glide finished, unfortunately :(

**Comment by thockin** [comment]
NP, I was just trying it, to see where things were.  I'll catch up with Jess
