### ISSUE TITLE
不支持win系统么？

### ISSUE THREAD

**Issue by xwinie** [Masterminds/glide#719]
不支持win os？

**Comment by sdboyer** [comment]
Sorry, but none of the glide folks know Chinese (afaik) - english, please?

**Comment by sdboyer** [comment]
though if the question was "does glide work on win os" (just guessing), the answer is "yes, it should"

**Comment by qindj** [comment]
@sdboyer
yes, you are right ,the question is " does glide work on windows?"

@xwinie
Glide可以很好的在windows下工作，在release页面有win64/32的bin包，下载解压即可

**Comment by sdboyer** [comment]
thanks, @qindj!
