### ISSUE TITLE
glide: gives spurious warnings when a non-release go version is used.

### ISSUE THREAD

**Issue by kardianos** [Masterminds/glide#72]
Rather then looking at "go version" (I assume) might want to check what the results of `go tool compile` returns, look for option "-importmap". Or just be silent if you see `go version` with a developer tag (example here) `go version devel +0cd2999 Fri Aug 7 05:52:11 2015 +0000 linux/amd64`

**Comment by technosophos** [comment]
That was my mistake. I had that messaging in there from the pre-0.5 release.

**Comment by technosophos** [comment]
The exact line that is causing the problem is right here:
https://github.com/Masterminds/glide/blob/master/cmd/util.go#L43
