### ISSUE TITLE
cannot find package "github.com/json-iterator/go" 

### ISSUE THREAD

**Issue by wuhuanhost** [Masterminds/glide#724]
### go env info
---

set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\study-go\
set GORACE=
set GOROOT=D:\Program Files\go
set GOTOOLDIR=D:\Program Files\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

---

### test.go
```go
package main
import "fmt"
/*json*/
import "github.com/json-iterator/go"
func main(){
  iter := jsoniter.ParseString(`[0,1,2,3]`)
  val := []int{}
  iter.Read(&val)
  fmt.Println(val[3])
}
```

### project structure

```
- e:\study-go/src
  |
  |-- glide.yaml
  |
  |-- glide.lock
  |
  |-- test.go 
  |
  |-- vendor
       |-- github.com
            |
            |-- json-iterator
                  |
                  |--go
                         |
                         |--......
```

### why run `go run test.go` throw error?
```
test.go:4:8: cannot find package "github.com/json-iterator/go" in any of:
        D:\Program Files\go\src\github.com\json-iterator\go (from $GOROOT)
        E:\study-go\src\github.com\json-iterator\go (from $GOPATH)
```

**Comment by franciscocpg** [comment]
hi @wuhuanhost 
Your question is more about `go` than `glide`.
Your project structure is strange, you cannot have a project on the $GOPATH/src root.
I recommend you reading [this](https://golang.org/doc/code.html#Command)

**Comment by wuhuanhost** [comment]
thank you very much.
this problem has been solved!

**Comment by franciscocpg** [comment]
That's nice @wuhuanhost 
Could you please close the issue?
