### ISSUE TITLE
gocode not work

### ISSUE THREAD

**Issue by deweixu** [Masterminds/glide#725]
gocode not work

**Comment by sdboyer** [comment]
> Using glide in vscode

I don't know what it means to "use glide in vscode." Please clarify.

> can`t complete dependency code

No idea what this means.

**Comment by deweixu** [comment]
@sdboyer gocode not work

**Comment by sdboyer** [comment]
If gocode doesn't work, it's because it's not reading properly from the vendor directory, which isn't a glide issue.

I realize there's a language barrier here, and I'm sorry, but I really can't do more without a real bug report.
