### ISSUE TITLE
How do I tell glide to always pick the latest commit from my fork? 

### ISSUE THREAD

**Issue by TamalSaha** [Masterminds/glide#726]
Hi,
I have a repo https://github.com/appscode/lego which is a fork of https://github.com/xenolf/lego. I would like some other repo of mine to always use the latest commit from master branch of my fork? Currently I do something like below:
```
- package: github.com/xenolf/lego
  repo: git@github.com:appscode/lego.git
  vcs: git
  version: {commit_hash}
```
Is it possible to tell glide always pick the latest commit from my fork without specifying the commit_hash as version?

**Comment by franciscocpg** [comment]
`version: master`
But you have to run `glide cc` to clean up the cache and `glide up` to update the `glide.lock` file

**Comment by TamalSaha** [comment]
Thank @franciscocpg
