### ISSUE TITLE
Sudden problem with glide install

### ISSUE THREAD

**Issue by argentum47** [Masterminds/glide#732]
I am trying to do glide install in mac osx, I get these errors:

```
[ERROR]	Failed to set version on github.com/DATA-DOG/godog to 2e189ad0f9dee046e42bb5f04a7ec5e91ec0700e: Unable to update checked out version

[ERROR]	Failed to set version on github.com/mitchellh/mapstructure to f3009df150dadf309fdee4a54ed65c124afad715: Unable to update checked out version
```

How to fix it? I deleted everything in GO_PATH and restarted the system and re-fetched the project, ran glide install and it still fails.

**Comment by franciscocpg** [comment]
@argentum47 
Which glide version are you using?
Could you run `glide --debug i` and post the output here?

**Comment by franciscocpg** [comment]
and if possible your `glide.yaml`

**Comment by argentum47** [comment]
Will do on Monday . :)  Using the latest version .. because I did the reinstall to see if it was version problem .. but will check to make sure

**Comment by argentum47** [comment]
Hey @franciscocpg thanks for the --debug tip, this was the problem:

```
[ERROR]	Failed to set version on github.com/garyburd/redigo to 8873b2f1995f59d4bcdd2b0dc9858e2cb9bf0c13: Unable to update checked out version

[DEBUG]	Output was: fatal: Unable to create '/Users/alex/.glide/cache/src/https-github.com-garyburd-redigo/.git/index.lock': File exists.
```

so I `rm -rf` ed `cache/src` and it works now.

**Comment by franciscocpg** [comment]
:+1: 
Maybe `glide cache-clear` would had helped you too.

**Comment by franciscocpg** [comment]
Could you close this issue then?
