### ISSUE TITLE
Install on linux (fedora) through sh.

### ISSUE THREAD

**Issue by aymone** [Masterminds/glide#734]
Error on install:
```
$ curl https://glide.sh/get | sh
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3241  100  3241    0     0   2376      0  0:00:01  0:00:01 --:--:--  2376
Downloading https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0    581      0 --:--:--  0:00:01 --:--:--   581
100 3344k  100 3344k    0     0   256k      0  0:00:13  0:00:13 --:--:--  414k
which: no glide in (/home/marceloaymone/.nvm/versions/node/v4.4.4/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/marceloaymone/bin:/usr/local/go/bin:
/usr/local/go/bin)
glide not found. Did you add $LGOBIN to your $PATH?
Fail to install glide

The official go doc have no mentions about "$LGOBIN"...

**Comment by franciscocpg** [comment]
@aymone 
Did you set `GOBIN` env variable?
Also did you add `$GOBIN` to your `PATH`?

**Comment by aymone** [comment]
@franciscocpg 
So $LGOBIN is the same as $GOBIN? I will try....

**Comment by franciscocpg** [comment]
To be honest I don't know why @mattfarina named it as `LGOBIN` in the script. But yes, considere it the same

**Comment by franciscocpg** [comment]
@aymone 
Could you share your solution please?

**Comment by aymone** [comment]
I have used $GOBIN...

**Comment by nielsole** [comment]
I guess this could be more clear. For anyone getting to this problem, glide is likely installed correctly, but the directory is not part of your `$PATH`. It probably is `$GOPATH/bin`. So you can either run glide directly from `$GOPATH/bin/glide` or add the directory to your path.

**Comment by unsystemizer** [comment]
` $GOPATH/bin/glide install` works for me (Ubuntu 16). That variable name should be changed.

**Comment by wolfstudy** [comment]
export  GOBIN:$GOROOT/bin

**Comment by lostinblue** [comment]
For me, because I use a directory structure local to the project

    export PATH=$(pwd)/bin:$PATH

**Comment by Yugloocamai** [comment]
I keep having this issue over and over.  Drives me crazy.  Not clear at all.

**Comment by z0ph** [comment]
Just added "$GOPATH/bin" in my .bash_profile. Its working like a charms. Thanks

**Comment by nielsole** [comment]
In https://glide.sh/get
```
echo "$PROJECT_NAME not found. Did you add "'$LGOBIN'" to your "'$PATH?'
```
Should probably be 
```
echo "$PROJECT_NAME not found. Did you add $LGOBIN to your "'$PATH?'
```
Because nobody looks at the script and knows what $LGOBIN is. If it would just display the path it would probably be easier to understand that you need to add your $GOPATH/bin to your PATH

**Comment by nielsole** [comment]
https://github.com/Masterminds/glide.sh/pull/18

**Comment by eiawilk** [comment]
I am having exactly the same problem and can not get Glide to install.  My Bash profile has these entries:   PATH=$PATH:$HOME/bin

export PATH

export GOBIN="$HOME/projects/bin"
export GOPATH="$HOME/projects/src"
export PATH=$GOPATH:/usr/local/go/bin
export PATH=$GOBIN:/usr/local/go/bin
export PATH=$LGOBIN:/usr/local/go/bin
export PATH=$PATH:/home/ec2-user/.nvm/versions/node/v6.8.0/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/go/bin

**Comment by eiawilk** [comment]
Also in /etc/profile.d.path.sh I have these:  export PATH=$GOPATH:/usr/local/go/bin
export PATH=$GOBIN:/usr/local/go/bin
export PATH=$LGOBIN:/usr/local/go/bin
export PATH=$PATH:/home/ec2-user/.nvm/versions/node/v6.8.0/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/go/bin

**Comment by eiawilk** [comment]
Ikeep getting the error   "glide not found. Did you add $LGOBIN to your $PATH?"  but I have no idea where to put this $LGOBIN variable.  Anyone any ideas?

**Comment by nielsole** [comment]
https://github.com/Masterminds/glide/issues/734#issuecomment-295189885

**Comment by mattfarina** [comment]
`$LGOBIN` is an internal variable name. That should not have been exposed in the messaging. I fixed that.

The shell script uses `which` to find the application. If `which` doesn't find it the message is displayed.
