### ISSUE TITLE
How to support http://gopkg.in/mgo.v2 ( not https)

### ISSUE THREAD

**Issue by penhauer-xiao** [Masterminds/glide#737]
Because the gopkg.in times out with HTTPS access,  so access it with http is ok, but the glide don't support.

$ git ls-remote http://gopkg.in/mgo.v2  
3f83fa5005286a7fe593b055f0d7771a7dce4655	HEAD
3f83fa5005286a7fe593b055f0d7771a7dce4655	refs/heads/master
c91e44ec198183371f67220d4e3ee563ee5cc10f	refs/pull/97/head
d3ff508e020127390aad8e6abf3311345fe8da78	refs/pull/97/merge
e5d775ad02fa2dfc96d4a4cc91d2938d49bdd4c3	refs/pull/99/head
d8f5b176c5cb051ec61b5f7106b35526a7375dce	refs/tags/go.2011-08-17
d8f5b176c5cb051ec61b5f7106b35526a7375dce	refs/tags/go.r59
dcd742c64912694716517bfb7141283d02d76384	refs/tags/go.r60
3f4829794e873359609f558cc21445145da54796	refs/tags/go.weekly.2011-12-14
60e3fb2629f6f12661c0737b219b1bd881cbc3d2	refs/tags/go.weekly.2012-01-20
447d0e2e62baa0b44fa26c105b176672a88de215	refs/tags/r2011-03-15
e4bd393b94ffd3a26813cfe74569af4d57e7c5dc	refs/tags/r2011-03-17
6c68d933922c946a26f9796c3dd29e7e96021fb4	refs/tags/r2011-03-20
1fd865ee346ed909725b1a5138a033b6dfc2e705	refs/tags/r2011-03-24
447d0e2e62baa0b44fa26c105b176672a88de215	refs/tags/r2011.03.15
e4bd393b94ffd3a26813cfe74569af4d57e7c5dc	refs/tags/r2011.03.17
6c68d933922c946a26f9796c3dd29e7e96021fb4	refs/tags/r2011.03.20
1fd865ee346ed909725b1a5138a033b6dfc2e705	refs/tags/r2011.03.24
2c4c03eedadcffcc4f1884ac7c343cd8727b1fc1	refs/tags/r2011.04.09
1fa0d41f2deb3ec0fd73dde2b6b93919da5f8080	refs/tags/r2011.04.13
8856b721b1b3c7f66e1f86384b5c6478a93887a7	refs/tags/r2011.04.19
5284467e72033c936abaf3624dc9da532ed83e59	refs/tags/r2011.04.24
45b249cb231488859b5fa2a7de52ac1d07c60c2b	refs/tags/r2011.04.28
50b7d712aee1b3a874929a07e22d02e416c190f7	refs/tags/r2011.05.12
bac454ccffeec8485e770a6e3d9095ac41f6789c	refs/tags/r2011.05.24
819c5251834521bd0ab304aee127ffc3dcd63636	refs/tags/r2011.06.24
955f9645b41aad079aba67c8d22a0284507dad82	refs/tags/r2011.07.15
4ac916566d5b7e41c27f5f4a20f6c2f8bc2dcf28	refs/tags/r2011.07.28
49ea3870e84e003045e5ad0721f3665ad43cda1d	refs/tags/r2011.08.02
d8f5b176c5cb051ec61b5f7106b35526a7375dce	refs/tags/r2011.08.21
9a87d973f95fa19487f8293730e73792a3d63778	refs/tags/r2011.09.15
aeecf000f12161500c20b44c253cab9c01449497	refs/tags/r2011.10.29
dcd742c64912694716517bfb7141283d02d76384	refs/tags/r2011.12.18
a4033b400eedcf2961c43d05a766b872274b659b	refs/tags/r2012.01.22
41512ec3abf54c189f495f7783a91f24411cf457	refs/tags/r2012.02.02
f13bea7d47b0e33e977c5266274381ff544417e4	refs/tags/r2012.03.04
25d859ee5cf9d5a4f331b41f3f5f55a60981b1de	refs/tags/r2012.04.08
1227e67c223d2cc895a26fdad17d81b925c08eab	refs/tags/r2012.05.21
44dcc642bb0878687fdafede04b052e24b92e9f6	refs/tags/r2012.06.22
6891649c6058bd9d9673fa3a26f228b14c084c81	refs/tags/r2012.08.07
4927bc5b144fe41be53806725ca8e2a0deabfea5	refs/tags/r2012.08.22
b48af10f9077becfc8a16858f81010779a1d8db0	refs/tags/r2012.08.23
ecc5141140853a61cfc3b42c52a10088f77a77e6	refs/tags/r2012.09.05
9fe1bd153017197d70c1b67bfcd8a778eed9fd96	refs/tags/r2012.10.04
3cc10a22ab9009f75d734e99d0ee5a3c2c0148b5	refs/tags/r2012.10.28
39723d9d045fb83fa241ee5cdc474472dd4b1783	refs/tags/r2013.01.20
ad9402baa229c5a791d63a45197e1a60f290865f	refs/tags/r2013.04.05
0db23adb3ff3f570149d7ac9c42e75e05bc854d8	refs/tags/r2013.04.11
1ed4068c77793fa29cff7809424f8863ac8c6541	refs/tags/r2013.05.19
d1c9089508537c1d8841c91cc31282433df462ee	refs/tags/r2013.07.21
15571ea624ced126e8e56ead0b9f772b3d514d1a	refs/tags/r2013.09.04
bb07d904984913eb3bec4e72586624c6f2e027e1	refs/tags/r2013.11.18
121e4ef93103097b8f2940cd8a6c43527503b800	refs/tags/r2014.01.25
ad99486d2d1583175c6e6579fe12792d1f76ebba	refs/tags/r2014.03.12
3116f72d0fe0216b75201cb3a1ae61c82c2a4d63	refs/tags/r2014.07.21
231ce7e0549b5ce60d35ed805bff505cab7098e4	refs/tags/r2014.10.12
c6a7dce14133ccac2dcac3793f1d6e2ef048503a	refs/tags/r2015.01.24
01ee097136da162d1dd3c9b44fbdf3abf4fd6552	refs/tags/r2015.05.29
3f8090ae6a04fa37c3f8299c62ed27b192835e73	refs/tags/r2015.06.03
f402e3a216db333ae6b3ba68b9152a34a0bc6984	refs/tags/r2015.10.05
e30de8ac9ae3b30df7065f766c71f88bba7d4e49	refs/tags/r2015.12.06
d90005c5262a3463800497ea5a89aed5fe22c886	refs/tags/r2016.02.04
b6121c6199b7beecde08e6853f256a6475fe8031	refs/tags/r2016.08.01

**Comment by penhauer-xiao** [comment]
I look at the source code, it is only supported tags/v1.1.2 similar to the beginning of the tags, how to support tags/r2013.11.18

**Comment by sdboyer** [comment]
First, I have no problem interacting with `https://gopkg.in/mgo.v2`, whether directly via git, or with curl, or via glide. Perhaps the timeout you had was a transient issue?

If you want to force glide to use http, use `repo: http://gopkg.in/mgo.v2` in `glide.yaml`.

If you want to specify a version in that list, it doesn't need to conform to semver. Just specify the string name of the tag - e.g. `r2013.11.18` in the `version` field in `glide.yaml`.

Both of these are [in the docs](https://glide.readthedocs.org/en/latest/glide.yaml/).
