### ISSUE TITLE
Issue installing glide on Travis

### ISSUE THREAD

**Issue by kalbasit** [Masterminds/glide#750]
In a `.travis.yml` I have the following:

```yml
before_install:
  # Install Glide
  - mkdir -p "${GOPATH}/bin"
  - curl https://glide.sh/get | bash
```

This works most of the time, but it fails sometimes as it cannot find a distribution that matches the OS, which is not true as I can see them in the release page. log:

```shell
$ mkdir -p "${GOPATH}/bin"

$ curl https://glide.sh/get | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3241  100  3241    0     0  14222      0 --:--:-- --:--:-- --:--:-- 16968
Sorry, we dont have a dist for your system: linux amd64
You can ask one here: https://github.com/Masterminds/glide/issues
Fail to install glide


The command "curl https://glide.sh/get | bash" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by kalbasit** [comment]
UPDATE: The only fix is to retry, so it happens randomly but often.

**Comment by franciscocpg** [comment]
Duplicated
https://github.com/Masterminds/glide/issues/708
https://github.com/Masterminds/glide/issues/639

Possibles workarounds
https://github.com/Masterminds/glide/issues/639#issuecomment-255097289
https://github.com/Masterminds/glide/issues/639#issuecomment-257431434

**Comment by franciscocpg** [comment]
And possible solution
https://github.com/Masterminds/glide/issues/639#issuecomment-255095785
with
https://github.com/Masterminds/glide.sh/pull/10

**Comment by kalbasit** [comment]
Thanks for the info @franciscocpg, I'll close this one out as a duplicate for now. @technosophos you should probably move the files out of Github. I'm happy to donate an S3 bucket, let me know if this is something you would consider.
