### ISSUE TITLE
Glide requires $GOPATH, but Go 1.8 doesn't

### ISSUE THREAD

**Issue by treeder** [Masterminds/glide#771]
Glide should use the default of $HOME/go if not set.

**Comment by mattfarina** [comment]
I wonder if we could use `go env GOPATH` if the `GOPATH` env var is empty. That may give us the right result.

**Comment by jmalloc** [comment]
I am using `go env` in Makefiles for similar reasons, and can confirm that it gives the correct results under 1.8 when `$GOPATH` is not set :)

**Comment by mattfarina** [comment]
There's a PR for this on #798

**Comment by comerc** [comment]
```
$ glide install
[ERROR]	$GOPATH is not set.

$ glide -v
glide version v0.12.3

go version go1.8.3 linux/amd64

Ubuntu 14.04.5 LTS
```
