### ISSUE TITLE
How should we handle ref being removed?

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#78]
Right now if `ref` is set for an import it checks that out. If `ref` is removed rather than being switched to something else no action is taken. So, nothing is recorded and the repo stays with the previous `ref` value.

Should we:
1. Keep the current behavior?
2. Switch back to a sane default (e.g., the master branch in git)
3. Display a message to the user if no `ref` is specified and they are in a detached head state.
4. Something else???

Many other systems work a little differently so they don't run into this case. For example, for composer and npm you always specify some form of version information.

**Comment by technosophos** [comment]
I would say that no ref means "checkout the latest"

**Comment by itsjamie** [comment]
If there is no version information then I would say checkout the "sane" default.

If there is a ref, and the checkout fails, this should definitely toss an error and not silently checkout the default.

**Comment by mattfarina** [comment]
@itsjamie if the ref can't be checked out it will, today, provide an error. We don't silently fail.

**Comment by itsjamie** [comment]
@mattfarina I wasn't sure what the current behaviour was, thanks for clearer that up. 

Thanks by the way, it was super easy to convert from Godeps to Glide, I was very pleased, you also solved the issue we worked around with git config settings for HTTP based `go get` with the repo setting. Loving it so far, thanks!

**Comment by mattfarina** [comment]
The latest codebase now takes no ref as being either the latest (svn) or the tip of the default branch.
