### ISSUE TITLE
Issue add logrus package

### ISSUE THREAD

**Issue by jaxxstorm** [Masterminds/glide#781]
I'm trying to add the logrus package using glide. I used the following in my code:

```
import (
  log "github.com/sirupsen/logrus"
)
```

Then, when I run `glide up`

```
[INFO]	--> Fetching updates for github.com/sirupsen/logrus.
[ERROR]	Update failed for github.com/sirupsen/logrus: The Remote does not match the VCS endpoint
[ERROR]	Could not update packages: The Remote does not match the VCS endpoint
```

I haven't noticed a change in destination repo, I haven't seen anything on the logrus side that might cause this. It's the only package that seems to be affected.

Anything I can do here? How can I debug why this is happening?

**Comment by adam-cv** [comment]
Try using the `--force` command to re-add the logrus dependency:
```
glide update --force  or glide install -force
```

**Comment by jaxxstorm** [comment]
I figured this out.

It's a case sensitivity thing.

The original VCS endpoint for the logrus package is actually this: `github.com/Sirupsen/logrus`

That single uppercase letter was the problem. I changed my import to use the upper case letter and it worked.

**Comment by Carpetsmoker** [comment]
Note that the correct name, as of June 2017, is `sirupsen`, with a *lower* case `s`. The repository got moved.
