### ISSUE TITLE
glide get doesn't keep flatten in glide.yaml file

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#79]
To reproduce run `glide get github.com/Masterminds/convert` from the root of the glide repo and notice the change to the `glide.yaml` file. A flatten flag is removed.

**Comment by derekdowling** [comment]
I'm running 0.8.0 and just had this happen to me after running: `glide get github.com/my/dependency`

**Comment by mattfarina** [comment]
@derekdowling flattening is now automatic and doesn't need to be enabled for two reasons:

1. That's the recommendation from the Go team and those who've been working with the `GO15VENDOREXPERIMENT`.
2. If you won't flatten you can easily run into problems. [Here's an example](https://github.com/mattfarina/golang-broken-vendor).
