### ISSUE TITLE
Can not fetch submodule

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Masterminds/glide#793]
I can't fetch a package which has submodule. 

For example, this is a glide.yaml

```
package: cf-engine
import:
- package: github.com/Azure/azure-sdk-for-go
  version: ~9.0.0-beta
```
This repo has git submodule at storage directory. 
https://github.com/Azure/azure-sdk-for-go

However, when I tried `glide install` or `glide up`, the storage directory is still empty.
When I tried `go get  github.com/Azure/azure-sdk-for-go` then the directory is filled with go files.

I tried this via my Mac and Windows.

Mac

```
history:cf-engine ushio$ go version
go version go1.8 darwin/amd64
history:cf-engine ushio$ glide --version
glide version 0.12.3
```

Windows

```
go version go1.7.5 windows/amd64
glide --version
glide version v0.12.3
```

**Comment by vikstrous** [comment]
See https://github.com/Masterminds/glide/issues/749
