### ISSUE TITLE
Specific case failure on OSX

### ISSUE THREAD

**Issue by sysradium** [Masterminds/glide#799]
Glide fails to install a package if the repo in a cache contains uncommited changes.
This can easily happen actually if you use OSX. For example if the git repo contains a symlink `README.MD -> README.md` on OSX after a `git clone` you will immediately receive a:

```
typechange: README.MD
```

And glide will fail with:
```
[ERROR]	Failed to set version on github.com/mwitkow/go-grpc-middleware to 2b82014fe1a83cf1d9190e0e8c7447b47a3fd57e: Unable to update checked out version
```
I am not sure if glide can work this out by doing force checkout. So you can close the issue, but I hope if somebody faces the `Unable to update checked out version` he will know what to do. I had to go to the git repo in a cache folder, remove the typechanged file and commit that.

**Comment by mattfarina** [comment]
Can you point me to a project I can reproduce this with?

Note, the default filesystem on macOs is case insensitive. So, `README.md` and `README.MD` are the same file. Are you using something other than the default filesystem setup?

**Comment by sysradium** [comment]
That's exactly the case. Because on OSX it is case insensitive git reports that the file type changed, because `README.md` is a file and `README.MD` is a symlink to that file :) So it thinks that you switched from a symlink to file.

This way you get the unstaged change right after the `git clone` and glides fails to checkout the right commit.

As I mentioned I have no idea if it is possible to fix this adding some force flag so it ignores that unstaged stuff :)

**Comment by sysradium** [comment]
Well, this thing is dead.
