### ISSUE TITLE
glide in doesn't change GOPATH

### ISSUE THREAD

**Issue by Nitrino** [Masterminds/glide#8]
Doing everything according to the instructions

``` bash
$ glide create 
[WARN] If your GOPATH is automatically set by your shell, 'glide in' may not correctly set it.
[INFO] Your new GOPATH is /Users/Nitrino/work/Go/Metro/_vendor. Run 'glide gopath' to see it again.
[INFO] Initialized. You can now edit 'glide.yaml'

$ glide in                                                            
>> You are now gliding into a new shell. To exit, type 'exit'

$ open glide.yaml 

$ glide install 
[ERROR] For Glide to create a managed _vendor directory, you must set your GOPATH to /Users/Nitrino/work/Go/Metro/_vendor.
[INFO] You can use `glide in` to set GOPATH for you.
[INFO] If you are using an external GOPATH, skip to `glide update`.
Oops! GOPATH is /Users/Nitrino/go, but current directory is /Users/Nitrino/work/Go/Metro/_vendor

$ echo $GOPATH 
/Users/Nitrino/go

$ glide in 
[WARN] You're already gliding. Run `glide out` to stop your current glide.

$ glide gopath
/Users/Nitrino/work/Go/Metro/_vendor
```

My glide.yaml

``` yaml
package: main
import:
  - package: github.com/Nitrino/go-airbrake
  - package: github.com/facebookgo/httpcontrol
  - package: github.com/fiorix/go-web
  - package: github.com/garyburd/redigo
  - package: github.com/lib/pq
  - package: github.com/spacemonkeygo/errors
```

Environment: OS X 10.10

**Comment by JacekLach** [comment]
I know this is a very old thread; but FWIW, if you had something like `glide env` which prints out the entire env to be sourced, you could do something like:

```
echo 'source ~/.bashrc' > /tmp/glide-<project>
glide env >> /tmp/glide-<project>
bash --rcfile /tmp/glide-project
```

Drawback being this is shell-dependent (i.e. zsh has a different flag; `--rcs`; than bash, and you'd have to swap out ~/.bashrc for ~/.zshrc, etc). 

Perhaps just having `glide env` would be useful (so that people can `eval "$(glide env)"` if their rcfile does stuff to gopath/gobin) and less fragile.

**Comment by mattfarina** [comment]
@JacekLach given the way Go is headed on vendoring we may have a workaround by leveraging what will be optional in Go 1.5 and default in Go 1.6. We're investigating that now.

**Comment by technosophos** [comment]
@JacekLach Hmmm... that's an idea I hadn't thought about.

`glide gopath` prints out the value for GOPATH, which is probably all you'd really need. I wouldn't want to mess too much with people's env unless that was necessary. There's a tool called `envdir` that I think handles the shell generalization part. 

But what @mattfarina is talking about is the experimental feature in Go 1.5 that automatically includes the subdir `vendor/` in  a project's GOPATH. That'd mean Glide may not have to manage GOPATH at all. We have our fingers crossed that that works out.
