### ISSUE TITLE
glide tree and glide list does not exist

### ISSUE THREAD

**Issue by nii236** [Masterminds/glide#80]
I get the following output below. I'm currently on version 0.5.0:

```bash
$ glide tree
Oops! Command glide-tree does not exist.
$ glide list
Oops! Command glide-list does not exist.
```

**Comment by mattfarina** [comment]
@nii236 those are commands on the tip of master and will be in the 0.6.0 release out something in a matter of hours (hopefully). If you want to run the tip of master you can install glide with `go get github.com/Masterminds/glide` and use it from the same place other Go tools are installed.
