### ISSUE TITLE
How glide deal with such a project change its root structure?

### ISSUE THREAD

**Issue by zhexuany** [Masterminds/glide#808]
Say we have a golang project named `Foo` with following structure:
Foo:
 - Bar
 - Baz

One day I decided to delete `Bar`. Now the project `Foo` looks like 
Foo:
- Baz

The case I am experiencing now is that `glide` will think this as a dependency failure.  Anyway to improve this? 

If above example did not explain too well, the following is concrete example. Before 0.12, `influxdb` has `cluster` and did not have `coordinator`. After this release, `influxdb` delete `cluster` and add `coordinator`. How could I fix this? 
 ~~~
[ERROR]	Error scanning github.com/influxdata/influxdb/cluster: open /Users/zhexuany/.glide/cache/src/https-github.com-influxdata-influxdb/cluster: no such file or directory
[ERROR]	This error means the referenced package was not found.
[ERROR]	Missing file or directory errors usually occur when multiple packages
[ERROR]	share a common dependency and the first reference encountered by the scanner
[ERROR]	sets the version to one that does not contain a subpackage needed required
[ERROR]	by another package that uses the shared dependency. Try setting a
[ERROR]	version in your glide.yaml that works for all packages that share this
[ERROR]	dependency.
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
~~~

**Comment by kmcminn** [comment]
Just hit this today as well and it was a drag. Only workaround that comes to mind is to create a forked copy rebased to the commit you need.

**Comment by zhexuany** [comment]
closing this issue.
