### ISSUE TITLE
C is not recognized as an internal package

### ISSUE THREAD

**Issue by gdm85** [Masterminds/glide#82]
I am trying to convert an existing project to glide, however I got instantly stuck at this (with guess/tree):
```
C       (glide get C)
```

I don't think I can ``go get C`` from anywhere...

Maybe this is related to #76?

**Comment by mattfarina** [comment]
@gdm85 thanks for bringing this up. Can you share the details about your environment and how you installed glide? If you run `go env` it will give a bunch of useful details. The OS and install method are important. For example, if you are on Mac and installed go with the package install from golang.org it makes a difference compared to being installed with brew.

Also, what version of glide are you running (can get with `glide --version`)?

Note, the OS/install method issue (see in #76) is fixed on the tip of master. Just tying to diagnose what you're seeing.

**Comment by technosophos** [comment]
Hmm... I wonder if this is a special case. I don't think `C` is present in $GOROOT. From the Go docs:

```
The rand package imports "C", but you'll find there's no such package in the standard Go library. That's because C is a "pseudo-package", a special name interpreted by cgo as a reference to C's name space.
```

So I think I need to special-case this one in.

**Comment by technosophos** [comment]
If you have a moment to test `master`, I'd appreciate it. I added special handling for `C` to `glide guess`, 
`glide tree` and `glide list`.

**Comment by gdm85** [comment]
@technosophos I just got back, thanks for giving a look at this.

I've put glide in my GOPATH with ``go get``, so I am using master, however this is what I get:
```
[WARN] To use Glide, you must set GO15VENDOREXPERIMENT=1
.
	C   ()
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x48b6e5]

goroutine 1 [running]:
github.com/Masterminds/glide/cmd.excludeSubtree(0x0, 0x0, 0x0, 0x0, 0x614f67)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/cmd/tree.go:220 +0x65
github.com/Masterminds/glide/cmd.walkDeps.func1(0x0, 0x0, 0x0, 0x0, 0x7f84ab0c2668, 0xc8201f36e0, 0x0, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/cmd/tree.go:185 +0x93
path/filepath.Walk(0x0, 0x0, 0xc820104d28, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:394 +0xa5
github.com/Masterminds/glide/cmd.walkDeps(0xc82007dad0, 0x0, 0x0, 0xc8201e45d1, 0x1, 0x0, 0x0, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/cmd/tree.go:213 +0xc0
github.com/Masterminds/glide/cmd.displayTree(0xc82007dad0, 0x0, 0x0, 0xc8201e45d1, 0x1, 0x2, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/cmd/tree.go:99 +0x86
github.com/Masterminds/glide/cmd.displayTree(0xc82007dad0, 0xc82000a124, 0x1c, 0x8da348, 0x1, 0x1, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/cmd/tree.go:112 +0x659
github.com/Masterminds/glide/cmd.Tree(0x7f84ab0c2590, 0xc820130b40, 0xc820084260, 0x0, 0x0, 0x0, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/cmd/tree.go:33 +0x6a6
github.com/Masterminds/cookoo.(*Router).doCommand(0xc82012f820, 0xc820131f50, 0x7f84ab0c2590, 0xc820130b40, 0x0, 0x0, 0x0, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/cookoo/router.go:209 +0x86
github.com/Masterminds/cookoo.(*Router).runRoute(0xc82012f820, 0x8dfa90, 0x4, 0x7f84ab0c2590, 0xc820130b40, 0x8dfa00, 0x0, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/cookoo/router.go:164 +0x4c9
github.com/Masterminds/cookoo.(*Router).HandleRequest(0xc82012f820, 0x8dfa90, 0x4, 0x7f84ab0c2590, 0xc820130b40, 0x8da000, 0x0, 0x0)
	/home/gdm85/.gopath/src/github.com/Masterminds/cookoo/router.go:131 +0x2fc
main.setupHandler(0xc82015e0f0, 0x8dfa90, 0x4, 0x7f84ab0c2590, 0xc820130b40, 0xc82012f820)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/glide.go:392 +0x2aa
main.commands.func11(0xc82015e0f0)
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/glide.go:339 +0x5e
github.com/codegangsta/cli.Command.Run(0x8dfa90, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x967860, 0x37, 0x9bf2a0, ...)
	/home/gdm85/.gopath/src/github.com/codegangsta/cli/command.go:127 +0x1052
github.com/codegangsta/cli.(*App).Run(0xc8200e3500, 0xc820086000, 0x2, 0x2, 0x0, 0x0)
	/home/gdm85/.gopath/src/github.com/codegangsta/cli/app.go:159 +0xc2f
main.main()
	/home/gdm85/.gopath/src/github.com/Masterminds/glide/glide.go:102 +0x494

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

If you want to reproduce it, it should be fairly simple: checkout my [drive project fork](https://github.com/gdm85/drive) (also the [original project](https://github.com/odeke-em/drive) will do the job), then enter ``src`` directory and run at your choice one of:
* ``glide list``
* ``glide tree``
* ``glide init; glide guess``

The last one will still return an error like:
```
Oops! cannot find package "C" in any of:
	/usr/local/go/src/C (from $GOROOT)
```

So I guess this is not addressed (yet). Have you looked at how similar projects handle this? For example [errcheck](https://github.com/kisielk/errcheck) (for which I have [recently updated the matchPackages func](https://github.com/gdm85/gotool/commit/85637c46d0d3e240b4d2e8f253f944114d49235d) in the gotool dependency). I guess somewhere in Go's codebase (or in errcheck codebase) it's applying a filter for these?

**Comment by technosophos** [comment]
Oh, man... the `glide tree` and `glide list` issues were really stupid mistakes I made. I'll go fix those and then look at `guess` too.

**Comment by technosophos** [comment]
@mattfarina since this error caused a panic, we should release 0.6.1 when this fix is confirmed.

@gdm85 I tested on your project (thanks for pointing me to that), and it seems to be working as expected. C is ignored by tree, list, and guess now.

**Comment by gdm85** [comment]
@technosophos yeah, now it is fixed, I confirm :+1:

**Comment by mattfarina** [comment]
@technosophos I'll do a 0.6.1 today.
