### ISSUE TITLE
glide nv returns folders with no Go code

### ISSUE THREAD

**Issue by itsjamie** [Masterminds/glide#84]
go test $(glide nv) returns

warning: "./deb-contents/..." matched no packages
warning: "./debian/..." matched no packages
warning: "./docs/..." matched no packages

Would be awesome if glide novendor did a little introspection to make sure at least there was a single .go file in the folder.

Thanks!

**Comment by technosophos** [comment]
That is a little beyond my original intent with the command... but I kind of like the idea. Originally, I anticipated use cases that might do things with .a or .so files or other non-source things. But in practice, I think we all just use it for source files.

Are we *just* interested in directories with `*.go` files in them?

**Comment by itsjamie** [comment]
If the intent of the novendor command is to add support for the usecase of `go test ./...` but exclude vendor packages then I think this would be nice.

The alternative currently is to do... `go list ./... | grep -v vendor`. Perhaps that is an easier way of implementing this command rather than looking for go files? Depend on go list finding the packages?

**Comment by technosophos** [comment]
@itsjamie If you would like to give that a try, it should work as you describe.

**Comment by itsjamie** [comment]
It's removing the folders that don't have any Go in them, however they don't follow a format that go test understands.

**Comment by itsjamie** [comment]
```
glide nv
controllers interfaces middleware models schedule server services .
```

**Comment by technosophos** [comment]
Ugh... I forgot to add back in the elipses.

On Sun, Sep 20, 2015 at 1:56 PM, Jamie Stackhouse <notifications@github.com>
wrote:

> glide nv
> controllers interfaces middleware models schedule server services .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Masterminds/glide/issues/84#issuecomment-141827445>.
>



-- 
http://technosophos.com
https://github.com/Masterminds

**Comment by technosophos** [comment]
Should be fixed now. Directories come back with `./DIRNAME/...`

I don't have any special casing for the `testdata` directory. I wonder if we need that.

**Comment by itsjamie** [comment]
This solves what I was running into. Thanks!

Out of curiosity, what special cases testdata? A cursory google search revealed a couple of stdlib packages moving their fixtures to that folder, but no reference as to why.

**Comment by technosophos** [comment]
Certain Go tools (notably `build`) ignore the `testdata` directory. I don't know all of the rules about the conditions under which it is ignored. In particular, I don't know if `go test` is supposed to use files in that folder.

I'll poke around and fix as necessary.

**Comment by 13k** [comment]
Sorry to comment on this closed issue, but seems relevant.

Isn't `novendor` supposed to respect the setting `excludeDirs` in `glide.yaml`? Does the `excludeDirs` setting has the same semantics in both resolving imports and `novendor` contexts?
