### ISSUE TITLE
Subpackage behaviour strange

### ISSUE THREAD

**Issue by nizsheanez** [Masterminds/glide#86]
i used file:
- package: golang.org/x/net/context
  ref: master
 
and glide installed repo golang.org/x/net to folder vendor/golang.org/x/net/context 
i think need to show error if somebody write subpackage instead of package

**Comment by mattfarina** [comment]
@nizsheanez Thanks for the bug report.

This relates to #71.

This particular case is caused by the go-get redirect system. Go uses a custom redirect system to have references such as golang.org/x/net that actually live on github.com.
