### ISSUE TITLE
[ERROR]	The Remote does not match the VCS endpoint

### ISSUE THREAD

**Issue by Skarlso** [Masterminds/glide#863]
Hi. 

I'm trying to run `glide install --force --strip-vendor` on a project structure located here: https://github.com/Skarlso/miner

At the end of it (presumably end) I'm getting said error message without any context what so ever. :( So I have no idea what the problem is or might be.

I did clean / delete / kill everything I could and tried again. Even nuked my whole Go folder.

Please help? :)

Thanks.

**Comment by sjansen** [comment]
For the benefit of anyone brought here by Google...

solution: https://github.com/sirupsen/logrus/issues/553#issuecomment-306591437
reason: https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

**Comment by Skarlso** [comment]
This can be closed then.

**Comment by Arlenmbx** [comment]
Great,  commond `glide install --force --strip-vendor` apply to me.
