### ISSUE TITLE
CLA for glide

### ISSUE THREAD

**Issue by Nayana-ibm** [Masterminds/glide#864]
Hi,

We are trying to build glide on big endian. To build glide, we require to add support for bug endian arch.
To contribute for that change, we want to know about Contributor License Agreement.

Please let us know which Contributor License Agreement needs for glide. 
I have checked URL to License: https://github.com/Masterminds/glide/blob/master/LICENSE however what's the CLA glide requires?

**Comment by mattfarina** [comment]
Glide does not currently have a CLA.

**Comment by Nayana-ibm** [comment]
@mattfarina  Thanks for info.
