### ISSUE TITLE
golang.org/x/ packages don't install correctly

### ISSUE THREAD

**Issue by erbridge** [Masterminds/glide#88]
Adding `golang.org/x/net/websockets` to the yaml  causes the whole of `golang.org/x/net` to be checked out into `./vendor/golang.org/x/net/websockets` not just the `websockets` package.

Workaround is to just include `golang.org/x/net` in the yaml.

**Comment by mattfarina** [comment]
@erbridge That bug was fixed this morning. Can you install from master (e.g., `go get -u github.com/Masterminds/glide`) and see if that fixes the problem?

**Comment by erbridge** [comment]
Seems to work.
