### ISSUE TITLE
glide guess <file> fails if file doesn't exist

### ISSUE THREAD

**Issue by tve** [Masterminds/glide#90]
The docs claim " By default, 'glide guess' writes to standard output. But if a filename
        is supplied, the results are written to the file" but that doesn't work if the file doesn't already exist:
```
$ glide guess glide.yaml
Oops! glide.yaml is missing from /home/src/github.com/foo/bar
$ ls
demo  main.go  main_suite_test.go  Makefile
```

**Comment by tve** [comment]
oh, needed to run glide create first...

**Comment by technosophos** [comment]
I should actually see if there is any reason why we require `glide init` to be called first. It seems to me that `glide guess` would make a logical first command to run.
