### ISSUE TITLE
glide list should indicate whether a package is vendored or in GOPATH

### ISSUE THREAD

**Issue by tve** [Masterminds/glide#91]
I expected glide list to tell me which dependencies are not vendored, but it doesn't seem to do so? I thought that "Present: yes" meant "vendored" but it doesn't seem that that's the case. Is there an easy way to tell which dependencies are not in the vendor subdir? (It would be nice if the values for Present in glide list were missing|gopath|vendor.)
Thanks for a nice tool!

**Comment by mattfarina** [comment]
Thanks for the feedback.

The current behavior appears to be that present says yes if the package is in either the GOPATH or the vendor directory. @technosophos is this what it was supposed to do?

I like the idea of telling you if the package being used is in missing, in the gopath, or in the vendor directory. I've personally run into the problem of using a package in the gopath when I thought it was in the vendor directory. Version issues ensued and was a headache to troubleshoot.

@technosophos before I mark this as an enhancement do you have any feedback?

**Comment by technosophos** [comment]
I hadn't thought of displaying the output in terms of what's in GOPATH vs. what's in `vendor/`. That's a great idea. It would actually be really helpful. Let's mark this as a feature.

FWIW, `present` means its installed. If it's marked "no", then there is an unresolved dependency somewhere in your tree.

**Comment by technosophos** [comment]
This is what the new output looks like:

```
$ glide list
github.com/Masterminds/cookoo (Location: vendored)
github.com/Masterminds/cookoo/io (Location: vendored)
github.com/Masterminds/glide/cmd (Location: gopath)
github.com/Masterminds/glide/gb (Location: gopath)
github.com/Masterminds/vcs (Location: vendored)
github.com/codegangsta/cli (Location: gopath)
github.com/kylelemons/go-gypsy/yaml (Location: missing)
```

**Comment by tve** [comment]
Niiice, thanks!
