### ISSUE TITLE
Glide couldn't pull all packages specified by Godeps.json correctly

### ISSUE THREAD

**Issue by aaskey** [Masterminds/glide#912]
Hi there,

Seems Glide couldn't pull all packages specified by Godep correctly. 

Here is what happened in my case. The glide.yaml file is like below:
```
import:
- package: google.golang.org/api/container/v1
- package: k8s.io/client-go
  version: v4.0.0
```
I used
```
glide update --strip-vendor
```
To pull the dependancies to vendor directory to my project.

It turns out that of the 6 go-openapi packages required by client-go, 5 were pulled correctly. However, the "spec" package was pulled incorrectly, here is what is actually in glide.lock:
```
- name: github.com/go-openapi/spec
  version: 7abd5745472fff5eb3685386d5fb8bf38683154d
```
Here is what is expected in Godeps.json from client-go:
```
    {
      "ImportPath": "github.com/go-openapi/spec",
      "Rev": "6aced65f8501fe1217321abf0749d354824ba2ff"
    },
```
The version (7abd574) pulled by Glide was happened to be the last commit at that time. 

Is this an known issues?

**Comment by mattfarina** [comment]
@aaskey This may be an ordering issue when it comes to scanning. Does `google.golang.org/api/container/v1` or one of its dependencies import `github.com/go-openapi/spec`? Try re-ordering packages in the glide.yaml file.

**Comment by aaskey** [comment]
@mattfarina , that's a good point. Is there a fast way to find which package is used by which? I was trying to using "glide tree" but it quickly becomes untraceable with large numbers of dependencies. 

Just want to clarify, how are order defined in Glide? Is it true that the one specified in glide.yaml first, together with its dependencies recursively, will take precedence over the ones specified after?

**Comment by mattfarina** [comment]
@aaskey yes. This gives one a bit of control.
