### ISSUE TITLE
Can you add support for reading dependencies from Gopkg.toml and Gopkg.lock

### ISSUE THREAD

**Issue by dfuentes77** [Masterminds/glide#915]
Now that golang [`dep`](https://github.com/golang/dep) is gaining popularity and use, it would be great if `glide` was able to parse those files for dependencies the same way it does the other dependency managers.

**Comment by mattfarina** [comment]
@dfuentes77 out of curiosity, is there a reason you can't use dep itself? I ask because dep is expected to be the successor to glide. If there is a gap in your needs I'm interested in knowing about it so I can make sure the dep team has it covered.

I'll consider the request.

**Comment by dfuentes77** [comment]
I actually didn't know how far along it was, and I was waiting on Heroku support for it, which seems to be on its way: https://github.com/heroku/heroku-buildpack-go/pull/196.   

Ultimately, I would hope for the entire feature set of Glide :P  I'm spoiled from it's magic. 
  
If you ever follow https://github.com/kennethreitz,  all the features that he's been adding to [pipenv](https://github.com/kennethreitz/pipenv) for python is nothing other than astounding, and a another great example.

**Comment by EronWright** [comment]
One limitation of `dep` that has me looking at glide again is golang/dep#1124; constraints aren't applied transitively, leading to much duplication in the top-level manifest.
