### ISSUE TITLE
vendor.json

### ISSUE THREAD

**Issue by andersfylling** [Masterminds/glide#928]
Can glide please generate a vendor.json file as this is used in docker, heroku and so on.

**Comment by mattfarina** [comment]
Heroku supports glide. See https://devcenter.heroku.com/articles/go-dependencies-via-glide

Not sure what you're talking about when it comes to docker. Can you provide a pointer?

vendor.json and Glide are expected to be overcome by [dep](https://github.com/golang/dep). Have you looked at that?
