### ISSUE TITLE
problem specifically with gopkg. Not allowing compile.

### ISSUE THREAD

**Issue by gedw99** [Masterminds/glide#93]
For github imports all is good, but for gopkg i am getting this issue.

# Context:
go version go1.5.1 darwin/amd64
glide version 0.6.1
atom 1.0.19

# Steps to reproduce
1. ```glide get gopkg.in/alecthomas/kingpin.v2```, and its in my vendor folder. 
2. Test code below. On saving in Atom, fmt forces the path to be:
``` "bitbucket.org/gedw99/berlininfusions-web/vendor/gopkg.in/alecthomas/kingpin.v2" ```
3. ``` go build ```, and it fails with:
"imports bitbucket.org/gedw99/berlininfusions-web/vendor/gopkg.in/alecthomas/kingpin.v2: must be imported as gopkg.in/alecthomas/kingpin.v2".
I cant make atom use this import path though :)

Is it atom, or glide ?

# Test code

```
// +build !appengine
// Above is a special build command: https://blog.golang.org/the-app-engine-sdk-and-workspaces-gopath

package main

import (
	"os"

	"bitbucket.org/gedw99/berlininfusions-web/vendor/gopkg.in/alecthomas/kingpin.v2"
)

func main() {

	// None of this gets gets run by AppEngine

	// cli
	kingpin.Version("0.0.1")
	kingpin.Parse()
}
```

**Comment by mattfarina** [comment]
I'm an atom user and I use it to develop glide itself. It sounds like you are using the `go-plus` community package and you have the format tool set to `goimports`. That's the common setup that causes the import rewriting. Is this right?

It looks like atom isn't picking up the GO15VENDOREXPERIMENT meaning it's not turned on.

In Go 1.5 the GO15VENDOREXPERIMENT needs to be enabled. It's off by default. The plan is for it to be on by default in Go 1.6. Do you have this enabled in your environment? You'd need the environment variable `GO15VENDOREXPERIMENT=1` set along with launching atom from the command line (to open the app for the first time not just to open a new project or file in it). This causes atom to use this environment variable setting.

It doesn't appear that `go-plus` has the ability to enable this outside of launching atom this way.

Can you test this and let me know how it goes?

**Comment by gedw99** [comment]
yes exactly. i am using go-plus in Atom, and yes i have the Format Tool set to use goimports. Default setup basically.

false, I do have the Vendor environment variable set. See below:
gedw99-MacBook-Pro:berlininfusions-web apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/Workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/Workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

I always launch Atom from the command line, using "atom ." 

So not sure why its messing with my imports.
When i manually edit the import to below, go build is happy, so its an atom problem.
import (
	"os"

	"gopkg.in/alecthomas/kingpin.v2"
)

Any ideas ?

**Comment by gedw99** [comment]
repo is here:
https://github.com/gedw99/berlininfusions-web

**Comment by gedw99** [comment]
Also i noticed when i did the glide get gopkg.in/alecthomas/kingpin.v2, i also had to do a glide get
github.com/alecthomas/units
github.com/alecthomas/template

Glide did not get the dependencies itself. No biggy though.

**Comment by mattfarina** [comment]
I've not experienced the atom difficulty you are. I use the latest atom with `go-plus` and have no issues. I wonder what's causing the issues. You may want to open an issue on `go-plus` or dig around in their docs/issues. You may not be the first person to experience this problem.

Glides recursive handling looks for `glide.yaml` files to perform the imports. If the `--import` flag is specified on `glide up` it will work with gb, godep, and GPM files as well.

We've talked about a flag to introspect each package to pull its imports as well but have not done so yet. If you'd like to file a separate issue asking for that we'd look at it.

Since the main issue is an atom one I'm going to close this.

Thanks again for talking with us here about this. We're happy to be helpful.
