### ISSUE TITLE
Fail to install Glide: $LGOBIN issue

### ISSUE THREAD

**Issue by anandumdas** [Masterminds/glide#938]
```
$curl https://glide.sh/get | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4712  100  4712    0     0   3822      0  0:00:01  0:00:01 --:--:--  3824
ARCH=amd64
OS=linux
Using curl as download tool
Getting https://glide.sh/version
TAG=v0.13.1
GLIDE_DIST=glide-v0.13.1-linux-amd64.tar.gz
Downloading https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz
glide not found. Did you add $LGOBIN to your $PATH?
Fail to install glide
```

**Comment by hitzzc** [comment]
+1

**Comment by sanket4373** [comment]
Facing the same issue.. Can someone kindly provide a fix for it?

**Comment by hitzzc** [comment]
Seems set $GOBIN will resolve this problem

**Comment by DSofter** [comment]
@hitzzc What should I set `$GOBIN` to?

**Comment by hitzzc** [comment]
@DSofter $GOBIN=$GOPATH/bin

**Comment by SvenSommer** [comment]
+1

**Comment by hamzahamidi** [comment]
I'm still facing the same issue here. Any solution?

**Comment by hamzahamidi** [comment]
I found a solution though I wouldn't recommend it. I just copied the files in go-workspace/bin to user/local/go/bin

**Comment by DavidGereb** [comment]
putting it together, you need to add the following to your `~/.bash_profile` or `~/.zshrc` if you use zshell
```
export GOPATH=$(go env GOPATH)
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
```

**Comment by DMEvanCT** [comment]
> putting it together, you need to add the following to your `~/.bash_profile` or `~/.zshrc` if you use zshell
> 
> ```
> export GOPATH=$(go env GOPATH)
> export GOBIN=$GOPATH/bin
> export PATH=$PATH:$GOBIN
> ```

You are a rockstar! That saved me a lots of time!

**Comment by vohrahul** [comment]
This issue could be closed.

It perfectly works fine once you set your GOBIN and PATH variable correctly.

````bash 
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
````

**Comment by sxpujs** [comment]
export GOROOT=/usr/local/go
export GOBIN=$GOROOT/bin

**Comment by Cavdy** [comment]
> putting it together, you need to add the following to your `~/.bash_profile` or `~/.zshrc` if you use zshell
> 
> ```
> export GOPATH=$(go env GOPATH)
> export GOBIN=$GOPATH/bin
> export PATH=$PATH:$GOBIN
> ```

Thanks for this... Wow
