### ISSUE TITLE
update brew formula

### ISSUE THREAD

**Issue by jchauncey** [Masterminds/glide#94]
The formula for install glide with brew is out of date.

**Comment by mattfarina** [comment]
@jchauncey the latest release of glide is 0.6.1 which is reflected [in homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/glide.rb). Are you not seeing that version on install?

The tip of master is currently 9 commit ahead of 0.6.1 and we're working on the 0.7.0 release.

What are you seeing and what are you expecting? We're you expecting the tip of master? I'm happy to try and help. Just trying to understand what you're looking for.

**Comment by jchauncey** [comment]
my brew must have been out of date... My fault sorry about that. =)

**Comment by mattfarina** [comment]
@jchauncey no problem. This has happened to me, too.
