### ISSUE TITLE
"Oops! exit status 128" from glide get

### ISSUE THREAD

**Issue by hkjn** [Masterminds/glide#95]
Hey guys,

I installed `glide` using `go get github.com/Masterminds/glide` yesterday and was using it with no apparent issues, but today (after going to a past commit in a repo to make sure I understood exactly what `glide` does in the `vendor/` directory) I noticed it exited with "Oops! exit status 128" when trying to add a dependency to a package after `glide init`, i.e. with only the placeholder `glide.yaml` in the root of the repo:
```
~src/hkjn.me/prober$ glide get github.com/golang/glog
Oops! exit status 128
```
I tried looking through the code, but ended up deep in the `github.com/Masterminds/cookoo` package without becoming much wiser. Let me know how I can get you more info (do you have a flag to increase logging verbosity?), but I wanted to drop this brief report because as is this doesn't tell me much about why the command is failing.

**Comment by mattfarina** [comment]
@hkjn thanks for reaching out. This is one place we can do better with our error messages.

Do you happen to already have `github.com/golang/glog` in your `vendor/` folder? Does the directory `vendor/github.com/golang/glog` already exist?

**Comment by technosophos** [comment]
`exit status 128` is coming from Git.

**Comment by hkjn** [comment]
Unfortunately I've been unable to reproduce the issue: I just now went to the same repo, detached from `HEAD` and went to the same commit I had checked out before, with a clean working directory, but this time `glide init && glide get github.com/golang/glog` worked just as it should. I'm not sure what's different. No `vendor/` directory should have existed when I saw the issue.

Feel free to close this out (or adapt it to be about improving error logging when things fail, your call).

**Comment by technosophos** [comment]
@mattfarina This might be the sort of thing where attaching the output of the VCS command to the error would be helpful. I would guess that the data present in `CombinedOutput` might give a better indication of what went wrong than just the `error` returned -- at least in the case of Git.

**Comment by mattfarina** [comment]
We could capture the output from the VCS command and display it when there's an error. All the parts are there to do that we just need to glue them together.

**Comment by technosophos** [comment]
I just now had a network failure cause an `exit status 128` while fetching `github.com/codegangsta/cli`.

**Comment by mattfarina** [comment]
The gist is that `repo` instances should have a real logger attached before performing a command and then if there's an error write the contents of the log to sdtout. There is a logger property that's supposed to be a Go logger.

**Comment by technosophos** [comment]
I traced this back to here: https://github.com/Masterminds/vcs/blob/master/git.go#L66

**Comment by technosophos** [comment]
I submitted an upstream pull request on VCS. I figured @mattfarina should probably double-check that before merging.

**Comment by mattfarina** [comment]
I just merged in the change by @technosophos and tested it on the tip of master for glide. This provides a much more detailed message now.

Please re-open if there are further issues.
