### ISSUE TITLE
Feature request: Allow multiple packages in `glide get``

### ISSUE THREAD

**Issue by hkjn** [Masterminds/glide#96]
See title: Similarly to how `go get` takes one or more packages to download:
`$ go get github.com/golang/glog github.com/gorilla/context`

I'm suggesting that `glide get` could work the same way, wheras it currently seems to silently swallow all packages after the first:
```
$ glide get github.com/golang/glog github.com/gorilla/context
[INFO] Checking dependencies for updates. Godeps: false, GPM: false, gb: false                                         
[INFO] Inspecting /home/zero/src/hkjn.me/googleauth/vendor.                                                            
[INFO] Looking in /home/zero/src/hkjn.me/googleauth/vendor/github.com/golang/glog for a glide.yaml file.
[INFO] Package github.com/golang/glog manages its own dependencies.
```

**Comment by technosophos** [comment]
That makes sense to me.

The one thing we'd be giving up is the (straightforward) ability to create flags specific to a package (like the `--version=` flag that has been discussed). But that's probably something we could accomplish in another way.

**Comment by technosophos** [comment]
@mattfarina  I left the `cmd.Get` function there, even though I believe it is now unused. It functions fine. Is there any reason to keep it, though? Are we treating the public API as frozen even though we're still pre-1.0?

@hkjn Let me know how this functionality feels to you.

**Comment by mattfarina** [comment]
@technosophos let's not consider the public API frozen yet. It will annoy a few people but we're prerelease and `GO15VENDOREXPERIMENT` is still opt-in. This is a good time for us to make useful changes and annoy as few people as possible.

The only [public things I can find calling the `cmd` package are forks of glide](https://godoc.org/github.com/Masterminds/glide/cmd?importers).

**Comment by technosophos** [comment]
I think I'd feel better just removing it, then, since otherwise we'll end up maintaining two very similar functions.
