### ISSUE TITLE
Glide failing on go4.org since the move

### ISSUE THREAD

**Issue by rickw** [Masterminds/glide#987]
`[ERROR] Update failed for go4.org: The Remote does not match the VCS endpoint`
`[ERROR] Failed to do initial checkout of config: The Remote does not match the VCS endpoint`

The packages I'm using that use it are still listing it as "go4.org" and not the GitHub url. I have no control over those packages so I'm stuck. 

Any dependency managers that handle this properly?

**Comment by rickw** [comment]
switched to `dep`

**Comment by lucab** [comment]
For reference, the underlying repository is at github.com/go4org/go4, but you may need to clean any glide cache to get rid of mismatches.
